/*
* This header is generated by classdump-dyld 0.1
* on Thursday, November 28, 2013 at 4:18:45 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /usr/libexec/DuetLST
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/


#import <DuetLST/DuetLST-Structs.h>
@class NSMutableArray, DuetLST;

@interface DuetLSTqueryCache : NSObject {

	NSMutableArray* cache;
	unsigned long long cacheHits;
	unsigned long long cacheMisses;
	DuetLST* lst;

}

@property (nonatomic,retain) DuetLST * lst; 
@property (nonatomic,retain) NSMutableArray * cache; 
@property (assign,nonatomic) unsigned long long cacheHits; 
@property (assign,nonatomic) unsigned long long cacheMisses; 
-(void)setLst:(id)arg1 ;
-(id)lst;
-(id)initWithLSTinstance:(id)arg1 ;
-(id)queryCacheForParams:(SCD_Struct_Du0*)arg1 ;
-(void)updateCacheForParams:(SCD_Struct_Du0*)arg1 withResults:(id)arg2 ;
-(void)dumpAll:(char*)arg1 ;
-(void)dumpLight:(char*)arg1 ;
-(unsigned long long)cacheHits;
-(void)setCacheHits:(unsigned long long)arg1 ;
-(unsigned long long)cacheMisses;
-(void)setCacheMisses:(unsigned long long)arg1 ;
-(id)cache;
-(void)setCache:(id)arg1 ;
-(void)clearCache;
-(void).cxx_destruct;
@end

