/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 10:35:33 PM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/MobilePhone.app/MobilePhone
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/

#import <MobilePhone/PHStarkGenericTableViewCell.h>

@class UILabel, UIImageView;

@interface PHStarkHardwareMenuTableViewCell : PHStarkGenericTableViewCell {

	UILabel* _mainLabel;
	UIImageView* _iconImageView;

}

@property (retain) UILabel * mainLabel;                      //@synthesize mainLabel=_mainLabel - In the implementation block
@property (retain) UIImageView * iconImageView;              //@synthesize iconImageView=_iconImageView - In the implementation block
-(id)mainLabel;
-(void)setMainLabel:(id)arg1 ;
-(void)dealloc;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2 ;
-(id)iconImageView;
-(void)setIconImageView:(id)arg1 ;
@end

