/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 1:38:51 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/MobilePhone.app/MobilePhone
* classdump-dyld is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/

#import <MobilePhone/PHStarkGenericTableViewController.h>

@class PHRecentsManager;

@interface PHStarkRecentsViewController : PHStarkGenericTableViewController {

	PHRecentsManager* _recentsManager;

}

@property (retain) PHRecentsManager * recentsManager;              //@synthesize recentsManager=_recentsManager - In the implementation block
-(id)recentsManager;
-(void)setRecentsManager:(id)arg1 ;
-(void)recentsManagerSignificantChangeNotification:(id)arg1 ;
-(void)programmaticallySelectRowAtIndexPath:(id)arg1 ;
-(id)titleForNoContentBanner;
-(id)subtitleForNoContentBanner;
-(id)badgeString;
-(void)dealloc;
-(id)init;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(void)viewDidDisappear:(BOOL)arg1 ;
-(float)defaultRowHeight;
@end

