/*
* This header is generated by strong_classdump 0.1
* on Wednesday, November 27, 2013 at 12:01:27 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/MobilePhone.app/MobilePhone
* strong_classdump is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/

#import <MobilePhone/PHVoicemailListViewController.h>
#import <UIKit/UIActionSheetDelegate.h>
#import <MobilePhone/PHVoicemailListViewControllerConcrete.h>

@class NSString, NSArray, UIActionSheet;

@interface PHVoicemailTrashListViewController : PHVoicemailListViewController <UIActionSheetDelegate, PHVoicemailListViewControllerConcrete> {

	UIActionSheet* _clearAllConfirmationActionSheet;

}

@property (readonly) NSString * cellDetailDestructiveActionText; 
@property (readonly) NSString * navigationBarText; 
@property (readonly) NSString * folderName; 
@property (readonly) unsigned flagsToHave; 
@property (readonly) unsigned flagsNotToHave; 
@property (readonly) BOOL popOffIfEmpty; 
@property (readonly) NSString * tableViewDestructiveActionText; 
@property (readonly) NSString * navigationBarTextWithCountFormat; 
@property (readonly) NSArray * childListControllers; 
-(id)cellDetailDestructiveActionText;
-(void)performCellDetailDestructiveActionForVoicemail:(id)arg1 ;
-(unsigned)flagsToHave;
-(unsigned)flagsNotToHave;
-(void)clearAllTapped;
-(void)_trashHandleVoicemailTaskStartedOrEnded:(id)arg1 ;
-(void)_updateClearAllEnabled;
-(void)performTableViewDestructiveActionForVoicemail:(id)arg1 ;
-(void)willShowVoicemails:(id)arg1 ;
-(id)navigationBarText;
-(BOOL)popOffIfEmpty;
-(id)tableViewDestructiveActionText;
-(id)initWithNavigationController:(id)arg1 ;
-(void)dealloc;
-(void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2 ;
-(void)viewWillAppear:(BOOL)arg1 ;
-(id)folderName;
@end

