/*
* This header is generated by strong_classdump 0.1
* on Wednesday, November 27, 2013 at 12:00:30 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/AdSheet.app/AdSheet
* strong_classdump is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/


@protocol ADRewardsJSO_Bindings <JSExport>
@property (nonatomic,retain) JSValue * listener; 
@property (nonatomic,readonly) NSArray * rewardTokens; 
@optional
-(void)reportRedeemFailureForReward:(id)arg1 withErrorMessage:(id)arg2 __JS_EXPORT_AS__reportRedeemFailure:(id)arg3;

@required
-(id)rewardTokens;
-(void)lookupReward:(id)arg1;
-(void)userRedeemedReward:(id)arg1;
-(void)reportRedeemFailureForReward:(id)arg1 withErrorMessage:(id)arg2;
-(void)setListener:(id)arg1;
-(id)listener;
@end

