/*
* This header is generated by strong_classdump 0.1
* on Wednesday, November 27, 2013 at 12:00:28 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/AdSheet.app/AdSheet
* strong_classdump is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/

#import <AdSheet/ADSActionViewController.h>

@class ADSStoryboardController;

@interface ADSStoryboardActionViewController : ADSActionViewController {

	ADSStoryboardController* _storyboardController;

}

@property (nonatomic,retain) ADSStoryboardController * storyboardController;              //@synthesize storyboardController=_storyboardController - In the implementation block
-(id)storyboardController;
-(void)setStoryboardController:(id)arg1 ;
-(void)clientApplicationDidEnterBackground;
-(void)clientApplicationCancelledAction;
-(void)didSetAdSpaceController;
-(void)storyboardDidFinishFirstLoad;
-(void)storyboardDidChangeSupportedOrientations:(unsigned)arg1 ;
-(void)readyToBeginAuthoredTransition;
-(void)dealloc;
-(unsigned)supportedInterfaceOrientations;
@end

