/*
* This header is generated by classdump-dyld 0.1
* on Thursday, November 28, 2013 at 3:59:20 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/AdSheet.app/AdSheet
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/


@protocol ADRemoteUIServicesCancelable;
@interface ADURLOpener : NSObject {

	id _requester;
	<ADRemoteUIServicesCancelable>* _token;

}

@property (nonatomic,retain) <ADRemoteUIServicesCancelable> * token;              //@synthesize token=_token - In the implementation block
@property (assign,nonatomic,__weak) id requester; 
+(id)sharedInstance;
-(void)cancelOpenPermissionRequestForRequester:(id)arg1 ;
-(void)requestPermissionToOpenURL:(id)arg1 forAd:(id)arg2 fromClient:(id)arg3 requester:(id)arg4 completion:(/*^block*/ id)arg5 ;
-(id)requester;
-(void)setRequester:(id)arg1 ;
-(id)token;
-(void)setToken:(id)arg1 ;
@end

