/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 10:35:51 PM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/MusicUIService.app/MusicUIService
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/


@protocol MPServiceMediaPickerController <NSObject>
@required
-(void)serviceMediaPickerSetPrompt:(id)arg1;
-(void)serviceMediaPickerSetAllowsPickingMultipleItems:(BOOL)arg1;
-(void)serviceMediaPickerSetShowsCloudItems:(BOOL)arg1;
-(void)serviceMediaPickerSetUserInterfaceIdiom:(int)arg1;
-(void)serviceMediaPickerSetMediaTypes:(unsigned)arg1;
@end

