/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 1:38:13 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/GameCenterUIService.app/GameCenterUIService
* classdump-dyld is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/


@protocol GKGameProfileCollectionViewControllerServiceDelegate <NSObject>
@required
-(void)gameProfileCollectionViewController:(id)arg1 didChangeToViewState:(int)arg2;
-(void)gameProfileCollectionViewController:(id)arg1 didSelectLeaderboardIdentifier:(id)arg2;
@end

