/*
* This header is generated by strong_classdump 0.1
* on Wednesday, November 27, 2013 at 12:00:47 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/GameCenterUIService.app/GameCenterUIService
* strong_classdump is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/

#import <Game Center~iphone/GKLeaderboardScoreCell.h>

@interface GKLeaderboardScoreLowRankCell : GKLeaderboardScoreCell
+(float)textOffsetForIdiom:(int)arg1 ;
-(void)initialContraints;
@end

