/*
* This header is generated by classdump-dyld 0.1
* on Thursday, November 28, 2013 at 3:59:39 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/GameCenterUIService.app/GameCenterUIService
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/

#import <GameCenterUI/GKBasicCollectionViewDataSource.h>

@class GKGameRecord, GKPlayer;

@interface GKLeaderboardSetListDataSource : GKBasicCollectionViewDataSource {

	GKGameRecord* _game;
	GKPlayer* _player;

}

@property (nonatomic,retain) GKGameRecord * game;              //@synthesize game=_game - In the implementation block
@property (nonatomic,retain) GKPlayer * player;                //@synthesize player=_player - In the implementation block
-(id)initWithGame:(id)arg1 player:(id)arg2 ;
-(id)game;
-(void)setGame:(id)arg1 ;
-(void)refreshContentsForDataType:(unsigned)arg1 userInfo:(id)arg2 updateNotifier:(id)arg3 ;
-(void)configureCollectionView:(id)arg1 ;
-(void)dealloc;
-(id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2 ;
-(id)sectionTitle;
-(id)player;
-(void)setPlayer:(id)arg1 ;
@end

