/*
* This header is generated by strong_classdump 0.1
* on Wednesday, November 27, 2013 at 12:00:49 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/GameCenterUIService.app/GameCenterUIService
* strong_classdump is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/

#import <UIKit/UITableViewCell.h>

@class GKComposeRecipient, GKLabel;

@interface GKRecipientTableViewCell : UITableViewCell {

	GKComposeRecipient* _recipient;
	GKLabel* _nameLabel;
	GKLabel* _labelLabel;
	GKLabel* _addressLabel;

}

@property (nonatomic,retain) GKComposeRecipient * recipient;              //@synthesize recipient=_recipient - In the implementation block
@property (nonatomic,retain) GKLabel * nameLabel;                         //@synthesize nameLabel=_nameLabel - In the implementation block
@property (nonatomic,retain) GKLabel * labelLabel;                        //@synthesize labelLabel=_labelLabel - In the implementation block
@property (nonatomic,retain) GKLabel * addressLabel;                      //@synthesize addressLabel=_addressLabel - In the implementation block
+(id)identifier;
+(float)height;
+(id)cellForRecipient:(id)arg1 ;
-(void)setLabelLabel:(id)arg1 ;
-(id)addressLabel;
-(void)setAddressLabel:(id)arg1 ;
-(id)labelLabel;
-(id)nameLabel;
-(void)setNameLabel:(id)arg1 ;
-(void)dealloc;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2 ;
-(id)recipient;
-(void)setRecipient:(id)arg1 ;
@end

