/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 10:34:57 PM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/GameCenterUIService.app/GameCenterUIService
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/

#import <GameCenterUIService/GKServiceViewController.h>
#import <UIKit/UIAlertViewDelegate.h>
#import <GameCenterUI/GKRemoteSignInViewControllerDelegate.h>

@class GKBubbleFlowAnimator, NSMutableArray, UIAlertView, GKGame;

@interface SignInServiceViewController : GKServiceViewController <UIAlertViewDelegate, GKRemoteSignInViewControllerDelegate> {

	GKBubbleFlowAnimator* _animator;
	int _mode;
	NSMutableArray* _inflightViewControllers;
	UIAlertView* _alertView;

}

@property (nonatomic,retain) GKBubbleFlowAnimator * animator;                       //@synthesize animator=_animator - In the implementation block
@property (assign,nonatomic) int mode;                                              //@synthesize mode=_mode - In the implementation block
@property (nonatomic,retain) NSMutableArray * inflightViewControllers;              //@synthesize inflightViewControllers=_inflightViewControllers - In the implementation block
@property (nonatomic,retain) UIAlertView * alertView;                               //@synthesize alertView=_alertView - In the implementation block
@property (nonatomic,retain) GKGame * game; 
+(id)_remoteViewControllerInterface;
+(id)_exportedInterface;
-(void)constructPrivateViewController;
-(void)presentInitialViewController:(id)arg1 ;
-(id)inflightViewControllers;
-(void)setInflightViewControllers:(id)arg1 ;
-(void)setIntialState:(id)arg1 withReply:(/*^block*/ id)arg2 ;
-(void)remoteViewControllerDidFinish;
-(void)remoteViewControllerDidCancel;
-(void)setAlertView:(id)arg1 ;
-(id)alertView;
-(void)dealloc;
-(id)init;
-(void)alertView:(id)arg1 didDismissWithButtonIndex:(int)arg2 ;
-(void)loadView;
-(void)pushViewController:(id)arg1 animated:(BOOL)arg2 ;
-(void)didShowViewController:(id)arg1 animated:(BOOL)arg2 ;
-(void)setViewControllers:(id)arg1 ;
-(void)setMode:(int)arg1 ;
-(int)mode;
-(id)animator;
-(void)setAnimator:(id)arg1 ;
@end

