/*
* This header is generated by classdump-dyld 0.1
* on Thursday, November 28, 2013 at 4:00:26 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/MobileSafari.app/MobileSafari
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/

#import <MobileSafari/MobileSafari-Structs.h>
#import <UIKit/UIWebScrollView.h>

@interface BrowserControllerScrollView : UIWebScrollView {

	UIEdgeInsets _hitTestInsets;

}

@property (assign,nonatomic) UIEdgeInsets hitTestInsets;              //@synthesize hitTestInsets=_hitTestInsets - In the implementation block
-(void)setHitTestInsets:(UIEdgeInsets)arg1 ;
-(UIEdgeInsets)hitTestInsets;
-(id)hitTest:(CGPoint)arg1 withEvent:(id)arg2 ;
@end

