/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 1:37:39 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /usr/lib/libAWDProtobufAirPlay.dylib
* classdump-dyld is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/

#import <libAWDProtobufAirPlay.dylib/libAWDProtobufAirPlay.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>

@class NSString;

@interface AWDAirPlaySessionStarted : PBCodable {

	unsigned long long _timestamp;
	unsigned _audioCompressionType;
	unsigned _initiator;
	unsigned _sessionType;
	NSString* _sessionUUID;
	unsigned _transportType;
	SCD_Struct_AW1 _has;

}

@property (nonatomic,readonly) BOOL hasSessionUUID; 
@property (nonatomic,retain) NSString * sessionUUID;                     //@synthesize sessionUUID=_sessionUUID - In the implementation block
@property (assign,nonatomic) BOOL hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;               //@synthesize timestamp=_timestamp - In the implementation block
@property (assign,nonatomic) BOOL hasInitiator; 
@property (assign,nonatomic) unsigned initiator;                         //@synthesize initiator=_initiator - In the implementation block
@property (assign,nonatomic) BOOL hasSessionType; 
@property (assign,nonatomic) unsigned sessionType;                       //@synthesize sessionType=_sessionType - In the implementation block
@property (assign,nonatomic) BOOL hasTransportType; 
@property (assign,nonatomic) unsigned transportType;                     //@synthesize transportType=_transportType - In the implementation block
@property (assign,nonatomic) BOOL hasAudioCompressionType; 
@property (assign,nonatomic) unsigned audioCompressionType;              //@synthesize audioCompressionType=_audioCompressionType - In the implementation block
-(void)dealloc;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned)hash;
-(id)description;
-(unsigned long long)timestamp;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(id)dictionaryRepresentation;
-(BOOL)hasTransportType;
-(void)setTransportType:(unsigned)arg1 ;
-(void)setHasTransportType:(BOOL)arg1 ;
-(unsigned)initiator;
-(void)setSessionUUID:(id)arg1 ;
-(void)setAudioCompressionType:(unsigned)arg1 ;
-(BOOL)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(unsigned)transportType;
-(BOOL)hasTimestamp;
-(void)setHasTimestamp:(BOOL)arg1 ;
-(BOOL)hasSessionUUID;
-(id)sessionUUID;
-(BOOL)hasInitiator;
-(void)setInitiator:(unsigned)arg1 ;
-(void)setHasInitiator:(BOOL)arg1 ;
-(BOOL)hasSessionType;
-(unsigned)sessionType;
-(void)setSessionType:(unsigned)arg1 ;
-(BOOL)hasAudioCompressionType;
-(unsigned)audioCompressionType;
-(void)setHasSessionType:(BOOL)arg1 ;
-(void)setHasAudioCompressionType:(BOOL)arg1 ;
@end

