/*
* This header is generated by classdump-dyld 0.1
* on Thursday, November 28, 2013 at 3:59:16 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /usr/lib/system/libxpc.dylib
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/

#import <libxpc.dylib/OS_xpc_object.h>
#import <libxpc.dylib/OS_xpc_endpoint.h>

@protocol OS_xpc_endpoint <OS_xpc_object>@end


@interface OS_xpc_endpoint : OS_xpc_object <OS_xpc_endpoint>
+(void)load;
@end

