/*
* This header is generated by strong_classdump 0.1
* on Wednesday, November 27, 2013 at 12:02:14 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/WebViewService.app/WebViewService
* strong_classdump is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/

#import <WebViewService/WebViewService-Structs.h>
#import <UIKit/UIApplicationDelegate.h>

@class UIWindow;

@interface WebViewServiceApplicationDelegate : NSObject <UIApplicationDelegate>

@property (nonatomic,retain) UIWindow * window; 
-(void)applicationDidFinishLaunching:(id)arg1 ;
@end

