/*
* This header is generated by classdump-dyld 0.1
* on Thursday, November 28, 2013 at 3:59:22 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/AppStore.app/AppStore
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/


@protocol UISearchBarDelegate <UIBarPositioningDelegate>
@optional
-(void)searchBar:(id)arg1 textDidChange:(id)arg2;
-(void)searchBar:(id)arg1 selectedScopeButtonIndexDidChange:(int)arg2;
-(BOOL)searchBarShouldBeginEditing:(id)arg1;
-(BOOL)searchBarShouldEndEditing:(id)arg1;
-(void)searchBarCancelButtonClicked:(id)arg1;
-(void)searchBarBookmarkButtonClicked:(id)arg1;
-(void)searchBarResultsListButtonClicked:(id)arg1;
-(void)searchBarTextDidBeginEditing:(id)arg1;
-(void)searchBarTextDidEndEditing:(id)arg1;
-(void)searchBarSearchButtonClicked:(id)arg1;
-(BOOL)searchBar:(id)arg1 shouldChangeTextInRange:(NSRange)arg2 replacementText:(id)arg3;
@end

