/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 10:35:46 PM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/MobileSafari.app/safarifetcherd
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/


@class NSString, NSMutableDictionary;

@interface BackgroundTaskAgent : NSObject {

	NSString* _name;
	NSMutableDictionary* _jobMap;

}

@property (nonatomic,readonly) NSString * name;              //@synthesize name=_name - In the implementation block
+(id)sharedBackgroundTaskAgent;
-(void)scheduleJob:(id)arg1 ;
-(void)unscheduleJob:(id)arg1 ;
-(id)initWithName:(id)arg1 dispatchQueue:(id)arg2 ;
-(id)name;
@end

