/*
* This header is generated by strong_classdump 0.1
* on Wednesday, November 27, 2013 at 12:01:34 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/MobileSafari.app/MobileSafari
* strong_classdump is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/

#import <MobileSafari/MobileSafari-Structs.h>
#import <UIKit/UIButton.h>

@class UIView, CloudTab;

@interface CloudTabItemView : UIButton {

	UIView* _separatorView;
	CloudTab* _cloudTab;

}

@property (nonatomic,retain) CloudTab * cloudTab;              //@synthesize cloudTab=_cloudTab - In the implementation block
@property (assign,nonatomic) BOOL showsSeparator; 
-(id)cloudTab;
-(void)setCloudTab:(id)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(void)setHighlighted:(BOOL)arg1 ;
-(BOOL)showsSeparator;
-(void)setShowsSeparator:(BOOL)arg1 ;
@end

