/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 10:35:46 PM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/MobileSafari.app/safarifetcherd
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/


@protocol SiteIconDownloadRequestDelegate <NSObject>
@required
-(void)siteIconDownloadRequestDidFail:(id)arg1;
-(void)siteIconDownloadRequest:(id)arg1 didLoadIconData:(id)arg2;
-(void)siteIconDownloadRequest:(id)arg1 didComputeIconKeyColor:(id)arg2;
@end

