/*
* This header is generated by strong_classdump 0.1
* on Wednesday, November 27, 2013 at 12:01:37 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/MobileSafari.app/MobileSafari
* strong_classdump is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/

#import <MobileSafari/MobileSafari-Structs.h>
#import <UIKit/UIViewController.h>
#import <MobileSafari/BookmarksPanelStateRestoring.h>
#import <MobileSafari/CatalogCategoryViewController.h>
#import <UIKit/UITableViewDelegate.h>
#import <UIKit/UITableViewDataSource.h>

@protocol SocialLinksViewControllerDelegate;
@class UITableViewController, NSMutableArray, _UIContentUnavailableView, , NSString, UIButton;

@interface SocialLinksViewController : UIViewController <BookmarksPanelStateRestoring, CatalogCategoryViewController, UITableViewDelegate, UITableViewDataSource> {

	UITableViewController* _tableViewController;
	NSMutableArray* _cachedItems;
	_UIContentUnavailableView* _explanationView;
	BOOL _finishedFirstRequest;
	<SocialLinksViewControllerDelegate>* _delegate;

}

@property (assign,nonatomic) <SocialLinksViewControllerDelegate> * delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,readonly) NSString * collectionType; 
@property (nonatomic,readonly) UIButton * navigationBarButton; 
+(BOOL)hasAnyAccount;
-(id)currentStateDictionary;
-(BOOL)restoreStateWithDictionary:(id)arg1 ;
-(float)currentScrollPosition;
-(void)restoreScrollPosition:(float)arg1 ;
-(id)collectionType;
-(id)bookmarksNavigationController;
-(void)_clearExplanationView;
-(void)_updatePopoverSize;
-(id)safari_tableViewForScrollPositionSaving;
-(id)safari_tableViewScrollPositionSaveIdentifier;
-(void)_showExplanationView;
-(void)_itemsChanged:(id)arg1 ;
-(void)_requestCompleted:(id)arg1 ;
-(void)refreshStateChanged:(id)arg1 ;
-(void)_updateExplanationViewVisibility;
-(void)dealloc;
-(void)setDelegate:(id)arg1 ;
-(id)init;
-(float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2 ;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(id)delegate;
-(void)viewWillAppear:(BOOL)arg1 ;
-(CGSize)preferredContentSize;
-(void)loadView;
-(void)viewWillDisappear:(BOOL)arg1 ;
-(void)_accountsChanged:(id)arg1 ;
@end

