/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 10:52:17 PM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /usr/libexec/routined
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/


#import <routined/routined-Structs.h>
@interface RTUtility : NSObject
+(BOOL)isIntegrityOfFileCompromised:(id)arg1 afterSuccessfulOpen:(BOOL)arg2 ;
+(unsigned long)crcFromData:(id)arg1 ;
+(id)managedPreferencesPath;
+(id)defaultsDomain;
+(id)frameworkBundlePath;
+(id)getBundleVersionFromPath:(id)arg1 ;
+(id)getSystemModel;
+(id)getSystemVersion;
+(id)getSystemInfoByName:(id)arg1 ;
+(id)getFirstOpenFailureTimestampKeyForPath:(id)arg1 ;
+(id)getConsecutiveOpenFailuresKeyForPath:(id)arg1 ;
+(id)executablePathFromPid:(int)arg1 ;
+(int)pidFromAuditToken:(SCD_Struct_RT2)arg1 ;
+(id)logDirectoryPath;
+(BOOL)isInternalInstall;
+(id)cacheDirectoryPath;
@end

