/*
* This header is generated by strong_classdump 0.1
* on Wednesday, November 27, 2013 at 12:02:05 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Stocks.app/Stocks
* strong_classdump is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/


#import <Stocks/Stocks-Structs.h>
@class UITouch, UIImageView, UIView;

@interface HUDTouchInfo : NSObject {

	UITouch* _touch;
	UIImageView* _dot;
	UIView* _bar;
	CGPoint _plottedLocation;
	CGPoint _locationInHUD;
	SCD_Struct_HU2 _stockValue;

}

@property (assign,nonatomic) SCD_Struct_HU2 stockValue;              //@synthesize stockValue=_stockValue - In the implementation block
@property (assign,nonatomic) CGPoint plottedLocation;                //@synthesize plottedLocation=_plottedLocation - In the implementation block
@property (assign,nonatomic) CGPoint locationInHUD;                  //@synthesize locationInHUD=_locationInHUD - In the implementation block
@property (assign,nonatomic,__weak) UITouch * touch;                 //@synthesize touch=_touch - In the implementation block
@property (nonatomic,retain) UIImageView * dot;                      //@synthesize dot=_dot - In the implementation block
@property (nonatomic,retain) UIView * bar;                           //@synthesize bar=_bar - In the implementation block
-(SCD_Struct_HU2)stockValue;
-(void)setStockValue:(SCD_Struct_HU2)arg1 ;
-(CGPoint)plottedLocation;
-(void)setPlottedLocation:(CGPoint)arg1 ;
-(CGPoint)locationInHUD;
-(void)setLocationInHUD:(CGPoint)arg1 ;
-(id)dot;
-(void)setDot:(id)arg1 ;
-(id)bar;
-(void)setBar:(id)arg1 ;
-(id)description;
-(id)touch;
-(void)setTouch:(id)arg1 ;
-(void).cxx_destruct;
@end

