/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 10:36:12 PM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Stocks.app/Stocks
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>

@class StockPickerViewController;

@interface StocksBackSideViewController : UIViewController {

	StockPickerViewController* _pickerViewController;
	BOOL _isShowing;

}
-(void)showStockPicker;
-(void)cancelPicker;
-(void)dealloc;
-(id)view;
-(void)viewWillAppear:(BOOL)arg1 ;
-(id)contentScrollView;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(void)loadView;
-(void)viewDidAppear:(BOOL)arg1 ;
-(void)viewWillDisappear:(BOOL)arg1 ;
-(BOOL)isLoading;
-(BOOL)isShowing;
-(void)updateDoneButton;
-(void).cxx_destruct;
@end

