/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 10:36:12 PM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Stocks.app/Stocks
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>

@class NSTimer, UIWindow, Stock;

@interface StocksController : UIViewController {

	BOOL _reachabilityCancelledLoads;
	BOOL _suspending;
	BOOL _dataIsLive;
	int _rowDataType;
	NSTimer* _updateTimer;
	UIWindow* _window;
	Stock* _selectedStock;

}

@property (nonatomic,retain) UIWindow * window;                  //@synthesize window=_window - In the implementation block
@property (nonatomic,retain) Stock * selectedStock;              //@synthesize selectedStock=_selectedStock - In the implementation block
+(id)sharedStocksController;
-(void)stopUpdateTimer;
-(void)reachabilityChanged:(id)arg1 ;
-(void)setSelectedStock:(id)arg1 ;
-(id)selectedStock;
-(void)prepareForApplicationScreenshot;
-(void)viewFullQuoteForStock:(id)arg1 ;
-(BOOL)dataIsLive;
-(id)chartView;
-(id)newsView;
-(void)updateChartData;
-(void)updateStockData;
-(void)didUpdateQuotes;
-(void)didUpdateMetadata;
-(void)_restoreSelectedStock;
-(void)startUpdateTimer;
-(void)setSelectedStock:(id)arg1 writeToDefaults:(BOOL)arg2 ;
-(void)updateLoadingStatus;
-(void)didBecomeActive;
-(id)listView;
-(void)dealloc;
-(id)window;
-(void)setWindow:(id)arg1 ;
-(void)suspend;
-(void)run;
-(void)resume;
-(BOOL)isNetworkReachable;
-(BOOL)isLoading;
-(void)willResignActive;
-(void)resetLocale;
-(void).cxx_destruct;
@end

