/*
* This header is generated by strong_classdump 0.1
* on Wednesday, November 27, 2013 at 12:02:06 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Stocks.app/Stocks
* strong_classdump is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/

#import <UIKit/UITableViewCell.h>

@class StockNewsItem, UILabel;

@interface StockNewsTableViewCell : UITableViewCell {

	StockNewsItem* _newsItem;
	UILabel* _headlineLabel;
	UILabel* _summaryLabel;
	UILabel* _infoLabel;
	BOOL _showSeparator;

}
-(void)updateBackgroundColor;
-(void)setNewsItem:(id)arg1 showingSeparator:(BOOL)arg2 table:(id)arg3 ;
-(void)layoutSubviews;
-(id)description;
-(id)initWithReuseIdentifier:(id)arg1 ;
-(void)setHighlighted:(BOOL)arg1 animated:(BOOL)arg2 ;
-(void)setSelected:(BOOL)arg1 animated:(BOOL)arg2 ;
-(void)prepareForReuse;
-(id)newsItem;
-(void).cxx_destruct;
@end

