/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 1:39:29 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Stocks.app/Stocks
* classdump-dyld is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/

#import <Stocks/Stocks-Structs.h>
#import <UIKit/UIView.h>
#import <UIKit/UITableViewDelegate.h>
#import <UIKit/UITableViewDataSource.h>

@class StocksBacksideTableView, UISegmentedControl, UIButton;

@interface StocksBacksideView : UIView <UITableViewDelegate, UITableViewDataSource> {

	StocksBacksideTableView* _table;
	UISegmentedControl* _segmentedControl;
	UIButton* _logoView;
	BOOL _didScroll;
	BOOL _suppressNotifications;

}
-(void)selectedSegmentChanged;
-(void)_logoClicked;
-(void)_stockListChanged;
-(void)_stockWasAdded:(id)arg1 ;
-(unsigned)numberOfPlaceholderCells;
-(void)setSelectedRowDataType:(int)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)layoutSubviews;
-(BOOL)tableView:(id)arg1 shouldIndentWhileEditingRowAtIndexPath:(id)arg2 ;
-(id)tableView:(id)arg1 targetIndexPathForMoveFromRowAtIndexPath:(id)arg2 toProposedIndexPath:(id)arg3 ;
-(void)scrollViewDidScroll:(id)arg1 ;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(BOOL)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2 ;
-(BOOL)tableView:(id)arg1 canMoveRowAtIndexPath:(id)arg2 ;
-(void)tableView:(id)arg1 commitEditingStyle:(int)arg2 forRowAtIndexPath:(id)arg3 ;
-(void)tableView:(id)arg1 moveRowAtIndexPath:(id)arg2 toIndexPath:(id)arg3 ;
-(void)flashScrollIndicators;
-(id)tableView;
-(void)viewWillAppear;
-(void).cxx_destruct;
-(void)willHide;
@end

