/*
* This header is generated by strong_classdump 0.1
* on Wednesday, November 27, 2013 at 12:02:06 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Stocks.app/Stocks
* strong_classdump is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/

typedef struct CGPoint {
	float x;
	float y;
} CGPoint;

typedef struct CGGradient* CGGradientRef;

typedef struct {
	double unixTime;
	double price;
	unsigned long long volume;
} SCD_Struct_HU2;

typedef struct CGSize {
	float width;
	float height;
} CGSize;

typedef struct CGRect {
	CGPoint origin;
	CGSize size;
} CGRect;

