/*
* This header is generated by classdump-dyld 0.1
* on Thursday, November 28, 2013 at 3:59:07 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /usr/lib/libMobileGestaltExtensions.dylib
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/


@protocol OS_dispatch_queue, OS_dispatch_source;
#import <libMobileGestaltExtensions.dylib/libMobileGestaltExtensions.dylib-Structs.h>
@class NSString, NSObject;

@interface MGFileWatcher : NSObject {

	NSString* _path;
	unsigned long long _inode;
	timespec _mtime;
	NSObject<OS_dispatch_queue>* _queue;
	NSObject<OS_dispatch_source>* _src;
	NSObject<OS_dispatch_source>* _parentSrc;
	/*^block*/ id _block;

}
-(void)dealloc;
-(void)cancel;
-(bool)updateWatcher;
-(id)initWithPath:(id)arg1 block:(/*^block*/ id)arg2 ;
@end

