/*
* This header is generated by classdump-dyld 0.1
* on Thursday, November 28, 2013 at 4:19:08 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /usr/libexec/tzd
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/


@class TZAssetClient;

@interface TZUpdateManager : NSObject {

	BOOL _localQueryOnly;
	TZAssetClient* _assetClient;

}

@property (assign,nonatomic) BOOL localQueryOnly;                      //@synthesize localQueryOnly=_localQueryOnly - In the implementation block
@property (nonatomic,retain) TZAssetClient * assetClient;              //@synthesize assetClient=_assetClient - In the implementation block
+(id)sharedTimeZoneUpdateManager;
-(void)mobileAssetNewMetadataNotificationHandler:(id)arg1 ;
-(void)mobileAssetNewAssetInstalledHandler:(id)arg1 ;
-(id)assetClient;
-(BOOL)localQueryOnly;
-(void)finishWithStatus:(BOOL)arg1 error:(id*)arg2 ;
-(void)setAssetClient:(id)arg1 ;
-(void)setLocalQueryOnly:(BOOL)arg1 ;
-(void)dealloc;
-(id)init;
-(void).cxx_destruct;
-(void)fetchAssets;
@end

