#import <libAWDProtobufSiri.dylib/AWDSiriNetworkAnalyzerRun.h>
#import <libAWDProtobufSiri.dylib/AWDSiriServerConnectionFailed.h>
#import <libAWDProtobufSiri.dylib/AWDSiriServerConnectionOpen.h>
#import <libAWDProtobufSiri.dylib/AWDSiriServerConnectionStart.h>
#import <libAWDProtobufSiri.dylib/AWDSiriSpeechRecognized.h>
#import <libAWDProtobufSiri.dylib/AWDSiriVoiceRecordingEnd.h>
#import <libAWDProtobufSiri.dylib/AWDSiriVoiceRecordingStart.h>
#import <libAWDProtobufSiri.dylib/AWDSiriVoiceSendEnd.h>
#import <libAWDProtobufSiri.dylib/AWDSiriVoiceSendStart.h>
