/*
* This header is generated by strong_classdump 0.1
* on Wednesday, November 27, 2013 at 12:42:38 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /usr/libexec/aosnotifyd
* strong_classdump is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/


@class NSString;

@interface AOSAccount : NSObject {

	BOOL _isActive;
	NSString* _uuid;

}

@property (nonatomic,retain) NSString * uuid;                    //@synthesize uuid=_uuid - In the implementation block
@property (nonatomic,readonly) NSString * uniqueId; 
@property (nonatomic,readonly) BOOL isValid; 
@property (assign,nonatomic) BOOL isActive;                      //@synthesize isActive=_isActive - In the implementation block
-(void)copyInfoFromAccount:(id)arg1 ;
-(BOOL)supportsMultipleActiveAccounts;
-(BOOL)hasSameRelevantInfoAs:(id)arg1 ;
-(id)init;
-(BOOL)isActive;
-(BOOL)isValid;
-(void)setIsActive:(BOOL)arg1 ;
-(id)uniqueId;
-(id)uuid;
-(void)setUuid:(id)arg1 ;
-(void).cxx_destruct;
@end

