/*
* This header is generated by strong_classdump 0.1
* on Wednesday, November 27, 2013 at 12:42:38 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /usr/libexec/aosnotifyd
* strong_classdump is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/


@class NSDictionary, AOSFindBaseServiceProvider, NSString;

@interface AOSCommandHandler : NSObject {

	NSDictionary* _commandParams;
	AOSFindBaseServiceProvider* _provider;

}

@property (nonatomic,retain) NSDictionary * commandParams;                              //@synthesize commandParams=_commandParams - In the implementation block
@property (assign,nonatomic,__weak) AOSFindBaseServiceProvider * provider;              //@synthesize provider=_provider - In the implementation block
@property (nonatomic,readonly) NSString * commandName; 
@property (nonatomic,readonly) NSString * commandID; 
@property (nonatomic,readonly) BOOL isPreviouslyHandledCommand; 
@property (nonatomic,readonly) NSDictionary * ackDataForCommand; 
-(id)loggingID;
-(void)setCommandParams:(id)arg1 ;
-(id)commandID;
-(BOOL)isPreviouslyHandledCommand;
-(void)handleCommand;
-(void)sendAck;
-(id)commandParams;
-(id)initWithParams:(id)arg1 provider:(id)arg2 ;
-(void)executeCommand;
-(id)ackDataForCommand;
-(void)didHandleCommandWithAckData:(id)arg1 ;
-(void)setProvider:(id)arg1 ;
-(id)commandName;
-(void)dealloc;
-(void).cxx_destruct;
-(id)provider;
@end

