/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 1:55:07 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /usr/libexec/aosnotifyd
* classdump-dyld is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/


@class NSString, NSDictionary, NSDate;

@interface AOSMonitoredFence : NSObject {

	NSString* _fenceId;
	int _triggerType;
	NSString* _triggerURL;
	NSDictionary* _contextDict;
	int _lastTrigger;
	NSDate* _lastTriggerTimestamp;
	NSDate* _lastAddedToCL;
	double _latitude;
	double _longitude;
	double _radius;

}

@property (nonatomic,retain) NSString * fenceId;                         //@synthesize fenceId=_fenceId - In the implementation block
@property (assign,nonatomic) int triggerType;                            //@synthesize triggerType=_triggerType - In the implementation block
@property (nonatomic,retain) NSString * triggerURL;                      //@synthesize triggerURL=_triggerURL - In the implementation block
@property (assign,nonatomic) double latitude;                            //@synthesize latitude=_latitude - In the implementation block
@property (assign,nonatomic) double longitude;                           //@synthesize longitude=_longitude - In the implementation block
@property (assign,nonatomic) double radius;                              //@synthesize radius=_radius - In the implementation block
@property (nonatomic,retain) NSDictionary * contextDict;                 //@synthesize contextDict=_contextDict - In the implementation block
@property (assign,nonatomic) int lastTrigger;                            //@synthesize lastTrigger=_lastTrigger - In the implementation block
@property (nonatomic,retain) NSDate * lastTriggerTimestamp;              //@synthesize lastTriggerTimestamp=_lastTriggerTimestamp - In the implementation block
@property (nonatomic,retain) NSDate * lastAddedToCL;                     //@synthesize lastAddedToCL=_lastAddedToCL - In the implementation block
-(id)triggerURL;
-(int)lastTrigger;
-(id)fenceId;
-(id)contextDict;
-(id)lastTriggerTimestamp;
-(id)lastAddedToCL;
-(void)setFenceId:(id)arg1 ;
-(void)setTriggerURL:(id)arg1 ;
-(void)setContextDict:(id)arg1 ;
-(void)setLastTrigger:(int)arg1 ;
-(void)setLastTriggerTimestamp:(id)arg1 ;
-(void)setLastAddedToCL:(id)arg1 ;
-(void)setLatitude:(double)arg1 ;
-(void)setLongitude:(double)arg1 ;
-(id)description;
-(double)latitude;
-(double)longitude;
-(void)setRadius:(double)arg1 ;
-(double)radius;
-(void)setTriggerType:(int)arg1 ;
-(int)triggerType;
-(void).cxx_destruct;
@end

