/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 10:51:58 PM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /usr/libexec/aosnotifyd
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/

#import <aosnotifyd/AOSServiceProvider.h>
#import <aosnotifyd/AOSAPSDelegate.h>

@class NSString;

@interface AOSPushServiceProvider : AOSServiceProvider <AOSAPSDelegate> {

	NSString* _appId;

}

@property (nonatomic,retain) NSString * appId;              //@synthesize appId=_appId - In the implementation block
-(void)deinitializeProvider;
-(void)accountDeactivated;
-(void)didReceiveAPSMessage:(id)arg1 ;
-(void)didReceiveAPSToken:(id)arg1 ;
-(id)serviceName;
-(void)start;
-(id)appId;
-(void)setAppId:(id)arg1 ;
-(void).cxx_destruct;
@end

