/*
* This header is generated by strong_classdump 0.1
* on Wednesday, November 27, 2013 at 12:42:38 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /usr/libexec/aosnotifyd
* strong_classdump is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/


@class AOSAccount, NSString;

@interface AOSServiceProvider : NSObject {

	AOSAccount* _account;

}

@property (nonatomic,retain) AOSAccount * account;                  //@synthesize account=_account - In the implementation block
@property (nonatomic,readonly) NSString * serviceName; 
-(void)accountDidChange;
-(void)deinitializeProvider;
-(void)accountDeactivated;
-(void)_accountDidDeactivateHandler:(id)arg1 ;
-(void)_accountDidChangeHandler:(id)arg1 ;
-(id)serviceName;
-(void)start;
-(void)stop;
-(id)account;
-(void)setAccount:(id)arg1 ;
-(void).cxx_destruct;
@end

