/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 1:55:14 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /usr/libexec/aosnotifyd
* classdump-dyld is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/


#import <aosnotifyd/aosnotifyd-Structs.h>
@class NSString;

@interface AOSSigningSession : NSObject {

	NACContextOpaque_Ref _context;
	OpaqueCFHTTPCookieStorageRef _cookieStorage;
	long _error;
	NSString* _certURL;
	NSString* _sessionURL;

}

@property (assign,nonatomic) long error;                         //@synthesize error=_error - In the implementation block
@property (nonatomic,retain) NSString * certURL;                 //@synthesize certURL=_certURL - In the implementation block
@property (nonatomic,retain) NSString * sessionURL;              //@synthesize sessionURL=_sessionURL - In the implementation block
-(id)sessionURL;
-(void)_fetchUrls;
-(id)certURL;
-(id)_sessionCreationURLRequest;
-(id)_configurationURLRequest;
-(void)setCertURL:(id)arg1 ;
-(void)setSessionURL:(id)arg1 ;
-(id)_clientInfoHeader;
-(void)setError:(long)arg1 ;
-(id)signatureForData:(id)arg1 ;
-(void)dealloc;
-(id)init;
-(void)establishSession;
-(long)error;
-(void).cxx_destruct;
@end

