/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 10:51:58 PM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /usr/libexec/aosnotifyd
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/


@class NSString, NSDictionary;

@interface FMFConfig : NSObject {

	BOOL _pushNotificationSettingsUpToDate;
	BOOL _fmfAppInfoUpToDate;

}

@property (nonatomic,readonly) BOOL isFMFLocationServicesEnabled; 
@property (nonatomic,readonly) BOOL isFMFAppInstalled; 
@property (nonatomic,readonly) NSString * fmfVersion; 
@property (nonatomic,readonly) NSString * fmfBuildVersion; 
@property (nonatomic,readonly) NSDictionary * fmfPushNotificationSettings; 
+(id)sharedInstance;
-(id)initSingleton;
-(void)refreshFMFAppInstallationState;
-(BOOL)isFMFAppInstalled;
-(BOOL)isFMFLocationServicesEnabled;
-(id)fmfVersion;
-(id)fmfBuildVersion;
-(id)fmfPushNotificationSettings;
-(void)fmfPushNotificationSettingsMayNeedUpdate;
-(void)fmfAppInfoMayNeedUpdate:(id)arg1 ;
-(id)_fmfAppInfoDict;
-(void)dealloc;
@end

