/*
* This header is generated by strong_classdump 0.1
* on Wednesday, November 27, 2013 at 12:01:59 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Reminders.app/Reminders
* strong_classdump is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/


@protocol RemindersLocationPickerModelDelegate <NSObject>
@required
-(void)locationPickerModelDidUpdateCurrentLocation:(id)arg1;
-(void)locationPickerModelDidUpdateCustomLocation:(id)arg1;
-(void)locationPickerModel:(id)arg1 didUpdateMeCardItem:(int)arg2;
-(void)locationPickerModelDidChangeSelection:(id)arg1;
-(void)locationPickerModel:(id)arg1 didEncounterError:(id)arg2;
@end

