/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 1:39:22 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Reminders.app/Reminders
* classdump-dyld is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/

#import <UIKit/UITableViewCell.h>

@interface RemindersListCell : UITableViewCell {

	BOOL _drawsSeparator;

}

@property (assign,nonatomic) BOOL drawsSeparator;              //@synthesize drawsSeparator=_drawsSeparator - In the implementation block
-(void)setDrawsSeparator:(BOOL)arg1 ;
-(float)titleHeight;
-(BOOL)drawsSeparator;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2 ;
@end

