/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 1:55:22 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /usr/libexec/gamed
* classdump-dyld is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/

#import <gamed/GKService.h>
#import <GameCenterFoundation/GKAccountService.h>

@interface GKAccountService : GKService <GKAccountService>
+(Class)interfaceClass;
+(unsigned long)requiredEntitlements;
-(void)_handleServerStatus:(int)arg1 ;
-(oneway void)generateIdentityVerificationSignatureWithHandler:(/*^block*/ id)arg1 ;
-(oneway void)authenticatePlayerWithExistingCredentialsWithHandler:(/*^block*/ id)arg1 ;
@end

