/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 1:55:18 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /usr/libexec/gamed
* classdump-dyld is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/

#import <gamed/GKListCacheObject.h>

@class NSString;

@interface GKCompatibilityListCacheObject : GKListCacheObject {

	NSString* _version;
	NSString* _bundleID;

}

@property (nonatomic,retain) NSString * bundleID;              //@synthesize bundleID=_bundleID - In the implementation block
@property (nonatomic,retain) NSString * version;               //@synthesize version=_version - In the implementation block
+(Class)entryClass;
+(id)entityName;
-(void)updateWithServerRepresentation:(id)arg1 expirationDate:(id)arg2 ;
-(id)bundleID;
-(void)setVersion:(id)arg1 ;
-(id)version;
-(void)setBundleID:(id)arg1 ;
@end

