/*
* This header is generated by strong_classdump 0.1
* on Wednesday, November 27, 2013 at 12:42:45 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /usr/libexec/gamed
* strong_classdump is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/

#import <gamed/GKExpiringCacheObject.h>

@class NSNumber, GKGameCacheObject;

@interface GKFlowRateCacheObject : GKExpiringCacheObject

@property (nonatomic,@dynamic,retain) NSNumber * playerGroup; 
@property (nonatomic,@dynamic,retain) NSNumber * playersPerMinute; 
@property (nonatomic,@dynamic,retain) GKGameCacheObject * game; 
+(id)entityName;
@end

