/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 1:55:18 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /usr/libexec/gamed
* classdump-dyld is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/

#import <gamed/GKExpiringCacheObject.h>

@class NSOrderedSet, NSString;

@interface GKListCacheObject : GKExpiringCacheObject

@property (nonatomic,@dynamic,retain) NSOrderedSet * entries; 
@property (nonatomic,@dynamic,retain) NSString * seed; 
@property (assign,nonatomic,@dynamic) BOOL detailsLoaded; 
+(id)relationshipKeyPathsForPrefetch;
+(Class)entryClass;
-(void)updateEntriesWithRepresentations:(id)arg1 entryForRepresentation:(/*^block*/ id)arg2 reuseEntriesByIndex:(BOOL)arg3 ;
-(void)updateSeed;
-(void)reorderEntry:(id)arg1 toIndex:(int)arg2 ;
-(void)removeEntriesMatchingPredicate:(id)arg1 ;
-(id)findEntry:(/*^block*/ id)arg1 ;
-(id)entryPassingTest:(/*^block*/ id)arg1 ;
-(id)entriesPassingTest:(/*^block*/ id)arg1 ;
-(id)internalRepresentation;
@end

