/*
* This header is generated by classdump-dyld 0.1
* on Thursday, November 28, 2013 at 4:18:57 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /usr/libexec/gamed
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/

#import <gamed/GKClientProxy.h>

@class GKClientProxy;

@interface GKUIServiceClientProxy : GKClientProxy {

	GKClientProxy* _host;

}

@property (nonatomic,retain) GKClientProxy * host;              //@synthesize host=_host - In the implementation block
+(id)existingUIServerProxy;
-(id)initWithHost:(id)arg1 ;
-(BOOL)deniedProductionEnvironment;
-(BOOL)isUIService;
-(void)terminateWithCompletionHandler:(/*^block*/ id)arg1 ;
-(id)serviceClient;
-(void)setHost:(id)arg1 ;
-(void)dealloc;
-(id)host;
@end

