/*
* This header is generated by classdump-dyld 0.1
* on Thursday, November 28, 2013 at 3:59:31 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/FaceTime.app/FaceTime
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/


@protocol ABPeoplePickerNavigationControllerPrivateMemberCellDelegate <ABPeoplePickerNavigationControllerDelegate>
@optional
-(BOOL)peoplePickerNavigationController:(id)arg1 shouldContinueAfterSelectingPerson:(void*)arg2 withLinkedPeople:(CFArrayRef)arg3 memberCell:(id)arg4;
-(BOOL)peoplePickerNavigationController:(id)arg1 shouldContinueAfterSelectingPerson:(void*)arg2 property:(int)arg3 identifier:(int)arg4 withMemberCell:(id)arg5;
@end

