/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 10:35:30 PM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/MobileNotes.app/MobileNotes
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/


@protocol NotesListAuthority
@required
-(void)queryForNewItem;
-(void)directionButtonClicked:(int)arg1 forNote:(id)arg2;
-(void)shouldEnableLeftButton:(BOOL*)arg1 rightButton:(BOOL*)arg2 forNote:(id)arg3;
-(id)currentList;
@end

