/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 1:38:47 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/MobileNotes.app/MobileNotes
* classdump-dyld is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/


@protocol NotePresenter <NSObject,NoteContentLayerDelegate>
@required
-(void)saveNote;
-(void)terminateFindSession;
-(void)highlightTermString:(id)arg1;
-(BOOL)noteNeedsSaving;
-(void)discardChanges;
-(BOOL)noteContainsNonWhitespaceCharacters;
-(void)updateBottomNavigationButtons;
-(BOOL)isAutosaving;
-(BOOL)willTransitionOut;
-(id)note;
-(BOOL)isEditing;
-(void)scrollToTop;
@end

