/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 10:35:31 PM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/MobileNotes.app/MobileNotes
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/


@protocol UIWebFindOnPageHighlighter <NSObject>
@property (nonatomic,readonly) NSString * searchText; 
@property (assign,nonatomic) <UIWebFindOnPageHighlighterDelegate> * delegate; 
@property (nonatomic,readonly) unsigned numberOfMatches; 
@property (nonatomic,readonly) unsigned highlightedMatchIndex; 
@required
-(void)setDelegate:(id)arg1;
-(id)delegate;
-(id)searchText;
-(void)setSearchText:(id)arg1 matchLimit:(unsigned)arg2;
-(void)setSelectionRect:(CGRect)arg1 textRects:(id)arg2 contentViews:(id)arg3 wobble:(BOOL)arg4;
-(void)highlightNextMatch;
-(void)highlightPreviousMatch;
-(unsigned)numberOfMatches;
-(unsigned)highlightedMatchIndex;
@end

