/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 10:34:43 PM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Compass.app/Compass
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/

typedef struct {
	double field1;
	double field2;
	double field3;
} SCD_Struct_Co0;

