/*
* This header is generated by strong_classdump 0.1
* on Wednesday, November 27, 2013 at 12:02:17 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/iPodOut.app/iPodOut
* strong_classdump is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/

#import <iPodOut/iPodOut-Structs.h>
#import <UIKit/UIControl.h>

@class UIImageView, UILabel, NSString;

@interface AlertView : UIControl {

	UIImageView* backgroundView;
	UILabel* titleLabel;
	UILabel* messageLabel;

}

@property (nonatomic,retain) NSString * title; 
@property (nonatomic,retain) NSString * message; 
@property (nonatomic,retain) UIImageView * backgroundView; 
@property (nonatomic,retain) UILabel * titleLabel; 
@property (nonatomic,retain) UILabel * messageLabel; 
-(void)setMessageLabel:(id)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(void)setTitle:(id)arg1 ;
-(id)title;
-(id)titleLabel;
-(void)setBackgroundView:(id)arg1 ;
-(id)backgroundView;
-(id)message;
-(id)messageLabel;
-(void)setMessage:(id)arg1 ;
-(void)setTitleLabel:(id)arg1 ;
-(void).cxx_destruct;
@end

