/*
* This header is generated by strong_classdump 0.1
* on Wednesday, November 27, 2013 at 12:02:17 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/iPodOut.app/iPodOut
* strong_classdump is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/

#import <iPodOut/iPodOut-Structs.h>
#import <Foundation/NSOperation.h>

@class MPMediaPlaylist, UIImage;

@interface GeniusMixArtworkLoader : NSOperation {

	id delegate;
	MPMediaPlaylist* geniusMix;
	UIImage* image;
	CGSize desiredSize;

}

@property (assign) id delegate; 
@property (retain) MPMediaPlaylist * geniusMix; 
@property (assign) CGSize desiredSize; 
@property (retain) UIImage * image; 
-(id)initWithGeniusMix:(id)arg1 desiredSize:(CGSize)arg2 ;
-(void)setGeniusMix:(id)arg1 ;
-(id)geniusMix;
-(void)setImage:(id)arg1 ;
-(void)setDelegate:(id)arg1 ;
-(id)delegate;
-(id)image;
-(void)main;
-(CGSize)desiredSize;
-(void)setDesiredSize:(CGSize)arg1 ;
-(void).cxx_destruct;
@end

