/*
* This header is generated by classdump-dyld 0.1
* on Thursday, November 28, 2013 at 4:01:13 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/iPodOut.app/iPodOut
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/


@protocol iPodOutViewController
@optional
-(void)writeCurrentPositionIntoNavigationPathComponent:(id)arg1;
-(int)restoreWithPathComponent:(id)arg1;
-(id)viewControllerForCurrentRow;
-(BOOL)autoRepeatDisabled;
-(id)initWithQuery:(id)arg1;

@required
-(void)downAction:(BOOL)arg1;
-(void)upAction:(BOOL)arg1;
-(void)selectAction:(BOOL)arg1;
-(void)leftAction:(BOOL)arg1;
-(void)rightAction:(BOOL)arg1;
-(void)clockwiseRotationAction:(BOOL)arg1;
-(void)counterClockwiseRotationAction:(BOOL)arg1;
@end

