/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 10:36:24 PM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/iPodOut.app/iPodOut
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/


#import <iPodOut/iPodOut-Structs.h>
@interface iPodOutStyle : NSObject
+(id)menuTextTitleFont;
+(id)menuIconFont;
+(UIEdgeInsets)safeArea;
+(unsigned)statusBarHeightDefault;
+(id)blockerTitleFont;
+(id)blockerSubtitleFont;
+(float)blockerTitleFontMinimumScale;
+(float)blockerSubtitleFontMinimumScale;
+(id)menuTextTwoLineSubtitleFont;
+(id)quickNavTextFont;
+(float)quickNavTextFontMinimumScale;
+(unsigned)statusBarHeightTall;
+(id)menuTextIconFont;
+(id)statusBarIconFont;
+(id)statusBarTextTitleFont;
+(id)statusBarTextTallTitleFont;
+(id)statusBarTextSubtitleFont;
+(id)menuTextRowNumberFont;
+(id)menuTextValueFont;
+(id)telephonyTimeFont;
+(id)telephonyCallerPhoneFont;
+(id)telephonyCallerNameFont;
+(float)nowPlayingTitleFontMinimumScale;
+(id)defaultFontName;
+(float)displayPixelDensity;
+(void)setDisplayPixelDensity:(float)arg1 ;
+(void)setSafeArea:(UIEdgeInsets)arg1 ;
+(id)menuTextUnselectedColor;
+(id)geniusMixArtistsFont;
+(id)geniusMixTitleFont;
+(float)geniusMixArtistsFontMinimumScale;
+(float)geniusMixTitleFontMinimumScale;
+(float)menuTextTitleFontMinimumScale;
+(id)alertTextTitleFont;
+(id)alertTextSubtitleFont;
+(id)nowPlayingTitleFont;
+(id)nowPlayingSubtitleFont;
+(float)nowPlayingSubtitleFontMinimumScale;
+(id)nowPlayingSmallFont;
+(id)nowPlayingRatingsIconFont;
+(id)nowPlayingOverlayFont;
+(float)telephonyCallerNameFontMinimumScale;
+(id)buttonIconFont;
+(void)setMinimumFontSize:(float)arg1 ;
+(float)minimumFontSize;
@end

