/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 10:36:24 PM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/iPodOut.app/iPodOut
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/

#import <iPodOut/iPodOut-Structs.h>
#import <UIKit/UIButton.h>

@interface LongPressButton : UIButton {

	CGRect backgroundRect;

}

@property (assign,nonatomic) CGRect backgroundRect; 
-(void)_touchHeld;
-(CGRect)backgroundRect;
-(void)setBackgroundRect:(CGRect)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)touchesCancelled:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesBegan:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesEnded:(id)arg1 withEvent:(id)arg2 ;
-(CGRect)backgroundRectForBounds:(CGRect)arg1 ;
@end

