/*
* This header is generated by strong_classdump 0.1
* on Wednesday, November 27, 2013 at 12:00:22 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /usr/lib/libacmobileshim.dylib
* strong_classdump is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/


@class NSDictionary;

@interface ACMBaseLocale : NSObject {

	NSDictionary* _localeStrings;
	ACMBaseLocale* _nextLocale;

}

@property (retain) ACMBaseLocale * nextLocale;              //@synthesize nextLocale=_nextLocale - In the implementation block
+(id)sharedInstance;
+(id)currentLanguageCode;
+(void)initResources;
+(id)localizedString:(id)arg1 ;
+(id)localeForIdentifier:(id)arg1 ;
+(id)localeForLanguage:(id)arg1 ;
-(void)dealloc;
-(id)objectForKey:(id)arg1 ;
-(void)setNextLocale:(id)arg1 ;
-(id)nextLocale;
@end

