/*
* This header is generated by strong_classdump 0.1
* on Wednesday, November 27, 2013 at 12:02:08 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Videos.app/Videos
* strong_classdump is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/

#import <Videos/Videos-Structs.h>
#import <UIKit/UICollectionViewCell.h>

@protocol VideosArtworkCellDelegate;
@class MPMediaItemImageRequest, UIButton, VideosUnplayedBadge, UIImageView, UILabel, , UIView, NSString;

@interface VideosArtworkCell : UICollectionViewCell {

	CGSize _artworkSize;
	MPMediaItemImageRequest* _imageRequest;
	UIButton* _deleteButton;
	VideosUnplayedBadge* _unplayedBadge;
	UIImageView* _cloudView;
	BOOL _needCloudImage;
	UIImageView* _glyph;
	UILabel* _titleLabel;
	BOOL _editing;
	BOOL _cloud;
	UIImageView* _artworkView;
	<VideosArtworkCellDelegate>* _delegate;
	unsigned _unplayedCount;
	unsigned _mediaType;
	UIView* _highlightView;
	CGSize _maxArtworkSize;

}

@property (nonatomic,readonly) UIImageView * artworkView;                                //@synthesize artworkView=_artworkView - In the implementation block
@property (assign,nonatomic) CGSize maxArtworkSize;                                      //@synthesize maxArtworkSize=_maxArtworkSize - In the implementation block
@property (assign,nonatomic,__weak) <VideosArtworkCellDelegate> * delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (assign,getter=isEditing,nonatomic) BOOL editing;                              //@synthesize editing=_editing - In the implementation block
@property (nonatomic,copy) NSString * title; 
@property (assign,nonatomic) unsigned unplayedCount;                                     //@synthesize unplayedCount=_unplayedCount - In the implementation block
@property (assign,nonatomic) BOOL cloud;                                                 //@synthesize cloud=_cloud - In the implementation block
@property (assign,nonatomic) unsigned mediaType;                                         //@synthesize mediaType=_mediaType - In the implementation block
@property (nonatomic,retain) UIView * highlightView;                                     //@synthesize highlightView=_highlightView - In the implementation block
-(void)loadImageWithRequest:(id)arg1 inCache:(id)arg2 ;
-(void)setUnplayedCount:(unsigned)arg1 ;
-(void)setMaxArtworkSize:(CGSize)arg1 ;
-(CGSize)maxArtworkSize;
-(BOOL)cloud;
-(void)setCloud:(BOOL)arg1 ;
-(void)_proportionallyAdjustArtworkFrame;
-(void)_addCloudView;
-(unsigned)unplayedCount;
-(id)highlightView;
-(void)setHighlightView:(id)arg1 ;
-(void)_deleteButtonPressed:(id)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)setDelegate:(id)arg1 ;
-(BOOL)pointInside:(CGPoint)arg1 withEvent:(id)arg2 ;
-(void)layoutSubviews;
-(void)setTitle:(id)arg1 ;
-(id)delegate;
-(id)title;
-(void)setHighlighted:(BOOL)arg1 ;
-(BOOL)isEditing;
-(void)setEditing:(BOOL)arg1 animated:(BOOL)arg2 ;
-(void)prepareForReuse;
-(void)setEditing:(BOOL)arg1 ;
-(void)applyLayoutAttributes:(id)arg1 ;
-(id)artworkView;
-(void)setMediaType:(unsigned)arg1 ;
-(void)setArtworkImage:(id)arg1 ;
-(unsigned)mediaType;
-(void).cxx_destruct;
@end

