/*
* This header is generated by classdump-dyld 0.1
* on Thursday, November 28, 2013 at 4:01:04 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Videos.app/Videos
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>

@class UIViewController;

@interface VideosTabBarProxyViewController : UIViewController {

	UIViewController* _proxy;

}

@property (nonatomic,readonly) UIViewController * proxy;              //@synthesize proxy=_proxy - In the implementation block
-(BOOL)videosAllowsCustomizationInTabBar;
-(BOOL)videosPresentedModallyInTabBar;
-(id)initWithProxy:(id)arg1 ;
-(id)restorationIdentifier;
-(id)tabBarItem;
-(id)proxy;
-(void).cxx_destruct;
@end

