/*
* This header is generated by strong_classdump 0.1
* on Wednesday, November 27, 2013 at 12:02:08 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Videos.app/Videos
* strong_classdump is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/

#import <UIKit/UIView.h>

@protocol VideosDetailHeaderViewDelegate;
@class , UIButton, UILabel, UIView, NSArray, SKUIItemOfferButton, UISegmentedControl;

@interface VideosDetailHeaderView : UIView {

	<VideosDetailHeaderViewDelegate>* _delegate;
	UIButton* _posterView;
	UILabel* _titleLabel;
	UILabel* _subtitleLabel;
	UIView* _iconsContainer;
	NSArray* _iconViews;
	UILabel* _expirationLabel;
	UIButton* _playButton;
	SKUIItemOfferButton* _cloudButton;
	UIView* _segmentedControlContainer;
	UISegmentedControl* _segmentedControl;

}

@property (assign,nonatomic,__weak) <VideosDetailHeaderViewDelegate> * delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) UIButton * posterView;                                           //@synthesize posterView=_posterView - In the implementation block
@property (nonatomic,retain) UILabel * titleLabel;                                            //@synthesize titleLabel=_titleLabel - In the implementation block
@property (nonatomic,retain) UILabel * subtitleLabel;                                         //@synthesize subtitleLabel=_subtitleLabel - In the implementation block
@property (nonatomic,retain) UIView * iconsContainer;                                         //@synthesize iconsContainer=_iconsContainer - In the implementation block
@property (nonatomic,retain) NSArray * iconViews;                                             //@synthesize iconViews=_iconViews - In the implementation block
@property (nonatomic,retain) UILabel * expirationLabel;                                       //@synthesize expirationLabel=_expirationLabel - In the implementation block
@property (nonatomic,retain) UIButton * playButton;                                           //@synthesize playButton=_playButton - In the implementation block
@property (nonatomic,retain) SKUIItemOfferButton * cloudButton;                               //@synthesize cloudButton=_cloudButton - In the implementation block
@property (nonatomic,retain) UIView * segmentedControlContainer;                              //@synthesize segmentedControlContainer=_segmentedControlContainer - In the implementation block
@property (nonatomic,retain) UISegmentedControl * segmentedControl;                           //@synthesize segmentedControl=_segmentedControl - In the implementation block
-(id)expirationLabel;
-(id)iconViews;
-(void)setPosterView:(id)arg1 ;
-(void)setIconsContainer:(id)arg1 ;
-(void)setIconViews:(id)arg1 ;
-(void)setExpirationLabel:(id)arg1 ;
-(id)cloudButton;
-(void)setCloudButton:(id)arg1 ;
-(void)setSegmentedControlContainer:(id)arg1 ;
-(id)segmentedControlContainer;
-(id)posterView;
-(id)iconsContainer;
-(void)setSubtitleLabel:(id)arg1 ;
-(void)setSegmentedControl:(id)arg1 ;
-(id)playButton;
-(void)setPlayButton:(id)arg1 ;
-(void)setDelegate:(id)arg1 ;
-(void)layoutSubviews;
-(id)delegate;
-(id)titleLabel;
-(id)subtitleLabel;
-(id)segmentedControl;
-(void)setTitleLabel:(id)arg1 ;
-(void).cxx_destruct;
@end

