/*
* This header is generated by strong_classdump 0.1
* on Wednesday, November 27, 2013 at 12:01:49 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Preferences.app/Preferences
* strong_classdump is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/


@protocol BiometricKitDelegate <NSObject>
@optional
-(void)statusMessage:(unsigned)arg1;
-(void)enrollResult:(id)arg1;
-(void)matchResult:(id)arg1;
-(void)matchResult:(id)arg1 withDetails:(id)arg2;
-(void)enrollProgress:(id)arg1;
-(void)homeButtonPressed;
@end

