/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 1:39:14 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Preferences.app/Preferences
* classdump-dyld is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/


@protocol OS_dispatch_semaphore;
@class NSObject;

@interface FindMyiPhoneController : NSObject {

	NSObject<OS_dispatch_semaphore>* _stateChangeSem;

}
+(id)shared;
-(void)locatorStateDidChange:(id)arg1 ;
-(id)preferredFindMyiPhoneAccount;
-(void)disablePhoneLocatorWithMessageString:(id)arg1 buttonTitle:(id)arg2 completion:(/*^block*/ id)arg3 ;
-(BOOL)isFindMyiPhoneProvisioned;
-(BOOL)isFindMyiPhoneEnabled;
-(void)enablePhoneLocatorWithCompletion:(/*^block*/ id)arg1 ;
-(void)dealloc;
-(id)init;
@end

