/*
* This header is generated by classdump-dyld 0.1
* on Thursday, November 28, 2013 at 4:00:44 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Preferences.app/Preferences
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIView.h>
#import <Preferences/PSHeaderFooterView.h>

@class UIImageView, UILabel;

@interface LocationIndicatorExplanationView : UIView <PSHeaderFooterView> {

	UIImageView* _activeIcon;
	UILabel* _activeLabel;
	UIImageView* _recentIcon;
	UILabel* _recentLabel;
	UIImageView* _geofenceIcon;
	UILabel* _geofenceLabel;

}
-(void)layoutForWidth:(float)arg1 inTableView:(id)arg2 ;
-(id)initWithSpecifier:(id)arg1 ;
-(float)preferredHeightForWidth:(float)arg1 ;
-(void)dealloc;
-(void)layoutSubviews;
-(float)preferredHeightForWidth:(float)arg1 inTableView:(id)arg2 ;
@end

