/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 10:35:55 PM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Preferences.app/Preferences
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/

#import <Preferences/Preferences-Structs.h>
#import <Preferences/PSEditingPane.h>

@class TKTonePicker;

@interface RingtonePane : PSEditingPane {

	TKTonePicker* _picker;

}
+(id)tonePickerWithFrame:(CGRect)arg1 ;
-(void)stopPlaying;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)layoutSubviews;
-(void)setPreferenceSpecifier:(id)arg1 ;
-(void)setPreferenceValue:(id)arg1 ;
-(void)viewDidBecomeVisible;
-(id)preferenceValue;
-(void)ringtonePicker:(id)arg1 selectedRingtoneWithIdentifier:(id)arg2 ;
@end

