/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 10:34:53 PM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Game Center~iphone.app/Game Center~iphone
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/

#import <Game Center~iphone/Game Center~iphone-Structs.h>
#import <GameCenterUI/GKCollectionViewCell.h>

@class GKGame, GKPlayer, GKLabel, GKHairlineView;

@interface GKFriendPlaySuggestionCell : GKCollectionViewCell {

	GKGame* _game;
	GKPlayer* _friend;
	GKLabel* _titleLabel;
	GKHairlineView* _underlineView;

}

@property (nonatomic,retain) GKGame * game;                               //@synthesize game=_game - In the implementation block
@property (nonatomic,retain) GKPlayer * friend;                           //@synthesize friend=_friend - In the implementation block
@property (nonatomic,retain) GKLabel * titleLabel;                        //@synthesize titleLabel=_titleLabel - In the implementation block
@property (nonatomic,retain) GKHairlineView * underlineView;              //@synthesize underlineView=_underlineView - In the implementation block
-(id)game;
-(void)setGame:(id)arg1 ;
-(id)underlineView;
-(void)setUnderlineView:(id)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(id)titleLabel;
-(void)setTitleLabel:(id)arg1 ;
-(id)friend;
-(void)setFriend:(id)arg1 ;
@end

