/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 10:34:54 PM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Game Center~iphone.app/Game Center~iphone
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/

#import <Game Center~iphone/Game Center~iphone-Structs.h>
#import <Game Center~iphone/GKPlayerProfileHeaderView.h>

@class GKHorizontalBubbleControlsView, GKTextBubbleControl;

@interface GKFriendRequestProfileHeaderView : GKPlayerProfileHeaderView {

	GKHorizontalBubbleControlsView* _bubblesContainerView;
	GKTextBubbleControl* _acceptBubble;
	GKTextBubbleControl* _ignoreBubble;

}

@property (nonatomic,retain) GKHorizontalBubbleControlsView * bubblesContainerView;              //@synthesize bubblesContainerView=_bubblesContainerView - In the implementation block
@property (nonatomic,retain) GKTextBubbleControl * acceptBubble;                                 //@synthesize acceptBubble=_acceptBubble - In the implementation block
@property (nonatomic,retain) GKTextBubbleControl * ignoreBubble;                                 //@synthesize ignoreBubble=_ignoreBubble - In the implementation block
-(void)pushRightBubble;
-(void)pushLeftBubble;
-(id)acceptBubble;
-(id)ignoreBubble;
-(id)bubblesContainerView;
-(void)updatePlayerStatus;
-(void)setBubblesContainerView:(id)arg1 ;
-(void)setAcceptBubble:(id)arg1 ;
-(void)setIgnoreBubble:(id)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(CGSize)intrinsicContentSize;
@end

