/*
* This header is generated by classdump-dyld 0.1
* on Thursday, November 28, 2013 at 3:59:36 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Game Center~iphone.app/Game Center~iphone
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/

#import <GameCenterUI/GKBasicCollectionViewDataSource.h>

@interface GKGamesRecommendationsDataSource : GKBasicCollectionViewDataSource {

	int _maxItemCount;

}

@property (assign,nonatomic) int maxItemCount;              //@synthesize maxItemCount=_maxItemCount - In the implementation block
-(void)storeFrontChanged:(id)arg1 ;
-(void)loadGamesWithHandler:(/*^block*/ id)arg1 ;
-(void)refreshContentsForDataType:(unsigned)arg1 userInfo:(id)arg2 updateNotifier:(id)arg3 ;
-(void)configureCollectionView:(id)arg1 ;
-(void)removeItemAtIndexPath:(id)arg1 ;
-(void)setMaxItemCount:(int)arg1 ;
-(int)maxItemCount;
-(SEL)showAllAction;
-(void)dealloc;
-(id)init;
-(id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2 ;
-(id)sectionTitle;
@end

