/*
* This header is generated by strong_classdump 0.1
* on Wednesday, November 27, 2013 at 12:00:45 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Game Center~iphone.app/Game Center~iphone
* strong_classdump is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/

#import <GameCenterUI/GKBasicCollectionViewDataSource.h>

@class GKPlayer, NSString;

@interface GKGamesCompareBasicDataSource : GKBasicCollectionViewDataSource {

	GKPlayer* _player;
	NSString* _localPlayerSeed;
	NSString* _playerSeed;

}

@property (nonatomic,retain) GKPlayer * player;                       //@synthesize player=_player - In the implementation block
@property (nonatomic,retain) NSString * localPlayerSeed;              //@synthesize localPlayerSeed=_localPlayerSeed - In the implementation block
@property (nonatomic,retain) NSString * playerSeed;                   //@synthesize playerSeed=_playerSeed - In the implementation block
@property (nonatomic,readonly) NSString * overallSeed; 
+(id)gamesCompareBasicDataSourceWithPlayer:(id)arg1 ;
-(id)seedForLocalPlayerSeed:(id)arg1 playerSeed:(id)arg2 ;
-(id)overallSeed;
-(BOOL)listNeedsUpdateForLocalPlayerSeed:(id)arg1 playerSeed:(id)arg2 ;
-(void)setLocalPlayerSeed:(id)arg1 ;
-(void)setPlayerSeed:(id)arg1 ;
-(id)localPlayerSeed;
-(id)playerSeed;
-(void)refreshContentsForDataType:(unsigned)arg1 userInfo:(id)arg2 updateNotifier:(id)arg3 ;
-(id)initWithPlayer:(id)arg1 ;
-(void)dealloc;
-(id)player;
-(void)setPlayer:(id)arg1 ;
@end

