/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 10:34:53 PM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Game Center~iphone.app/Game Center~iphone
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/

#import <Game Center~iphone/Game Center~iphone-Structs.h>
#import <GameCenterUI/GKSplittingDataSource.h>

@class GKPlayer, NSMutableIndexSet;

@interface GKGamesCompareOverviewDataSource : GKSplittingDataSource {

	GKPlayer* _player;
	NSMutableIndexSet* _loadedPages;

}

@property (nonatomic,retain) GKPlayer * player;                            //@synthesize player=_player - In the implementation block
@property (nonatomic,retain) NSMutableIndexSet * loadedPages;              //@synthesize loadedPages=_loadedPages - In the implementation block
+(id)gamesCompareOverviewDataSourceWithPlayer:(id)arg1 ;
-(unsigned)pageForItemIndex:(unsigned)arg1 ;
-(id)loadedPages;
-(void)setLoadedPages:(id)arg1 ;
-(void)configureCell:(id)arg1 withItem:(id)arg2 ;
-(void)loadDetailsForItemsInPages:(NSRange)arg1 handler:(/*^block*/ id)arg2 ;
-(NSRange)itemRangeForPageRange:(NSRange)arg1 ;
-(void)refreshContentsForDataType:(unsigned)arg1 userInfo:(id)arg2 updateNotifier:(id)arg3 ;
-(void)configureDataSource;
-(void)configureCollectionView:(id)arg1 ;
-(void)collectionViewWillBecomeActive:(id)arg1 ;
-(id)initWithPlayer:(id)arg1 ;
-(void)dealloc;
-(id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2 ;
-(id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3 ;
-(unsigned)indexForIndexPath:(id)arg1 ;
-(unsigned)pageSize;
-(id)player;
-(void)setPlayer:(id)arg1 ;
@end

