/*
* This header is generated by strong_classdump 0.1
* on Wednesday, November 27, 2013 at 12:00:31 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/AppStore.app/AppStore
* strong_classdump is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/

#import <StoreKitUI/SKUIItemTableViewCell.h>

@class ASPurchasedCellLayout;

@interface ASPurchasedTableViewCell : SKUIItemTableViewCell {

	ASPurchasedCellLayout* _layout;

}

@property (nonatomic,readonly) ASPurchasedCellLayout * layout;              //@synthesize layout=_layout - In the implementation block
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2 ;
-(id)layout;
-(void)configureForItem:(id)arg1 rowIndex:(int)arg2 ;
-(void).cxx_destruct;
@end

