/*
* This header is generated by classdump-dyld 0.1
* on Thursday, November 28, 2013 at 3:59:22 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/AppStore.app/AppStore
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/

#import <AppStore/AppStore-Structs.h>
#import <UIKit/UITableView.h>

@class SKUIClientContext, _UIContentUnavailableView;

@interface ASUpdatesTableView : UITableView {

	SKUIClientContext* _clientContext;
	float _purchasedRowHeight;
	BOOL _showsNoUpdates;
	_UIContentUnavailableView* _noUpdatesView;

}

@property (nonatomic,retain) SKUIClientContext * clientContext;              //@synthesize clientContext=_clientContext - In the implementation block
@property (assign,nonatomic) float purchasedRowHeight;                       //@synthesize purchasedRowHeight=_purchasedRowHeight - In the implementation block
@property (assign,nonatomic) BOOL showsNoUpdates;                            //@synthesize showsNoUpdates=_showsNoUpdates - In the implementation block
-(void)setShowsNoUpdates:(BOOL)arg1 ;
-(void)setPurchasedRowHeight:(float)arg1 ;
-(void)_layoutNoUpdatesView;
-(float)purchasedRowHeight;
-(BOOL)showsNoUpdates;
-(void)setFrame:(CGRect)arg1 ;
-(id)clientContext;
-(void).cxx_destruct;
-(void)setClientContext:(id)arg1 ;
@end

