/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 10:34:42 PM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Calculator.app/Calculator
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/


@interface CalculateUtilities : NSObject
+(id)errorStringForResult:(id)arg1 ;
+(id)stringMathResultWithOperator:(unsigned)arg1 ;
+(id)stringMathResultWithExpression:(id)arg1 ;
+(id)stringRoundedToPrecision:(unsigned)arg1 withString:(id)arg2 roundingMode:(unsigned)arg3 ;
@end

