/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 1:37:59 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Calculator.app/Calculator
* classdump-dyld is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/

#import <Calculator/Calculator-Structs.h>
#import <UIKit/UIViewController.h>
#import <Calculator/ComputationViewDelegate.h>
#import <Calculator/KeypadDelegate.h>

@class ComputationView, KeypadView, SelectionView, Computation;

@interface CalculatorViewController : UIViewController <ComputationViewDelegate, KeypadDelegate> {

	ComputationView* _computationView;
	KeypadView* _keypadView;
	SelectionView* _selectionView;
	unsigned _editState;
	Computation* _computation;

}
-(void)_refreshDisplay;
-(void)_setSelectionRange:(NSRange)arg1 ;
-(void)_selectCharacterAtIndex:(unsigned)arg1 ;
-(void)upperTextViewDidSelectCharacterAtIndex:(unsigned)arg1 ;
-(void)lowerTextViewDidSelectCharacterAtIndex:(unsigned)arg1 ;
-(void)computationViewDidDeselect;
-(void)keypadKeyTapped:(int)arg1 ;
-(void)dealloc;
-(unsigned)supportedInterfaceOrientations;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(void)viewDidLoad;
-(void)loadView;
@end

