/*
* This header is generated by strong_classdump 0.1
* on Wednesday, November 27, 2013 at 12:42:42 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /usr/libexec/backboardd
* strong_classdump is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/


#import <backboardd/backboardd-Structs.h>
@interface BKAccessibility : NSObject
+(BOOL)_invertColorsEnabled;
+(/*function pointer*/ void*)_accessibilityEventTapCallback;
+(/*function pointer*/ void*)_accessibilityHIDEventTapCallback;
+(BOOL)_objectWithinProximity;
+(id)_eventRoutingClientConnectionManager;
+(void)_accessibilitySetEventTapCallback:(/*function pointer*/ void*)arg1 ;
+(void)_accessibilitySetHIDEventTapCallback:(/*function pointer*/ void*)arg1 ;
+(void)_setInvertColorsEnabled:(BOOL)arg1 ;
+(CGPoint)_displayConvertFromCAScreen:(CGPoint)arg1 contextId:(unsigned)arg2 ;
+(CGPoint)_displayConvertToCAScreen:(CGPoint)arg1 ;
+(void)_accessibilityProcessExternHIDEvent:(IOHIDEventRef)arg1 ;
+(BOOL)_isDisplayBacklightOff;
@end

