/*
* This header is generated by strong_classdump 0.1
* on Wednesday, November 27, 2013 at 12:42:42 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /usr/libexec/backboardd
* strong_classdump is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/


@protocol OS_dispatch_source;
@class NSObject, NSString;

@interface BKDisplayBrightnessUpdateTransaction : NSObject {

	/*^block*/ id _invalidationHandler;
	unsigned _port;
	NSObject<OS_dispatch_source>* _portSource;
	NSObject<OS_dispatch_source>* _timerSource;
	NSString* _identifier;
	BOOL _updateTransactionActive;
	double _expirationTime;

}
+(void)beginImplicitDisplayBrightnessUpdateTransaction;
-(id)initWithClientPort:(unsigned)arg1 identifier:(id)arg2 invalidationHandler:(/*^block*/ id)arg3 ;
-(void)_invalidateAndReleaseSource:(id)arg1 ;
-(void)_updateExpirationTimeWithIntervalSinceNow:(double)arg1 ;
-(void)_setHandlersForAndResumeSource:(id)arg1 ;
-(void)_beginUpdateTransaction;
-(id)initWithClientPort:(unsigned)arg1 identifier:(id)arg2 invalidationHandler:(/*^block*/ id)arg3 delay:(double)arg4 ;
-(id)initWithDelay:(double)arg1 identifier:(id)arg2 invalidationHandler:(/*^block*/ id)arg3 ;
-(void)_setTimerWithTimeIntervalSinceNow:(double)arg1 ;
-(void)_sourceFired:(id)arg1 ;
-(void)_endUpdateTransaction;
-(void)dealloc;
-(id)initWithIdentifier:(id)arg1 ;
@end

