/*
* This header is generated by classdump-dyld 0.1
* on Thursday, November 28, 2013 at 4:18:51 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /usr/libexec/backboardd
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/


#import <backboardd/backboardd-Structs.h>
@interface BKHIDSystemInterface : NSObject
+(void)startServer;
+(id)sharedInstance;
-(void)setSystemProperty:(id)arg1 forKey:(id)arg2 ;
-(id)copySystemClientPropertyForKey:(id)arg1 ;
-(void)setSystemClientProperty:(id)arg1 forKey:(id)arg2 ;
-(void)registerCallback:(/*function pointer*/ void*)arg1 forProperty:(id)arg2 ;
-(id)systemPropertyForKey:(id)arg1 ;
-(void)injectHIDEvent:(IOHIDEventRef)arg1 ;
-(void)injectGSEvent:(GSEventRef)arg1 ;
-(BOOL)isOpen;
-(BOOL)ping;
-(void)open;
@end

