/*
* This header is generated by classdump-dyld 0.1
* on Thursday, November 28, 2013 at 3:59:34 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/FieldTest.app/FieldTest
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/


@class NSString;

@interface FieldTestModelNode : NSObject {

	NSString* _name;

}
+(id)makeTreeFromObject:(id)arg1 withPathDictionary:(id)arg2 ;
-(void)dealloc;
-(id)value;
-(id)childNodes;
-(id)displayName;
@end

