/*
* This header is generated by strong_classdump 0.1
* on Wednesday, November 27, 2013 at 12:00:44 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/FieldTest.app/FieldTest
* strong_classdump is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/

#import <FieldTest/LogGenerator.h>

@interface GSMLogGenerator : LogGenerator
+(id)processObject:(id)arg1 ;
+(id)generator;
-(id)getStartCommand;
-(id)generateLogUsingState:(id)arg1 ;
-(void)updateState:(id)arg1 withData:(id)arg2 ;
-(id)getSaveContentsFromState:(id)arg1 ;
-(id)canCollapse:(id)arg1 ;
@end

