/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 10:52:10 PM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /usr/libexec/locationd
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/

#import <locationd/locationd-Structs.h>
#import <CoreMotion/CLIntersiloService.h>
#import <locationd/CLLocationHarvesterProtocol.h>

@interface CLLocationHarvesterAdapter : CLIntersiloService <CLLocationHarvesterProtocol> {

	CLLocationHarvester* _harvester;

}

@property (assign,nonatomic) CLLocationHarvester* harvester;              //@synthesize harvester=_harvester - In the implementation block
+(id)getSilo;
-(void)setHarvestingEnabled:(BOOL)arg1 ;
-(CLLocationHarvester*)harvester;
-(void)setHarvester:(CLLocationHarvester*)arg1 ;
-(void)setPrivateMode:(BOOL)arg1 ;
-(id)initInSilo:(id)arg1 ;
-(void)heartAttack;
-(void)beginService;
-(void)endService;
-(void)shutdown;
@end

