/*
* This header is generated by classdump-dyld 0.1
* on Thursday, November 28, 2013 at 4:19:00 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /usr/libexec/locationd
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/


#import <locationd/locationd-Structs.h>
@class CLSilo, NSMutableArray, NSString;

@interface CLMescalSigner : NSObject {

	CLSilo* _silo;
	NSMutableArray* _worklist;
	BOOL _keyExchangeStarted;
	BOOL _keyExchangeComplete;
	FairPlayHWInfo_ _hardwareInfo;
	FPSAPContextOpaque_Ref _session;
	NSString* _mescalVersion;
	NSString* _mescalCertURL;
	NSString* _mescalExchangeURL;
	double _replaceAfter;

}

@property (nonatomic,readonly) double replaceAfter;              //@synthesize replaceAfter=_replaceAfter - In the implementation block
-(void)_doSigningWhenReady;
-(void)_initializeMescalWithCompletion:(/*^block*/ id)arg1 ;
-(void)_churnMescalExchangeData:(id)arg1 withCompletion:(/*^block*/ id)arg2 ;
-(void)signData:(id)arg1 withCompletion:(/*^block*/ id)arg2 ;
-(double)replaceAfter;
-(id)initInSilo:(id)arg1 ;
-(void)dealloc;
@end

