/*
* This header is generated by strong_classdump 0.1
* on Wednesday, November 27, 2013 at 12:42:53 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /usr/libexec/locationd
* strong_classdump is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/

#import <locationd/locationd-Structs.h>
#import <CoreMotion/CLIntersiloService.h>
#import <CoreMotion/CLNotifierServiceProtocol.h>

@interface CLNotifierServiceAdapter : CLIntersiloService <CLNotifierServiceProtocol> {

	map<unsigned long, int, std::__1::less<unsigned long>, std::__1::allocator<std::__1::pair<const unsigned long, int> > >* _clients;
	CLNotifierBase* _notifier;

}

@property (nonatomic,readonly) CLNotifierBase* notifier;              //@synthesize notifier=_notifier - In the implementation block
-(void)register:(R)arg1 forNotification:(id)arg2 registrationInfo:(int)arg3 :(id)arg4 ;
-(id)initInSilo:(id)arg1 ;
-(void)setAdaptedNotifier:(CLNotifierBase*)arg1 ;
-(void)unregister:(R)arg1 forNotification:(id)arg2 :(int)arg3 ;
-(void)forget:(R)arg1 :(id)arg2 ;
-(CLNotifierBase*)notifier;
-(int)notifierClientNumForCoparty:(id)arg1 ;
-(id)debugDescription;
-(void)invalidate;
-(id).cxx_construct;
-(void).cxx_destruct;
@end

