/*
* This header is generated by strong_classdump 0.1
* on Wednesday, November 27, 2013 at 12:42:52 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /usr/libexec/locationd
* strong_classdump is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/

#import <locationd/locationd-Structs.h>
#import <CoreMotion/CLNotifierServiceAdapter.h>
#import <locationd/CLTilesManagerProtocol.h>

@interface CLTilesManagerAdapter : CLNotifierServiceAdapter <CLTilesManagerProtocol>
+(id)getSilo;
-(void)requestTileDownloadByType:(int)arg1 lat:(double)arg2 lon:(double)arg3 seckey:(unsigned long long)arg4 details:(CLTileFileDownloadDetails)arg5 ;
-(CLTilesManager*)tilesManager;
-(id)initInSilo:(id)arg1 ;
-(void)heartAttack;
-(void)beginService;
-(void)endService;
@end

