/*
* This header is generated by strong_classdump 0.1
* on Wednesday, November 27, 2013 at 12:42:59 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /usr/sbin/BTLEServer
* strong_classdump is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/

#import <BTLEServer/BTLEServer-Structs.h>
#import <BTLEServer/ANCCallAlert.h>

@interface ANCIncomingCallAlert : ANCCallAlert
-(id)initWithCall:(CTCallRef)arg1 addressBook:(void*)arg2 ;
-(BOOL)isEqualToAlert:(id)arg1 ;
-(BOOL)isImportant;
-(id)message;
@end

