/*
* This header is generated by strong_classdump 0.1
* on Wednesday, November 27, 2013 at 12:42:58 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /usr/sbin/BTLEServer
* strong_classdump is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/


@protocol OS_xpc_object;
@class NSObject;

@interface BTLEXpcServer : NSObject {

	NSObject<OS_xpc_object>* _server;

}
+(id)instance;
-(void)handleConnection:(id)arg1 ;
-(id)init;
-(void)handleEvent:(id)arg1 ;
-(void)start;
@end

