/*
* This header is generated by classdump-dyld 0.1
* on Thursday, November 28, 2013 at 4:00:54 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Reminders.app/Reminders
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/


@protocol RemindersSearchViewControllerDelegate
@required
-(void)searchController:(id)arg1 willBecomeActive:(BOOL)arg2;
-(void)searchController:(id)arg1 didSelectReminder:(id)arg2 forSearchTerm:(id)arg3;
@end

