/*
* This header is generated by strong_classdump 0.1
* on Wednesday, November 27, 2013 at 12:00:41 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/FaceTime.app/FaceTime
* strong_classdump is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/


@interface PHFavoritesManager : NSObject
+(id)currentFavorites;
+(id)allFavorites;
+(BOOL)dialFavoriteEntry:(id)arg1 ;
+(void)_abFavoritesEntryChangedNotification:(id)arg1 ;
+(void)_abfavoritesListChangedNotification:(id)arg1 ;
+(void)_ftcServiceAvailabilityDidChangeNotification:(id)arg1 ;
+(void)_phoneApplicationAddressBookChangedNotification:(id)arg1 ;
+(void)_clearCachedFavorites;
+(id)predicateForTelephonyEntries;
+(id)predicateForFaceTimeAudioEntries;
+(id)predicateForFaceTimeEntries;
+(id)_favoritesWithPredicate:(id)arg1 ;
+(id)starkFavorites;
+(void)recacheIdentitiesSoon;
+(void)save;
+(void)initialize;
@end

