/*
* This header is generated by classdump-dyld 0.1
* on Thursday, November 28, 2013 at 4:01:04 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Videos.app/Videos
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/

#import <MediaPlayer/MPAVController.h>

@class NSTimer;

@interface VideosAVController : MPAVController {

	BOOL _scheduledTrackExpirationCallback;
	NSTimer* _rentalExpiryTimer;

}
-(void)_networkTypeDidChange:(id)arg1 ;
-(void)_isCellularDataRestrictedDidChange:(id)arg1 ;
-(void)_availableMediaLibrariesDidChange:(id)arg1 ;
-(void)_scheduleExpirationTimerIfNecessary;
-(void)_setRentalIsPlaying:(BOOL)arg1 forItem:(id)arg2 ;
-(void)_movieExpirationCheckCallback;
-(BOOL)showPlaybackStateOverlaysOnTVOut;
-(BOOL)currentItemIsRental;
-(void)_itemReadyToPlay:(id)arg1 ;
-(void)airPlayVideoEnded;
-(void)_itemWillChange:(id)arg1 ;
-(void)_downloadCancelledNotification:(id)arg1 ;
-(void)dealloc;
-(id)init;
-(void)_endPlaybackIfNeededForCurrentNetwork;
-(void).cxx_destruct;
@end

