/*
* This header is generated by classdump-dyld 0.1
* on Thursday, November 28, 2013 at 4:00:12 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/

#import <MobileMail/MobileMail-Structs.h>
#import <UIKit/UIView.h>

@interface MessageFoldShadowView : UIView {

	CGGradientRef _gradient;
	float _visibleLeftMargin;

}
-(id)initWithFrame:(CGRect)arg1 topWhite:(float)arg2 alpha:(float)arg3 midWhite:(float)arg4 alpha:(float)arg5 bottomWhite:(float)arg6 alpha:(float)arg7 ;
-(void)setVisibleLeftMargin:(float)arg1 ;
-(void)dealloc;
-(void)drawRect:(CGRect)arg1 ;
-(BOOL)isOpaque;
@end

