/*
* This header is generated by classdump-dyld 0.1
* on Thursday, November 28, 2013 at 4:18:50 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /usr/libexec/atc
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/


@protocol ATStoreLinkDelegate <NSObject>
@required
-(void)resetTimeout;
-(void)cancelAsset:(id)arg1;
-(BOOL)downloadAsset:(id)arg1 withProgress:(/*^block*/ id)arg2 withCompletion:(/*^block*/ id)arg3;
-(void)asset:(id)arg1 wasInstalled:(BOOL)arg2 withError:(id)arg3;
-(void)storeLink:(id)arg1 encounteredError:(id)arg2;
-(dispatch_queue_sRef)workQueue;
@end

