/*
* This header is generated by classdump-dyld 0.1
* on Thursday, November 28, 2013 at 4:00:40 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Nike.app/Nike
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/

#import <Nike/Nike-Structs.h>
#import <UIKit/UILabel.h>

@interface STTableHeaderView : UILabel {

	BOOL _wantsSeparator;

}

@property (assign,nonatomic) BOOL wantsSeparator;              //@synthesize wantsSeparator=_wantsSeparator - In the implementation block
-(BOOL)wantsSeparator;
-(void)setWantsSeparator:(BOOL)arg1 ;
-(void)drawRect:(CGRect)arg1 ;
@end

