/*
* This header is generated by classdump-dyld 0.1
* on Thursday, November 28, 2013 at 4:00:58 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Setup.app/Setup
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/

#import <Setup/BuddyAppleIDSignInPage.h>
#import <Setup/BuddyController.h>
#import <UIKit/UIAlertViewDelegate.h>

@class BuddyAppleIDController;

@interface BuddyRestoreSignInPage : BuddyAppleIDSignInPage <BuddyController, UIAlertViewDelegate> {

	BuddyAppleIDController* _appleIDController;

}

@property (assign,nonatomic,@dynamic) <BuddyControllerDelegate> * delegate; 
-(BOOL)shouldAllowStartOver;
-(id)navControllerForCreateAppleIDPages:(id)arg1 ;
-(void)appleIDControllerFinished:(id)arg1 success:(BOOL)arg2 ;
-(void)appleIDAuthFailed:(id)arg1 ;
-(id)appleIDController;
-(id)newHeader;
-(id)newFooter;
-(id)signInTitle;
-(void)dealloc;
-(id)init;
-(void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2 ;
@end

