/*
* This header is generated by classdump-dyld 0.1
* on Thursday, November 28, 2013 at 3:59:09 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/


@protocol ACMTicketVerificationRequest <NSObject>
@property (retain) NSString * userName; 
@property (retain) NSString * realm; 
@property (retain) NSString * token; 
@property (retain) NSNumber * appID; 
@property (retain) NSString * appIDKey; 
@property (retain) NSNumber * serverResponseTimeout; 
@property (retain) id userInfo; 
@required
-(id)userName;
-(id)realm;
-(id)userInfo;
-(void)setUserInfo:(id)arg1;
-(void)setAppID:(id)arg1;
-(void)setRealm:(id)arg1;
-(void)setUserName:(id)arg1;
-(id)token;
-(void)setToken:(id)arg1;
-(void)setAppIDKey:(id)arg1;
-(id)appID;
-(id)appIDKey;
-(id)serverResponseTimeout;
-(void)setServerResponseTimeout:(id)arg1;
@end

