/*
* This header is generated by classdump-dyld 0.1
* on Thursday, November 28, 2013 at 3:59:04 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /usr/lib/libAWDProtobufPower.dylib
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/

#import <libAWDProtobufPower.dylib/libAWDProtobufPower.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>

@class NSString;

@interface AWDPerProcessCPULoad : PBCodable {

	unsigned _duration;
	NSString* _procName;
	SCD_Struct_AW2 _has;

}

@property (nonatomic,readonly) BOOL hasProcName; 
@property (nonatomic,retain) NSString * procName;              //@synthesize procName=_procName - In the implementation block
@property (assign,nonatomic) BOOL hasDuration; 
@property (assign,nonatomic) unsigned duration;                //@synthesize duration=_duration - In the implementation block
-(void)dealloc;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned)hash;
-(id)description;
-(unsigned)duration;
-(void)setDuration:(unsigned)arg1 ;
-(id)dictionaryRepresentation;
-(BOOL)readFrom:(id)arg1 ;
-(BOOL)hasDuration;
-(void)setHasDuration:(BOOL)arg1 ;
-(id)procName;
-(void)setProcName:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(BOOL)hasProcName;
@end

