#import <libsystem_network.dylib/OS_tcp_connection.h>
#import <libsystem_network.dylib/OS_tcp_connection_host.h>
#import <libsystem_network.dylib/OS_tcp_connection_destination.h>
#import <libsystem_network.dylib/OS_tcp_connection_bonjour.h>
#import <libsystem_network.dylib/OS_tcp_connection_read_channel.h>
#import <libsystem_network.dylib/OS_tcp_connection_write_channel.h>
#import <libsystem_network.dylib/OS_tcp_connection_watcher.h>
#import <libsystem_network.dylib/OS_tcp_connection_details.h>
#import <libsystem_network.dylib/OS_tcp_listener.h>
#import <libsystem_network.dylib/OS_tcp_connection_msg_in.h>
#import <libsystem_network.dylib/OS_tcp_connection_msg_out.h>
