/*
* This header is generated by classdump-dyld 0.1
* on Thursday, November 28, 2013 at 4:19:05 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /usr/libexec/mobileassetd
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/


#import <mobileassetd/mobileassetd-Structs.h>
@interface ASConnectionManager : NSObject {

	CFArrayRef _downloadObserverConnections;
	CFArrayRef _cancelClientConnections;
	CFArrayRef _pauseClientConnections;
	CFArrayRef _resumeClientConnections;

}
+(id)connectionManagerWithAsset:(_MobileAsset*)arg1 replyingToMessage:(id)arg2 onConnection:(id)arg3 messageKind:(int)arg4 ;
+(id)managersDictQueue;
+(id)managersDict;
-(void)sendStatus:(int)arg1 toClients:(int)arg2 ;
-(void)sendProgressMessageWithOperation:(id)arg1 progress:(float)arg2 callbackState:(id)arg3 toClients:(int)arg4 ;
-(void)sendErrorMessageWithError:(id)arg1 toClients:(int)arg2 ;
-(void)sendConnectionTerminationToClients:(int)arg1 ;
-(void)addClientOfMessageKind:(int)arg1 replyingToMessage:(id)arg2 onConnection:(id)arg3 ;
-(void)sendStatus:(int)arg1 toClientConnections:(CFArrayRef)arg2 ;
-(void)tearDown;
-(void)dealloc;
-(id)init;
@end

