/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 10:52:18 PM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /usr/libexec/tzd
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/


@class NSURL, NSDictionary, NSString, NSArray;

@interface TZAsset : NSObject {

	NSURL* _localURL;
	NSDictionary* _versionInfo;
	NSString* _tzDataVersion;
	NSString* _icuChecksumBaseline;
	NSString* _icuChecksumAsset;
	NSString* _icuCurrentName;
	NSString* _icuPreviousName;
	NSArray* _changedFiles;
	NSURL* _icuPatchFileURL;
	NSURL* _zoneinfoURL;
	NSURL* _destinationDirectoryURL;
	NSURL* _versionPlistLocation;

}

@property (retain) NSURL * localURL;                             //@synthesize localURL=_localURL - In the implementation block
@property (retain) NSDictionary * versionInfo;                   //@synthesize versionInfo=_versionInfo - In the implementation block
@property (retain) NSString * tzDataVersion;                     //@synthesize tzDataVersion=_tzDataVersion - In the implementation block
@property (retain) NSString * icuChecksumBaseline;               //@synthesize icuChecksumBaseline=_icuChecksumBaseline - In the implementation block
@property (retain) NSString * icuChecksumAsset;                  //@synthesize icuChecksumAsset=_icuChecksumAsset - In the implementation block
@property (retain) NSString * icuCurrentName;                    //@synthesize icuCurrentName=_icuCurrentName - In the implementation block
@property (retain) NSString * icuPreviousName;                   //@synthesize icuPreviousName=_icuPreviousName - In the implementation block
@property (retain) NSArray * changedFiles;                       //@synthesize changedFiles=_changedFiles - In the implementation block
@property (retain) NSURL * icuPatchFileURL;                      //@synthesize icuPatchFileURL=_icuPatchFileURL - In the implementation block
@property (retain) NSURL * zoneinfoURL;                          //@synthesize zoneinfoURL=_zoneinfoURL - In the implementation block
@property (retain) NSURL * destinationDirectoryURL;              //@synthesize destinationDirectoryURL=_destinationDirectoryURL - In the implementation block
@property (retain) NSURL * versionPlistLocation;                 //@synthesize versionPlistLocation=_versionPlistLocation - In the implementation block
+(id)_versionInfoFromLocalURL:(id)arg1 WithError:(id*)arg2 ;
+(BOOL)_verifyVersionInfoDictionary:(id)arg1 ;
+(id)TZAssetWithAsset:(id)arg1 error:(id*)arg2 ;
-(id)tzDataVersion;
-(id)zoneinfoURL;
-(id)versionPlistLocation;
-(id)icuPreviousName;
-(id)icuCurrentName;
-(id)icuPatchFileURL;
-(id)icuChecksumAsset;
-(void)setTzDataVersion:(id)arg1 ;
-(id)initWithLocalAssetURL:(id)arg1 VersionInfo:(id)arg2 ;
-(id)versionInfo;
-(void)setVersionInfo:(id)arg1 ;
-(id)icuChecksumBaseline;
-(void)setIcuChecksumBaseline:(id)arg1 ;
-(void)setIcuChecksumAsset:(id)arg1 ;
-(void)setIcuCurrentName:(id)arg1 ;
-(void)setIcuPreviousName:(id)arg1 ;
-(id)changedFiles;
-(void)setChangedFiles:(id)arg1 ;
-(void)setIcuPatchFileURL:(id)arg1 ;
-(void)setZoneinfoURL:(id)arg1 ;
-(id)destinationDirectoryURL;
-(void)setDestinationDirectoryURL:(id)arg1 ;
-(void)setVersionPlistLocation:(id)arg1 ;
-(void)setLocalURL:(id)arg1 ;
-(id)localURL;
-(void).cxx_destruct;
@end

