/*
* This header is generated by classdump-dyld 0.1
* on Thursday, November 28, 2013 at 3:59:33 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/FacebookAccountMigrationDialog.app/FacebookAccountMigrationDialog
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UINavigationController.h>

@interface SLFacebookMigrationNavigationController : UINavigationController {

	int _orientation;

}

@property (assign,nonatomic) int orientation;              //@synthesize orientation=_orientation - In the implementation block
-(int)orientation;
-(BOOL)shouldAutorotate;
-(void)setOrientation:(int)arg1 ;
@end

