/*
* This header is generated by classdump-dyld 0.1
* on Thursday, November 28, 2013 at 3:59:21 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/AdSheet.app/AdSheet
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/

typedef struct CGImage* CGImageRef;

typedef struct __SCDynamicStore* SCDynamicStoreRef;

typedef struct __CFUserNotification* CFUserNotificationRef;

typedef struct __CFDictionary* CFDictionaryRef;

typedef struct __CFString* CFStringRef;

typedef struct CGPoint {
	float x;
	float y;
} CGPoint;

typedef struct CGSize {
	float width;
	float height;
} CGSize;

typedef struct CGRect {
	CGPoint origin;
	CGSize size;
} CGRect;

