/*
* This header is generated by classdump-dyld 0.1
* on Thursday, November 28, 2013 at 3:59:18 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/AdSheet.app/AdSheet
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/

#import <AdSheet/AdSheet-Structs.h>
#import <UIKit/UIWindow.h>

@interface ADSLayerHostWindow : UIWindow
+(id)layerHostWindowForView:(id)arg1 ;
-(CGAffineTransform)_screenTransform:(float)arg1 ;
-(CGPoint)_adjustForClassic:(CGPoint)arg1 ;
-(void)_setupConfiguration;
-(CGPoint)_centerForFrame:(CGRect)arg1 ;
-(id)init;
-(void)setFrame:(CGRect)arg1 ;
-(BOOL)_isWindowServerHostingManaged;
-(void)_updateTransformLayerForClassicPresentation;
-(void)handleStatusBarChangeFromHeight:(float)arg1 toHeight:(float)arg2 ;
@end

