/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 1:39:34 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/VoiceMemos.app/VoiceMemos
* classdump-dyld is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/

#import <VoiceMemos/VoiceMemos-Structs.h>
#import <UIKit/UIApplication.h>

@interface RecorderApp : UIApplication {

	BOOL _suspending;

}

@property (nonatomic,readonly) BOOL isSuspending; 
-(BOOL)isSuspending;
-(void)applicationWillSuspend;
-(BOOL)applicationSuspend:(GSEventRef)arg1 settings:(id)arg2 ;
-(void)applicationResume:(GSEventRef)arg1 ;
@end

