/*
* This header is generated by strong_classdump 0.1
* on Wednesday, November 27, 2013 at 12:01:15 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/MobileMail.app/MobileMail
* strong_classdump is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/


@class NSMutableSet, NSMutableDictionary, NSMutableIndexSet;

@interface _MCVCMallContext : NSObject {

	BOOL _showingSearchProgress;
	BOOL _showingNoMessages;
	BOOL _delayingReloadingMessages;
	NSMutableSet* _messagesPendingReload;
	NSMutableDictionary* _bannerViews;
	NSMutableIndexSet* _sectionsShowingSpinner;

}

@property (assign,getter=isShowingSearchProgress,nonatomic) BOOL showingSearchProgress;                      //@synthesize showingSearchProgress=_showingSearchProgress - In the implementation block
@property (assign,getter=isShowingNoMessages,nonatomic) BOOL showingNoMessages;                              //@synthesize showingNoMessages=_showingNoMessages - In the implementation block
@property (assign,getter=isDelayingReloadingMessages,nonatomic) BOOL delayingReloadingMessages;              //@synthesize delayingReloadingMessages=_delayingReloadingMessages - In the implementation block
@property (nonatomic,retain) NSMutableSet * messagesPendingReload;                                           //@synthesize messagesPendingReload=_messagesPendingReload - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * bannerViews;                                              //@synthesize bannerViews=_bannerViews - In the implementation block
@property (nonatomic,retain) NSMutableIndexSet * sectionsShowingSpinner;                                     //@synthesize sectionsShowingSpinner=_sectionsShowingSpinner - In the implementation block
-(id)bannerViews;
-(id)sectionsShowingSpinner;
-(BOOL)isShowingSearchProgress;
-(void)setShowingSearchProgress:(BOOL)arg1 ;
-(BOOL)isShowingNoMessages;
-(void)setShowingNoMessages:(BOOL)arg1 ;
-(BOOL)isDelayingReloadingMessages;
-(void)setDelayingReloadingMessages:(BOOL)arg1 ;
-(id)messagesPendingReload;
-(void)setMessagesPendingReload:(id)arg1 ;
-(void)setBannerViews:(id)arg1 ;
-(void)setSectionsShowingSpinner:(id)arg1 ;
-(void)dealloc;
@end

