/*
* This header is generated by classdump-dyld 0.1
* on Thursday, November 28, 2013 at 4:00:12 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/


@class NSArray;

@interface _MFResultsGenerator : NSObject {

	NSArray* _resultKeys;

}
-(id)initWithKeys:(id)arg1 ;
-(SEL)selectorForKey:(id)arg1 ;
-(id)copyResults;
-(void)dealloc;
-(id)init;
-(id)valueForKey:(id)arg1 ;
-(id)keys;
-(id)results;
@end

