/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 1:38:45 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/


@class NSDateFormatter;

@interface _SearchTimePeriodDateFormatter : NSObject {

	unsigned _deltaUnit;
	int _delta;
	NSDateFormatter* _dateFormatter;
	unsigned _units;

}

@property (nonatomic,retain) NSDateFormatter * dateFormatter;              //@synthesize dateFormatter=_dateFormatter - In the implementation block
@property (assign,nonatomic) unsigned units;                               //@synthesize units=_units - In the implementation block
-(void)setDateFormatter:(id)arg1 ;
-(void)useDelta:(int)arg1 forUnit:(unsigned)arg2 ;
-(id)alternativeFromPhrase:(id)arg1 ;
-(void)dealloc;
-(id)dateFormatter;
-(unsigned)units;
-(void)setUnits:(unsigned)arg1 ;
@end

