/*
* This header is generated by strong_classdump 0.1
* on Wednesday, November 27, 2013 at 12:01:18 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/MobileMail.app/MobileMail
* strong_classdump is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/


@protocol ABPersonViewControllerPrivateDelegate <ABPersonViewControllerDelegate>
@optional
-(void*)personForVCardRepresentation;
-(BOOL)personViewController:(id)arg1 shouldPresentMessageCompositionWithVCard:(id)arg2 filename:(id)arg3;
-(void)personViewController:(id)arg1 willSetEditing:(BOOL)arg2 animated:(BOOL)arg3;
-(void)personViewController:(id)arg1 didLoadScrollView:(id)arg2;
-(BOOL)isPersonViewControllerInCustomPopover:(id)arg1;
-(void)personViewController:(id)arg1 scrollViewDidScroll:(id)arg2;
-(void)personViewController:(id)arg1 didReloadDataInScrollView:(id)arg2;
@end

