/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 10:35:23 PM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/


@protocol DDDetectionControllerDelegate
@optional
-(id)detectionController:(id)arg1 coreRecentsWeightForResult:(DDResultRef)arg2 inContainer:(id)arg3 partOfSignature:(BOOL)arg4;
-(id)detectionController:(id)arg1 coreRecentsWeightForResult:(DDResultRef)arg2 fromScanQuery:(DDScanQueryRef)arg3 inContainer:(id)arg4 partOfSignature:(BOOL)arg5;
@end

