/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 10:35:24 PM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/

#import <MobileMail/MobileMail-Structs.h>
#import <UIKit/UITableViewCell.h>
#import <MobileMail/MBLSingleMessageClient.h>
#import <MobileMail/MailboxContentTableEntry.h>

@class MFMailMessage, UIDateLabel, _MailboxContentViewCellLayoutValues, NSArray, NSString, NSAttributedString, NSMutableArray, _CellStaticView, MessageListStatusIndicatorManager, UILabel, MFSimpleLabel, UIImageView, UIColor;

@interface MailboxContentViewCell : UITableViewCell <MBLSingleMessageClient, MailboxContentTableEntry> {

	MFMailMessage* _message;
	UIDateLabel* _dateLabel;
	_MailboxContentViewCellLayoutValues* _layoutValues;
	NSArray* _highlightedTerms;
	NSString* _address;
	NSString* _subject;
	NSString* _summary;
	NSString* _mailboxName;
	NSAttributedString* _attributedAddress;
	NSAttributedString* _attributedSubject;
	NSAttributedString* _attributedSummary;
	NSRange _firstAddressRange;
	NSRange _firstSubjectRange;
	NSRange _firstSummaryRange;
	double _interval;
	unsigned _generationNumber;
	NSString* _bestRecipientString;
	NSArray* _recipientRangeMatches;
	int _bestMatchLabelType;
	int _recipientLabelType;
	int _chevronType;
	NSMutableArray* _viewsToLayoutDuringTransition;
	_CellStaticView* _staticView;
	MessageListStatusIndicatorManager* _statusIndicatorLayoutManager;
	UILabel* _mailboxNameLabel;
	MFSimpleLabel* _addressLabel;
	MFSimpleLabel* _subjectLabel;
	MFSimpleLabel* _summaryLabel;
	UIImageView* _recipientLabelImageView;
	UIImageView* _bestMatchLabelImageView;
	UIImageView* _chevron;
	UIColor* _originalBackgroundColor;
	unsigned _isFlagged : 1;
	unsigned _isUnread : 1;
	unsigned _isReplied : 1;
	unsigned _isForwarded : 1;
	unsigned _isVIP : 1;
	unsigned _hasAttachments : 1;
	unsigned _threaded : 1;
	unsigned _removeFromMBL : 1;
	unsigned _needsSummary : 1;
	unsigned _shouldHighlightDate : 1;
	unsigned _preferToOverFrom : 1;
	unsigned _showsBestMatchedAddress : 1;
	BOOL _subjectIsPresent;
	BOOL _addressIsPresent;

}

@property (getter=isThreaded,nonatomic,readonly) BOOL threaded; 
@property (assign,nonatomic) BOOL subjectIsPresent;                          //@synthesize subjectIsPresent=_subjectIsPresent - In the implementation block
@property (assign,nonatomic) BOOL addressIsPresent;                          //@synthesize addressIsPresent=_addressIsPresent - In the implementation block
@property (nonatomic,retain) UIColor * originalBackgroundColor;              //@synthesize originalBackgroundColor=_originalBackgroundColor - In the implementation block
+(void)emptyCaches;
+(float)marginWidthEditing:(BOOL)arg1 ;
+(float)contentLeftInsetEditing:(BOOL)arg1 ;
+(float)defaultRowHeight;
+(void)invalidateCachedLayoutInformation;
-(void)setHighlightedTerms:(id)arg1 ;
-(void)setShowsBestMatchedAddress:(BOOL)arg1 ;
-(void)setPrefersToOverFrom:(BOOL)arg1 ;
-(void)setShowsAccessory:(BOOL)arg1 ;
-(void)updateRecipientToCc:(BOOL)arg1 ;
-(void)setShouldHighlightDate:(BOOL)arg1 ;
-(void)setDisplayUnreadDot:(BOOL)arg1 ;
-(void)setDisplayVIP:(BOOL)arg1 ;
-(void)setAddressIsPresent:(BOOL)arg1 ;
-(BOOL)isThreaded;
-(id)_dateLabel;
-(void)setMessage:(id)arg1 threaded:(BOOL)arg2 ;
-(void)setThreadMessageCount:(unsigned)arg1 hasUnreadMessages:(BOOL)arg2 hasAttachments:(BOOL)arg3 hasFlagged:(BOOL)arg4 hasVIP:(BOOL)arg5 receivedInterval:(double)arg6 ;
-(void)updateFlagsFromMessage:(id)arg1 ;
-(void)_layoutValuesDidChange;
-(void)_invalidateCachedValues;
-(id)_dateLabelTextColor;
-(void)staticViewNeedsDisplay;
-(void)staticViewNeedsLayout;
-(void)layoutStatusIndicatorViews;
-(id)_statusIndicatorLayoutManager;
-(void)_recalculateAttributedStrings;
-(id)_mailboxNameLabel;
-(id)_addressLabel;
-(id)_subjectLabel;
-(id)_summaryLabel;
-(id)_recipientLabelImageView;
-(id)_bestMatchLabelImageView;
-(id)_chevron;
-(CGRect)rectForDateWithBounds:(CGRect)arg1 ;
-(CGRect)rectForMailboxNameWithBounds:(CGRect)arg1 dateRect:(CGRect)arg2 ;
-(CGRect)rectForAddressWithBounds:(CGRect)arg1 dateRect:(CGRect)arg2 ;
-(CGRect)rectForSubjectWithBounds:(CGRect)arg1 mailboxRect:(CGRect)arg2 ;
-(CGRect)rectForSummaryWithBounds:(CGRect)arg1 ;
-(CGRect)rectForRecipientLabelWithBounds:(CGRect)arg1 ;
-(CGRect)rectForBestMatchLabelWithBounds:(CGRect)arg1 ;
-(CGRect)rectForChevronWithBounds:(CGRect)arg1 ;
-(CGRect)rectForStatusIndicatorViewsWithPrimaryStatusIndicatorImage:(id)arg1 ;
-(void)_cancelMessageBodyLoad;
-(void)_updateSummary;
-(void)_requestMessageBodyLoadForMessage:(id)arg1 ;
-(id)_copyAttributedStringWithString:(id)arg1 attributes:(id)arg2 matchRanges:(id)arg3 matchAttributes:(id)arg4 ;
-(NSRange)_focusableRangeWithString:(id)arg1 ranges:(id)arg2 ;
-(id)_addressAttributesWithColor:(id)arg1 ;
-(id)bestRecipientStringWithMatchedRanges:(id*)arg1 labelType:(int*)arg2 ;
-(BOOL)addressIsPresent;
-(id)_subjectAttributesWithColor:(id)arg1 ;
-(id)_copyAttributedStringWithString:(id)arg1 attributes:(id)arg2 searchTerms:(id)arg3 matchAttributes:(id)arg4 firstHighlightedRange:(NSRange*)arg5 ;
-(BOOL)subjectIsPresent;
-(id)_bodyAttributesWithColor:(id)arg1 ;
-(BOOL)wantsContentsOfType:(int)arg1 ;
-(void)notifyContentsAvailable:(id)arg1 forMessage:(id)arg2 ;
-(void)notifyContentsUnavailableForMessage:(id)arg1 error:(id)arg2 ;
-(void)notifyFullMessageContentsUnavailableForMessage:(id)arg1 error:(id)arg2 ;
-(BOOL)isFlagged;
-(BOOL)isUnread;
-(BOOL)isReplied;
-(BOOL)isForwarded;
-(void)drawInStaticView:(id)arg1 highlighted:(BOOL)arg2 ;
-(unsigned)generationNumberForStaticView:(id)arg1 ;
-(BOOL)isSelectedForStaticView:(id)arg1 ;
-(void)setSubjectIsPresent:(BOOL)arg1 ;
-(id)originalBackgroundColor;
-(void)setOriginalBackgroundColor:(id)arg1 ;
-(double)ordering;
-(void)setAddress:(id)arg1 ;
-(float)_rightInset;
-(float)_leftInset;
-(void)dealloc;
-(void)layoutSubviews;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2 ;
-(id)description;
-(UIEdgeInsets)edgeInsets;
-(id)_scriptingInfo;
-(id)message;
-(void)setTimeInterval:(double)arg1 ;
-(id)_multiselectBackgroundColor;
-(void)didTransitionToState:(unsigned)arg1 ;
-(void)willTransitionToState:(unsigned)arg1 ;
-(unsigned)priority;
-(void)setMailboxName:(id)arg1 ;
-(void)_significantTimeChange;
@end

