/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 10:35:27 PM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/


@interface MCSChangeUtilities : NSObject
+(id)mergeMessageChanges:(id)arg1 withChanges:(id)arg2 ;
+(id)allMessagesInChanges:(id)arg1 ;
+(id)flagChangesForKey:(id)arg1 ;
@end

