/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 10:35:29 PM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/

#import <MobileMail/_ContextDictionary.h>

@class NSMutableIndexSet;

@interface MegaMRowsChangedContext : _ContextDictionary

@property (assign,nonatomic) int section; 
@property (nonatomic,retain) NSMutableIndexSet * insertedIndices; 
@property (nonatomic,retain) NSMutableIndexSet * removedIndices; 
@property (nonatomic,retain) NSMutableIndexSet * updatedIndices; 
@property (nonatomic,retain) NSMutableIndexSet * destinationIndices; 
@property (nonatomic,retain) NSMutableIndexSet * relocatedIndices; 
+(id)_sharedKeySet;
-(id)insertedIndices;
-(id)removedIndices;
-(id)updatedIndices;
-(id)destinationIndices;
-(id)relocatedIndices;
-(void)setRemovedIndices:(id)arg1 ;
-(void)setInsertedIndices:(id)arg1 ;
-(void)setUpdatedIndices:(id)arg1 ;
-(void)setRelocatedIndices:(id)arg1 ;
-(void)setDestinationIndices:(id)arg1 ;
-(int)section;
-(void)setSection:(int)arg1 ;
-(BOOL)hasChanges;
@end

