/*
* This header is generated by strong_classdump 0.1
* on Wednesday, November 27, 2013 at 12:01:20 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/MobileMail.app/MobileMail
* strong_classdump is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/

#import <MobileMail/MobileMail-Structs.h>
#import <UIKit/UIView.h>

@protocol MFArrowControlsViewDelegate;
@class UIButton, ;

@interface MFArrowControlsView : UIView {

	UIButton* _upButton;
	UIButton* _downButton;
	<MFArrowControlsViewDelegate>* _delegate;
	int _interfaceOrientation;

}

@property (assign,nonatomic) <MFArrowControlsViewDelegate> * delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,readonly) UIButton * downButton;                               //@synthesize downButton=_downButton - In the implementation block
@property (nonatomic,readonly) UIButton * upButton;                                 //@synthesize upButton=_upButton - In the implementation block
@property (assign,nonatomic) int interfaceOrientation;                              //@synthesize interfaceOrientation=_interfaceOrientation - In the implementation block
+(float)defaultWidthForOrientation:(int)arg1 ;
+(float)defaultHeightForOrientation:(int)arg1 ;
-(id)upButton;
-(void)_arrowButtonWasTapped:(id)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)setDelegate:(id)arg1 ;
-(id)hitTest:(CGPoint)arg1 withEvent:(id)arg2 ;
-(void)layoutSubviews;
-(id)delegate;
-(int)interfaceOrientation;
-(void)setInterfaceOrientation:(int)arg1 ;
-(id)downButton;
@end

