/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 10:35:28 PM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/


@protocol MFSearchAlternativesManagerDelegate <NSObject>
@required
-(void)alternativesManager:(id)arg1 foundAlternatives:(id)arg2 forIdentifier:(id)arg3;
-(void)alternativesManager:(id)arg1 finishedWithIdentifier:(id)arg2;
@end

