/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 1:38:43 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/

#import <MobileMail/MFServiceConnectionState.h>

@protocol OS_xpc_object, OS_dispatch_queue;
@class NSObject, NSLock, MailXPCServices;

@interface MFXPCConnection : NSObject <MFServiceConnectionState> {

	NSObject<OS_xpc_object>* _connection;
	NSObject<OS_dispatch_queue>* _connectionQueue;
	NSObject<OS_dispatch_queue>* _messageQueue;
	int _cancelFlag;
	NSLock* _errorHandlerLock;
	/*^block*/ id _errorHandler;
	MailXPCServices* _serviceManager;

}

@property (assign,nonatomic) MailXPCServices * serviceManager;              //@synthesize serviceManager=_serviceManager - In the implementation block
@property (copy) id errorHandler;                                           //@synthesize errorHandler=_errorHandler - In the implementation block
-(/*^block*/ id)errorHandler;
-(void)dealloc;
-(void)start;
-(void)stop;
-(void)setErrorHandler:(/*^block*/ id)arg1 ;
-(id)initWithConnection:(id)arg1 ;
-(void)setServiceManager:(id)arg1 ;
-(id)serviceManager;
-(void)handleError:(id)arg1 ;
-(BOOL)shouldCancel;
@end

