/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 1:38:42 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/


@protocol MiniMallSearchWrapper <MiniMallSource>
@property (getter=isSearching,readonly) BOOL searching; 
@required
-(void)searchForMessagesMatchingCriterion:(id)arg1;
-(BOOL)isSearching;
@end

