/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 10:35:28 PM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/

#import <MobileMail/MobileMail-Structs.h>
#import <UIKit/UIControl.h>

@class UIScrollView, UISegmentedControl, UIView, NSArray;

@interface SearchScopeControl : UIControl {

	UIScrollView* _scrollView;
	UISegmentedControl* _segments;
	UIView* _separator;
	NSArray* _scopeTitles;

}

@property (nonatomic,copy) NSArray * scopeTitles;                 //@synthesize scopeTitles=_scopeTitles - In the implementation block
@property (assign,nonatomic) int selectedScopeIndex; 
-(int)selectedScopeIndex;
-(void)setScopeTitles:(id)arg1 ;
-(void)setSelectedScopeIndex:(int)arg1 ;
-(void)_segmentValueChanged:(id)arg1 ;
-(void)_updateMaskIfNecessary;
-(void)setScopeTitles:(id)arg1 animated:(BOOL)arg2 ;
-(void)_updateTitles:(BOOL)arg1 ;
-(id)scopeTitles;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(void)willMoveToSuperview:(id)arg1 ;
-(void)_didScroll;
@end

