/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 1:38:42 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/


@protocol StackElementDelegate
@required
-(void)stackElement:(id)arg1 currentStateDidChangeFrom:(int)arg2 to:(int)arg3;
-(id)stackContainerView;
-(int)maximumStackElementDepth;
-(UIEdgeInsets*)stackContainerViewEdgeInsets;
-(BOOL)stackIsTerminating;
-(id)viewForStackElement:(id)arg1;
-(id)viewBelowStackElement:(id)arg1;
-(void)stackElement:(id)arg1 willRemoveView:(id)arg2;
-(void)stackElement:(id)arg1 targetStateDidChangeFrom:(int)arg2 to:(int)arg3;
@end

