/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 10:35:23 PM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/MobileMail.app/MobileMail
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/

#import <Message/MFMailboxUid.h>

@class NSString;

@interface StaticMailbox : MFMailboxUid {

	NSString* _plistPath;

}
-(id)initWithMessagePlistAtPath:(id)arg1 ;
-(id)store;
-(void)dealloc;
-(id)name;
-(id)displayName;
-(unsigned)unreadCount;
-(id)plistPath;
@end

