/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 1:39:21 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/PrintStatus.app/PrintStatus
* classdump-dyld is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/

#import <SpringBoardUIServices/_SBUISwitcherPageServiceViewController.h>

@interface PrintStatusViewController : _SBUISwitcherPageServiceViewController
-(void)viewDidLoad;
@end

