#import <libAWDProtobufWifi.dylib/AWDWiFiMetricNetworkPrefs.h>
#import <libAWDProtobufWifi.dylib/AWDWifiAssociation.h>
#import <libAWDProtobufWifi.dylib/AWDWiFiMetricHotspotTransportType.h>
#import <libAWDProtobufWifi.dylib/AWDWiFiMetricLinkChangeData.h>
#import <libAWDProtobufWifi.dylib/AWDWifiPowerState.h>
#import <libAWDProtobufWifi.dylib/AWDWiFiMetricsManagerPowerStatsUpdateEvent.h>
#import <libAWDProtobufWifi.dylib/AWDWiFiMetricIPv4DHCPLatency.h>
#import <libAWDProtobufWifi.dylib/AWDWiFiMetricInterfaceStats.h>
#import <libAWDProtobufWifi.dylib/AWDWiFiMetricsKnownNetworksEvent.h>
#import <libAWDProtobufWifi.dylib/AWDWifiMetricWiFiTetheredDeviceOUI.h>
#import <libAWDProtobufWifi.dylib/AWDWiFiMetricsManagerDeviceCount.h>
#import <libAWDProtobufWifi.dylib/AWDWifiHardwareVersion.h>
#import <libAWDProtobufWifi.dylib/AWDWifiMostUsedNetworks.h>
#import <libAWDProtobufWifi.dylib/AWDWiFiMetricRssiHistory.h>
#import <libAWDProtobufWifi.dylib/AWDWiFiMetricCustomNetworkSetting.h>
#import <libAWDProtobufWifi.dylib/AWDWiFiMetricWowState.h>
#import <libAWDProtobufWifi.dylib/AWDWiFiMetricsManagerWifidAvailability.h>
#import <libAWDProtobufWifi.dylib/AWDWiFiMetricsManagerWatchdogEvent.h>
