/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 10:52:19 PM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /usr/sbin/BTAvrcp
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/

#import <BTAvrcp/BTAVRCP_VFSFolder.h>

@class NSNumber;

@interface BTAVRCP_PlaylistsFolder : BTAVRCP_VFSFolder {

	NSNumber* _parentPlaylistID;

}
-(unsigned char)createFolderWithUid:(unsigned long long)arg1 folder:(id*)arg2 ;
-(id)replyItemAtIndex:(unsigned)arg1 attributeIDs:(id)arg2 ;
-(id)replyAttributesForUid:(unsigned long long)arg1 attributeIDs:(id)arg2 ;
-(unsigned char)playItemWithUid:(unsigned long long)arg1 ;
-(id)initWithName:(id)arg1 uid:(unsigned long long)arg2 parent:(id)arg3 ;
-(id)initWithName:(id)arg1 uid:(unsigned long long)arg2 parent:(id)arg3 parentPlaylistID:(id)arg4 ;
-(BOOL)playlistIsFolder:(id)arg1 ;
-(id)baseQuery;
-(void)dealloc;
-(unsigned)childrenCount;
@end

