/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 10:34:34 PM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /usr/lib/system/libsystem_network.dylib
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/

#import <libdispatch.dylib/OS_object.h>

@interface OS_tcp_connection_bonjour : OS_object
-(void)_dispose;
@end

