/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 1:55:31 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /usr/libexec/webinspectord
* classdump-dyld is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/


@class NSData;

@interface TCPRelayMessage : NSObject {

	NSData* _payload;
	BOOL _writtenHeader;
	unsigned _writtenPayloadOffset;

}

@property (nonatomic,readonly) unsigned length; 
@property (nonatomic,readonly) NSData * payload;              //@synthesize payload=_payload - In the implementation block
+(id)TCPRelayMessageWithPayload:(id)arg1 ;
+(id)TCPRelayMessageFromDataStream:(id)arg1 error:(id*)arg2 ;
-(id)initWithPayload:(id)arg1 ;
-(void)dealloc;
-(unsigned)length;
-(id)payload;
-(int)write:(int)arg1 ;
@end

