/SourceCache/nsnetworkd/CFNetwork-672.0.8/nsnetworkd/
main.mm
/private/var/tmp/nsnetworkd/nsnetworkd-672.0.8~1/CFNetwork.build/nsnetworkd.build/Objects-normal/armv7/main.o
_main
GCC_except_table0
/SourceCache/nsnetworkd/CFNetwork-672.0.8/nsnetworkd/
NDAdditions.mm
/private/var/tmp/nsnetworkd/nsnetworkd-672.0.8~1/CFNetwork.build/nsnetworkd.build/Objects-normal/armv7/NDAdditions.o
-[NSString(nsnetworkd_Additions) _sha1Hash]
-[NSError(nsnetworkd_Additions) _isRecoverableErrorForBackgroundTaskWithStartTime:resourceTimeout:]
-[NSError(nsnetworkd_Additions) _errorShouldSuppressWake]
-[NSError(nsnetworkd_Additions) _cancelledReasonForError]
GCC_except_table0
GCC_except_table1
GCC_except_table2
GCC_except_table3
/SourceCache/nsnetworkd/CFNetwork-672.0.8/nsnetworkd/
NDTaskMonitor.mm
/private/var/tmp/nsnetworkd/nsnetworkd-672.0.8~1/CFNetwork.build/nsnetworkd.build/Objects-normal/armv7/NDTaskMonitor.o
-[NDTaskMonitor setupTimeoutTimerWithTimeout:]
___46-[NDTaskMonitor setupTimeoutTimerWithTimeout:]_block_invoke
___copy_helper_block_
___destroy_helper_block_
-[NDTaskMonitor setThroughputTimerForCurrentInterval]
___53-[NDTaskMonitor setThroughputTimerForCurrentInterval]_block_invoke
___copy_helper_block_8
___destroy_helper_block_9
-[NDTaskMonitor setupThroughputTimer]
-[NDTaskMonitor initWithTask:timeout:]
-[NDTaskMonitor currentThroughputThreshold]
-[NDTaskMonitor currentIntervalEndDelta]
-[NDTaskMonitor calculateThroughput]
-[NDTaskMonitor taskTransferredData:]
-[NDTaskMonitor cancel]
-[NDTaskMonitor .cxx_destruct]
GCC_except_table1
GCC_except_table4
GCC_except_table9
GCC_except_table12
GCC_except_table13
__ZL25kNDThroughputKBThresholds
__ZL31kNDThroughputIntervalEndMinutes
___block_descriptor_tmp
___block_descriptor_tmp10
_OBJC_CLASS_$_NDTaskMonitor
_OBJC_METACLASS_$_NDTaskMonitor
_OBJC_IVAR_$_NDTaskMonitor._queue
_OBJC_IVAR_$_NDTaskMonitor._timeoutTimer
_OBJC_IVAR_$_NDTaskMonitor._task
_OBJC_IVAR_$_NDTaskMonitor._throughputTimer
_OBJC_IVAR_$_NDTaskMonitor._throughputInterval
_OBJC_IVAR_$_NDTaskMonitor._progressTimestamps
_OBJC_IVAR_$_NDTaskMonitor._progressValues
/SourceCache/nsnetworkd/CFNetwork-672.0.8/nsnetworkd/
NDUtilities.mm
/private/var/tmp/nsnetworkd/nsnetworkd-672.0.8~1/CFNetwork.build/nsnetworkd.build/Objects-normal/armv7/NDUtilities.o
__Z5NDLog10NDLogLevelP8NSStringz
__Z18NDPowerlogLogEventP8NSStringS0_P16NSURLSessionTaskP10NDTaskInfo
__Z12NDADLogErrorP16NSURLSessionTask8TaskKindP7NSErrorh
__Z17NDADLogResumeDatadd
GCC_except_table0
GCC_except_table1
GCC_except_table2
/SourceCache/nsnetworkd/CFNetwork-672.0.8/nsnetworkd/
NDStatusMonitor.mm
/private/var/tmp/nsnetworkd/nsnetworkd-672.0.8~1/CFNetwork.build/nsnetworkd.build/Objects-normal/armv7/NDStatusMonitor.o
+[NDStatusMonitor sharedMonitor]
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.0.Internal.sdk/usr/include/dispatch/once.h
___32+[NDStatusMonitor sharedMonitor]_block_invoke
-[NDStatusMonitor init]
-[NDStatusMonitor dealloc]
-[NDStatusMonitor performBlockAfterNetworkChangedEvent:]
-[NDStatusMonitor handleDynamicStoreCallback:changedKeys:]
___58-[NDStatusMonitor handleDynamicStoreCallback:changedKeys:]_block_invoke
___copy_helper_block_
___destroy_helper_block_
-[NDStatusMonitor startMonitoringDynamicStore]
__ZL21_dynamicStoreCallbackPK16__SCDynamicStorePK9__CFArrayPv
-[NDStatusMonitor stopMonitoringDynamicStore]
-[NDStatusMonitor start]
-[NDStatusMonitor stop]
-[NDStatusMonitor .cxx_destruct]
___clang_call_terminate
GCC_except_table2
GCC_except_table3
GCC_except_table5
GCC_except_table7
___block_descriptor_tmp
___block_literal_global
___block_descriptor_tmp22
_OBJC_CLASS_$_NDStatusMonitor
_OBJC_METACLASS_$_NDStatusMonitor
_OBJC_IVAR_$_NDStatusMonitor._dynamicStoreSource
_OBJC_IVAR_$_NDStatusMonitor._blocksToExecuteAftetNetworkChange
_OBJC_IVAR_$_NDStatusMonitor._networkChangeEventCount
_OBJC_IVAR_$_NDStatusMonitor._queue
__MergedGlobals
/SourceCache/nsnetworkd/CFNetwork-672.0.8/nsnetworkd/
NDBackgroundSession.mm
/private/var/tmp/nsnetworkd/nsnetworkd-672.0.8~1/CFNetwork.build/nsnetworkd.build/Objects-normal/armv7/NDBackgroundSession.o
-[DummyQueue initWithDispatchQueue:]
-[DummyQueue addOperationWithBlock:]
-[DummyQueue maxConcurrentOperationCount]
-[DummyQueue queue]
-[DummyQueue setQueue:]
-[DummyQueue .cxx_destruct]
-[NDBackgroundSession configurationWithClientConfiguration:forPriority:]
-[NDBackgroundSession initWithConfiguration:bundleID:downloadDirectory:clientProxy:delegate:]
-[NDBackgroundSession sessionForPriority:]
-[NDBackgroundSession setXPCConnection:]
___40-[NDBackgroundSession setXPCConnection:]_block_invoke
___copy_helper_block_
___destroy_helper_block_
___40-[NDBackgroundSession setXPCConnection:]_block_invoke142
___copy_helper_block_145
___destroy_helper_block_146
-[NDBackgroundSession applicationWasQuitFromAppSwitcher:]
___57-[NDBackgroundSession applicationWasQuitFromAppSwitcher:]_block_invoke
___copy_helper_block_162
___destroy_helper_block_163
-[NDBackgroundSession applicationBackgroundUpdatesTurnedOff:]
___61-[NDBackgroundSession applicationBackgroundUpdatesTurnedOff:]_block_invoke
___copy_helper_block_167
___destroy_helper_block_168
-[NDBackgroundSession applicationWasSuspended:]
___47-[NDBackgroundSession applicationWasSuspended:]_block_invoke
___copy_helper_block_172
___destroy_helper_block_173
-[NDBackgroundSession applicationNoLongerInForeground:]
___55-[NDBackgroundSession applicationNoLongerInForeground:]_block_invoke
___55-[NDBackgroundSession applicationNoLongerInForeground:]_block_invoke_2
___copy_helper_block_187
___destroy_helper_block_188
___copy_helper_block_196
___destroy_helper_block_197
-[NDBackgroundSession applicationEnteredForeground:]
___52-[NDBackgroundSession applicationEnteredForeground:]_block_invoke
___copy_helper_block_212
___destroy_helper_block_213
-[NDBackgroundSession clientApplicationWasReinstalled]
___54-[NDBackgroundSession clientApplicationWasReinstalled]_block_invoke
___copy_helper_block_237
___destroy_helper_block_238
-[NDBackgroundSession setupDownloadDirectory:]
-[NDBackgroundSession cleanupSession]
-[NDBackgroundSession obliterate]
___33-[NDBackgroundSession obliterate]_block_invoke
___copy_helper_block_271
___destroy_helper_block_272
-[NDBackgroundSession tasksArchivePath]
-[NDBackgroundSession archiveTaskInfo]
___38-[NDBackgroundSession archiveTaskInfo]_block_invoke
___copy_helper_block_278
___destroy_helper_block_279
-[NDBackgroundSession initializeTask:fromTaskInfo:]
-[NDBackgroundSession createNewTaskFromInfo:]
-[NDBackgroundSession restoreInProgressTask:]
-[NDBackgroundSession restoreCompletedTask:]
-[NDBackgroundSession restoreTask:isOutstanding:]
-[NDBackgroundSession restoreTasks]
-[NDBackgroundSession retryTask:originalError:]
___47-[NDBackgroundSession retryTask:originalError:]_block_invoke
___copy_helper_block_383
___destroy_helper_block_384
-[NDBackgroundSession removeDownloadFileForTaskInfo:]
-[NDBackgroundSession removeUploadFileForTask:]
-[NDBackgroundSession sessionHasOutstandingTasks]
-[NDBackgroundSession getClientProxy]
-[NDBackgroundSession errorOccurredDuringFinishedCallbackDelivery:]
-[NDBackgroundSession errorOccurredDuringAuthCallbackDelivery:completionHandler:]
-[NDBackgroundSession clientAcknowledgedTerminalCallbackForTask:]
-[NDBackgroundSession wakeUpClient]
-[NDBackgroundSession clientIsActive]
-[NDBackgroundSession notifyQueueOfTaskCompletion:identifier:taskInfo:suppressWake:]
-[NDBackgroundSession clientDidDisconnect]
-[NDBackgroundSession reconnectClient:withCompletion:]
___54-[NDBackgroundSession reconnectClient:withCompletion:]_block_invoke
___copy_helper_block_437
___destroy_helper_block_438
-[NDBackgroundSession allowReconnect]
-[NDBackgroundSession createClientTaskForTask:taskInfo:]
-[NDBackgroundSession getTasksForReconnection]
___46-[NDBackgroundSession getTasksForReconnection]_block_invoke
___copy_helper_block_460
___destroy_helper_block_461
-[NDBackgroundSession currentPriority]
-[NDBackgroundSession enqueueTask:withPriority:]
-[NDBackgroundSession downloadTaskWithResumeData:identifier:reply:]
-[NDBackgroundSession downloadTaskWithRequest:originalRequest:identifier:reply:]
-[NDBackgroundSession makeTempUploadFile:]
-[NDBackgroundSession uploadTaskWithRequest:originalRequest:fromFile:identifier:reply:]
-[NDBackgroundSession requeueTask:]
___35-[NDBackgroundSession requeueTask:]_block_invoke
___copy_helper_block_538
___destroy_helper_block_539
-[NDBackgroundSession cancelTaskWithIdentifier:byProducingResumeData:]
___70-[NDBackgroundSession cancelTaskWithIdentifier:byProducingResumeData:]_block_invoke
___copy_helper_block_543
___destroy_helper_block_544
-[NDBackgroundSession cancelTaskWithIdentifier:]
-[NDBackgroundSession suspendTaskWithIdentifier:]
-[NDBackgroundSession resumeTaskWithIdentifier:]
-[NDBackgroundSession setDescription:forTask:]
-[NDBackgroundSession resetStorageWithReply:]
-[NDBackgroundSession cancelMonitorForTask:]
-[NDBackgroundSession taskShouldResume:withTimeout:]
___52-[NDBackgroundSession taskShouldResume:withTimeout:]_block_invoke
___copy_helper_block_571
___destroy_helper_block_572
-[NDBackgroundSession taskShouldSuspend:]
___41-[NDBackgroundSession taskShouldSuspend:]_block_invoke
___copy_helper_block_579
___destroy_helper_block_580
-[NDBackgroundSession URLSession:didBecomeInvalidWithError:]
-[NDBackgroundSession URLSession:task:didReceiveChallenge:completionHandler:]
-[NDBackgroundSession URLSession:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:]
-[NDBackgroundSession URLSession:task:didCompleteWithError:]
-[NDBackgroundSession URLSession:dataTask:willCacheResponse:completionHandler:]
-[NDBackgroundSession URLSession:dataTask:didReceiveResponse:completionHandler:]
-[NDBackgroundSession URLSession:dataTask:didReceiveData:]
-[NDBackgroundSession URLSession:dataTask:didBecomeDownloadTask:]
-[NDBackgroundSession URLSession:downloadTask:didFinishDownloadingToURL:]
-[NDBackgroundSession URLSession:downloadTask:didResumeAtOffset:expectedTotalBytes:]
-[NDBackgroundSession URLSession:downloadTask:didWriteData:totalBytesWritten:totalBytesExpectedToWrite:]
-[NDBackgroundSession _URLSession:downloadTask:didReceiveResponse:]
-[NDBackgroundSession _URLSession:downloadTaskNeedsDownloadDirectory:]
-[NDBackgroundSession delegate]
/SourceCache/nsnetworkd/CFNetwork-672.0.8/nsnetworkd/NDBackgroundSession.h
-[NDBackgroundSession setDelegate:]
-[NDBackgroundSession identifier]
-[NDBackgroundSession .cxx_destruct]
GCC_except_table0
GCC_except_table6
GCC_except_table7
GCC_except_table9
GCC_except_table17
GCC_except_table21
GCC_except_table29
GCC_except_table36
GCC_except_table40
GCC_except_table43
GCC_except_table44
GCC_except_table46
GCC_except_table49
GCC_except_table50
GCC_except_table54
GCC_except_table55
GCC_except_table56
GCC_except_table57
GCC_except_table58
GCC_except_table59
GCC_except_table60
GCC_except_table64
GCC_except_table65
GCC_except_table69
GCC_except_table70
GCC_except_table71
GCC_except_table72
GCC_except_table73
GCC_except_table74
GCC_except_table80
GCC_except_table81
GCC_except_table82
GCC_except_table85
GCC_except_table86
GCC_except_table87
GCC_except_table88
GCC_except_table89
GCC_except_table90
GCC_except_table92
GCC_except_table95
GCC_except_table96
GCC_except_table99
GCC_except_table100
GCC_except_table101
GCC_except_table102
GCC_except_table103
GCC_except_table104
GCC_except_table106
GCC_except_table110
GCC_except_table113
GCC_except_table114
GCC_except_table115
GCC_except_table116
GCC_except_table118
GCC_except_table119
GCC_except_table120
GCC_except_table121
GCC_except_table122
GCC_except_table123
GCC_except_table124
___block_descriptor_tmp
___block_descriptor_tmp147
___block_descriptor_tmp164
___block_descriptor_tmp169
___block_descriptor_tmp174
___block_descriptor_tmp190
___block_descriptor_tmp198
___block_descriptor_tmp214
___block_descriptor_tmp239
___block_descriptor_tmp273
___block_descriptor_tmp280
___block_descriptor_tmp385
___block_descriptor_tmp439
___block_descriptor_tmp463
___block_descriptor_tmp540
___block_descriptor_tmp546
___block_descriptor_tmp574
___block_descriptor_tmp581
_OBJC_CLASS_$_DummyQueue
_OBJC_METACLASS_$_DummyQueue
_OBJC_CLASS_$_NDBackgroundSession
_OBJC_METACLASS_$_NDBackgroundSession
_OBJC_IVAR_$_DummyQueue._queue
_OBJC_IVAR_$_NDBackgroundSession._credentialStorage
_OBJC_IVAR_$_NDBackgroundSession._clientBundleID
_OBJC_IVAR_$_NDBackgroundSession._identifier
_OBJC_IVAR_$_NDBackgroundSession._sessionDirectory
_OBJC_IVAR_$_NDBackgroundSession._downloadDirectory
_OBJC_IVAR_$_NDBackgroundSession._workQueue
_OBJC_IVAR_$_NDBackgroundSession._archiveQueue
_OBJC_IVAR_$_NDBackgroundSession._clientProxy
_OBJC_IVAR_$_NDBackgroundSession._discretionary
_OBJC_IVAR_$_NDBackgroundSession._sendsLaunchEvents
_OBJC_IVAR_$_NDBackgroundSession._userInitiatedSession
_OBJC_IVAR_$_NDBackgroundSession._discretionaryPrioritySession
_OBJC_IVAR_$_NDBackgroundSession._callbackQueue
_OBJC_IVAR_$_NDBackgroundSession._tasksToIdentifiers
_OBJC_IVAR_$_NDBackgroundSession._identifiersToTasks
_OBJC_IVAR_$_NDBackgroundSession._identifiersToTaskInfo
_OBJC_IVAR_$_NDBackgroundSession._identifiersToMonitors
_OBJC_IVAR_$_NDBackgroundSession._outstandingTaskIDs
_OBJC_IVAR_$_NDBackgroundSession._obliterated
_OBJC_IVAR_$_NDBackgroundSession._cleanedUp
_OBJC_IVAR_$_NDBackgroundSession._delayPendingEventsUntilReady
_OBJC_IVAR_$_NDBackgroundSession._readyForPendingEventsSem
_OBJC_IVAR_$_NDBackgroundSession._clientPID
_OBJC_IVAR_$_NDBackgroundSession._xpcConn
_OBJC_IVAR_$_NDBackgroundSession._delegate
/SourceCache/nsnetworkd/CFNetwork-672.0.8/nsnetworkd/
NDCredentialStorage.mm
/private/var/tmp/nsnetworkd/nsnetworkd-672.0.8~1/CFNetwork.build/nsnetworkd.build/Objects-normal/armv7/NDCredentialStorage.o
-[NDCredentialStorage initWithDelegate:]
___40-[NDCredentialStorage initWithDelegate:]_block_invoke
___40-[NDCredentialStorage initWithDelegate:]_block_invoke_2
___40-[NDCredentialStorage initWithDelegate:]_block_invoke_3
___copy_helper_block_
___destroy_helper_block_
___copy_helper_block_8
___destroy_helper_block_9
___copy_helper_block_14
___destroy_helper_block_15
-[NDCredentialStorage credentialsForProtectionSpace:]
___53-[NDCredentialStorage credentialsForProtectionSpace:]_block_invoke
___copy_helper_block_17
___destroy_helper_block_18
___53-[NDCredentialStorage credentialsForProtectionSpace:]_block_invoke23
___53-[NDCredentialStorage credentialsForProtectionSpace:]_block_invoke_2
___copy_helper_block_28
___destroy_helper_block_29
___copy_helper_block_31
___destroy_helper_block_32
___Block_byref_object_copy_
___Block_byref_object_dispose_
___53-[NDCredentialStorage credentialsForProtectionSpace:]_block_invoke37
___copy_helper_block_40
___destroy_helper_block_41
-[NDCredentialStorage allCredentials]
___37-[NDCredentialStorage allCredentials]_block_invoke
___copy_helper_block_43
___destroy_helper_block_44
___37-[NDCredentialStorage allCredentials]_block_invoke46
___37-[NDCredentialStorage allCredentials]_block_invoke_2
___copy_helper_block_49
___destroy_helper_block_50
___copy_helper_block_52
___destroy_helper_block_53
___37-[NDCredentialStorage allCredentials]_block_invoke57
___copy_helper_block_59
___destroy_helper_block_60
-[NDCredentialStorage setCredential:forProtectionSpace:]
___56-[NDCredentialStorage setCredential:forProtectionSpace:]_block_invoke
___copy_helper_block_66
___destroy_helper_block_67
-[NDCredentialStorage removeCredential:forProtectionSpace:]
___59-[NDCredentialStorage removeCredential:forProtectionSpace:]_block_invoke
___copy_helper_block_71
___destroy_helper_block_72
-[NDCredentialStorage defaultCredentialForProtectionSpace:]
___59-[NDCredentialStorage defaultCredentialForProtectionSpace:]_block_invoke
___copy_helper_block_74
___destroy_helper_block_75
___59-[NDCredentialStorage defaultCredentialForProtectionSpace:]_block_invoke77
___59-[NDCredentialStorage defaultCredentialForProtectionSpace:]_block_invoke_2
___copy_helper_block_78
___destroy_helper_block_79
___copy_helper_block_81
___destroy_helper_block_82
___59-[NDCredentialStorage defaultCredentialForProtectionSpace:]_block_invoke87
___copy_helper_block_88
___destroy_helper_block_89
-[NDCredentialStorage setDefaultCredential:forProtectionSpace:]
___63-[NDCredentialStorage setDefaultCredential:forProtectionSpace:]_block_invoke
___copy_helper_block_93
___destroy_helper_block_94
-[NDCredentialStorage reset]
___28-[NDCredentialStorage reset]_block_invoke
___copy_helper_block_96
___destroy_helper_block_97
-[NDCredentialStorage delegate]
/SourceCache/nsnetworkd/CFNetwork-672.0.8/nsnetworkd/NDCredentialStorage.h
-[NDCredentialStorage setDelegate:]
-[NDCredentialStorage .cxx_destruct]
GCC_except_table0
GCC_except_table1
GCC_except_table10
GCC_except_table15
GCC_except_table25
GCC_except_table38
GCC_except_table39
GCC_except_table42
GCC_except_table43
GCC_except_table46
GCC_except_table51
GCC_except_table56
GCC_except_table59
GCC_except_table60
___block_descriptor_tmp
___block_descriptor_tmp11
___block_descriptor_tmp16
___block_descriptor_tmp20
___block_descriptor_tmp30
___block_descriptor_tmp34
___block_descriptor_tmp42
___block_descriptor_tmp45
___block_descriptor_tmp51
___block_descriptor_tmp54
___block_descriptor_tmp61
___block_descriptor_tmp68
___block_descriptor_tmp73
___block_descriptor_tmp76
___block_descriptor_tmp80
___block_descriptor_tmp84
___block_descriptor_tmp90
___block_descriptor_tmp95
___block_descriptor_tmp98
_OBJC_CLASS_$_NDCredentialStorage
_OBJC_METACLASS_$_NDCredentialStorage
_OBJC_IVAR_$_NDCredentialStorage._delegate
_OBJC_IVAR_$_NDCredentialStorage._cachedCredentials
_OBJC_IVAR_$_NDCredentialStorage._cachedDefaultCredentialUsers
_OBJC_IVAR_$_NDCredentialStorage._queue
/SourceCache/nsnetworkd/CFNetwork-672.0.8/nsnetworkd/
NDTaskInfo.mm
/private/var/tmp/nsnetworkd/nsnetworkd-672.0.8~1/CFNetwork.build/nsnetworkd.build/Objects-normal/armv7/NDTaskInfo.o
-[NDTaskInfo initWithTask:bundleID:sessionID:]
-[NDTaskInfo initWithUploadTask:bundleID:sessionID:]
-[NDTaskInfo initWithDownloadTask:bundleID:sessionID:]
-[NDTaskInfo encodeWithCoder:]
-[NDTaskInfo initWithCoder:]
+[NDTaskInfo supportsSecureCoding]
-[NDTaskInfo identifier]
/SourceCache/nsnetworkd/CFNetwork-672.0.8/nsnetworkd/NDTaskInfo.h
-[NDTaskInfo setIdentifier:]
-[NDTaskInfo taskKind]
-[NDTaskInfo setTaskKind:]
-[NDTaskInfo taskPriority]
-[NDTaskInfo setTaskPriority:]
-[NDTaskInfo creationTime]
-[NDTaskInfo setCreationTime:]
-[NDTaskInfo state]
-[NDTaskInfo setState:]
-[NDTaskInfo suspendCount]
-[NDTaskInfo setSuspendCount:]
-[NDTaskInfo taskDescription]
-[NDTaskInfo setTaskDescription:]
-[NDTaskInfo originalRequest]
-[NDTaskInfo setOriginalRequest:]
-[NDTaskInfo currentRequest]
-[NDTaskInfo setCurrentRequest:]
-[NDTaskInfo response]
-[NDTaskInfo setResponse:]
-[NDTaskInfo error]
-[NDTaskInfo setError:]
-[NDTaskInfo fileURL]
-[NDTaskInfo setFileURL:]
-[NDTaskInfo downloadFileURL]
-[NDTaskInfo setDownloadFileURL:]
-[NDTaskInfo bundleID]
-[NDTaskInfo setBundleID:]
-[NDTaskInfo sessionID]
-[NDTaskInfo setSessionID:]
-[NDTaskInfo hasStarted]
-[NDTaskInfo setHasStarted:]
-[NDTaskInfo uniqueIdentifier]
-[NDTaskInfo setUniqueIdentifier:]
-[NDTaskInfo .cxx_destruct]
GCC_except_table0
GCC_except_table1
GCC_except_table2
GCC_except_table3
GCC_except_table4
_OBJC_CLASS_$_NDTaskInfo
_OBJC_METACLASS_$_NDTaskInfo
_OBJC_IVAR_$_NDTaskInfo._identifier
_OBJC_IVAR_$_NDTaskInfo._state
_OBJC_IVAR_$_NDTaskInfo._taskDescription
_OBJC_IVAR_$_NDTaskInfo._originalRequest
_OBJC_IVAR_$_NDTaskInfo._currentRequest
_OBJC_IVAR_$_NDTaskInfo._response
_OBJC_IVAR_$_NDTaskInfo._error
_OBJC_IVAR_$_NDTaskInfo._bundleID
_OBJC_IVAR_$_NDTaskInfo._sessionID
_OBJC_IVAR_$_NDTaskInfo._hasStarted
_OBJC_IVAR_$_NDTaskInfo._uniqueIdentifier
_OBJC_IVAR_$_NDTaskInfo._taskKind
_OBJC_IVAR_$_NDTaskInfo._taskPriority
_OBJC_IVAR_$_NDTaskInfo._creationTime
_OBJC_IVAR_$_NDTaskInfo._suspendCount
_OBJC_IVAR_$_NDTaskInfo._fileURL
_OBJC_IVAR_$_NDTaskInfo._downloadFileURL
/SourceCache/nsnetworkd/CFNetwork-672.0.8/nsnetworkd/
Daemon.mm
/private/var/tmp/nsnetworkd/nsnetworkd-672.0.8~1/CFNetwork.build/nsnetworkd.build/Objects-normal/armv7/Daemon.o
+[Daemon sharedDaemon]
___22+[Daemon sharedDaemon]_block_invoke
+[Daemon nsnetworkdPath]
+[Daemon bundleManagerPath:]
+[Daemon sessionPath:forBundleID:]
-[Daemon createDaemonDirectory]
-[Daemon init]
-[Daemon archivePath]
-[Daemon applicationIsInstalled:]
-[Daemon restoreState]
___22-[Daemon restoreState]_block_invoke
-[Daemon archiveState]
___22-[Daemon archiveState]_block_invoke
___copy_helper_block_
___destroy_helper_block_
-[Daemon listener:shouldAcceptNewConnection:]
-[Daemon getSessionWithIdentifier:forBundleID:]
___Block_byref_object_copy_
___Block_byref_object_dispose_
___47-[Daemon getSessionWithIdentifier:forBundleID:]_block_invoke
___copy_helper_block_250
___destroy_helper_block_251
-[Daemon managerBecameEmpty:bundleID:]
___38-[Daemon managerBecameEmpty:bundleID:]_block_invoke
___copy_helper_block_257
___destroy_helper_block_258
-[Daemon addTransaction]
-[Daemon releaseTransaction]
-[Daemon applicationsDidInstall:]
___33-[Daemon applicationsDidInstall:]_block_invoke
___copy_helper_block_271
___destroy_helper_block_272
-[Daemon applicationsDidUninstall:]
___35-[Daemon applicationsDidUninstall:]_block_invoke
___copy_helper_block_278
___destroy_helper_block_279
-[Daemon start]
___15-[Daemon start]_block_invoke
___copy_helper_block_284
___destroy_helper_block_285
-[Daemon queue]
/SourceCache/nsnetworkd/CFNetwork-672.0.8/nsnetworkd/Daemon.h
-[Daemon .cxx_destruct]
GCC_except_table2
GCC_except_table3
GCC_except_table4
GCC_except_table5
GCC_except_table6
GCC_except_table7
GCC_except_table9
GCC_except_table10
GCC_except_table11
GCC_except_table15
GCC_except_table19
GCC_except_table23
GCC_except_table29
GCC_except_table33
GCC_except_table36
___block_descriptor_tmp
___block_literal_global
___block_descriptor_tmp82
___block_literal_global83
___block_descriptor_tmp108
___block_descriptor_tmp252
___block_descriptor_tmp259
___block_descriptor_tmp273
___block_descriptor_tmp280
___block_descriptor_tmp287
_OBJC_CLASS_$_Daemon
_OBJC_METACLASS_$_Daemon
_OBJC_IVAR_$_Daemon._clients
_OBJC_IVAR_$_Daemon._queue
__MergedGlobals
/SourceCache/nsnetworkd/CFNetwork-672.0.8/nsnetworkd/
NDSpringBoard.mm
/private/var/tmp/nsnetworkd/nsnetworkd-672.0.8~1/CFNetwork.build/nsnetworkd.build/Objects-normal/armv7/NDSpringBoard.o
+[NDSpringBoard sharedSpringBoard]
___34+[NDSpringBoard sharedSpringBoard]_block_invoke
-[NDSpringBoard init]
__ZL30handleBackgroundSettingsChangeP22__CFNotificationCenterPvPK10__CFStringPKvPK14__CFDictionary
-[NDSpringBoard dealloc]
-[NDSpringBoard setupMonitor]
___29-[NDSpringBoard setupMonitor]_block_invoke
-[NDSpringBoard handleAppSwitcherQuitAppNotification:]
___54-[NDSpringBoard handleAppSwitcherQuitAppNotification:]_block_invoke
___copy_helper_block_
___destroy_helper_block_
-[NDSpringBoard getBackgroundSettingsAppList]
-[NDSpringBoard handleBackgroundSettingsChange]
___47-[NDSpringBoard handleBackgroundSettingsChange]_block_invoke
___47-[NDSpringBoard handleBackgroundSettingsChange]_block_invoke_2
___copy_helper_block_87
___destroy_helper_block_88
___47-[NDSpringBoard handleBackgroundSettingsChange]_block_invoke95
___copy_helper_block_98
___destroy_helper_block_99
-[NDSpringBoard handleApplicationStateChange:]
___46-[NDSpringBoard handleApplicationStateChange:]_block_invoke
___copy_helper_block_121
___destroy_helper_block_122
-[NDSpringBoard addObserver:forApplication:]
___44-[NDSpringBoard addObserver:forApplication:]_block_invoke
___copy_helper_block_129
___destroy_helper_block_130
-[NDSpringBoard removeObserver:forApplication:]
___47-[NDSpringBoard removeObserver:forApplication:]_block_invoke
___copy_helper_block_134
___destroy_helper_block_135
-[NDSpringBoard startMonitoringBundleID:]
___41-[NDSpringBoard startMonitoringBundleID:]_block_invoke
___copy_helper_block_141
___destroy_helper_block_142
-[NDSpringBoard stopMonitoringBundleID:]
___40-[NDSpringBoard stopMonitoringBundleID:]_block_invoke
___copy_helper_block_146
___destroy_helper_block_147
-[NDSpringBoard applicationStateForBundleID:]
___45-[NDSpringBoard applicationStateForBundleID:]_block_invoke
___copy_helper_block_149
___destroy_helper_block_150
-[NDSpringBoard applicationIsForeground:]
-[NDSpringBoard applicationIsAwake:]
-[NDSpringBoard applicationIsSuspended:]
-[NDSpringBoard applicationIsBeingDebugged:]
-[NDSpringBoard applicationHasBackgroundTaskCompletion:]
___56-[NDSpringBoard applicationHasBackgroundTaskCompletion:]_block_invoke
___copy_helper_block_156
___destroy_helper_block_157
-[NDSpringBoard bundleIdentifierForProcess:]
-[NDSpringBoard _onqueue_releaseAssertionForBundleID:sessionID:]
-[NDSpringBoard releaseAssertionForBundleID:sessionID:]
___55-[NDSpringBoard releaseAssertionForBundleID:sessionID:]_block_invoke
___copy_helper_block_171
___destroy_helper_block_172
-[NDSpringBoard takeAssertionForBundleID:sessionID:]
___52-[NDSpringBoard takeAssertionForBundleID:sessionID:]_block_invoke
___copy_helper_block_177
___destroy_helper_block_178
-[NDSpringBoard internalWakeUpApp:forSession:]
-[NDSpringBoard application:hasPendingWakeRequestForSession:]
___61-[NDSpringBoard application:hasPendingWakeRequestForSession:]_block_invoke
___copy_helper_block_200
___destroy_helper_block_201
-[NDSpringBoard wakeUpApp:forSession:]
___38-[NDSpringBoard wakeUpApp:forSession:]_block_invoke
___38-[NDSpringBoard wakeUpApp:forSession:]_block_invoke_2
___copy_helper_block_221
___destroy_helper_block_222
___copy_helper_block_226
___destroy_helper_block_227
-[NDSpringBoard .cxx_destruct]
GCC_except_table2
GCC_except_table4
GCC_except_table6
GCC_except_table7
GCC_except_table9
GCC_except_table12
GCC_except_table14
GCC_except_table15
GCC_except_table18
GCC_except_table22
GCC_except_table26
GCC_except_table30
GCC_except_table34
GCC_except_table38
GCC_except_table42
GCC_except_table49
GCC_except_table50
GCC_except_table54
GCC_except_table59
GCC_except_table63
GCC_except_table64
GCC_except_table69
GCC_except_table70
___block_descriptor_tmp
___block_literal_global
___block_descriptor_tmp44
___block_literal_global45
___block_descriptor_tmp58
___block_descriptor_tmp90
___block_descriptor_tmp96
___block_literal_global97
___block_descriptor_tmp100
___block_descriptor_tmp123
___block_descriptor_tmp131
___block_descriptor_tmp136
___block_descriptor_tmp143
___block_descriptor_tmp148
___block_descriptor_tmp151
___block_descriptor_tmp158
___block_descriptor_tmp173
___block_descriptor_tmp180
___block_descriptor_tmp202
___block_descriptor_tmp223
___block_descriptor_tmp228
_OBJC_CLASS_$_NDSpringBoard
_OBJC_METACLASS_$_NDSpringBoard
_OBJC_IVAR_$_NDSpringBoard._monitor
_OBJC_IVAR_$_NDSpringBoard._service
_OBJC_IVAR_$_NDSpringBoard._assertions
_OBJC_IVAR_$_NDSpringBoard._wakeDelays
_OBJC_IVAR_$_NDSpringBoard._nextWakeTimes
_OBJC_IVAR_$_NDSpringBoard._pendingWakes
_OBJC_IVAR_$_NDSpringBoard._observers
_OBJC_IVAR_$_NDSpringBoard._appStates
_OBJC_IVAR_$_NDSpringBoard._backgroundUpdatesAllowed
_OBJC_IVAR_$_NDSpringBoard._observedBackgroundSettings
_OBJC_IVAR_$_NDSpringBoard._monitoredBundleIDs
_OBJC_IVAR_$_NDSpringBoard._queue
__MergedGlobals
/SourceCache/nsnetworkd/CFNetwork-672.0.8/nsnetworkd/
NDSessionManager.mm
/private/var/tmp/nsnetworkd/nsnetworkd-672.0.8~1/CFNetwork.build/nsnetworkd.build/Objects-normal/armv7/NDSessionManager.o
-[NDSessionManager initWithDelegate:bundleID:]
-[NDSessionManager archivePath]
-[NDSessionManager downloadDirectoryDataPath]
-[NDSessionManager restoreState]
-[NDSessionManager archiveState]
___32-[NDSessionManager archiveState]_block_invoke
___copy_helper_block_
___destroy_helper_block_
-[NDSessionManager boost:]
___26-[NDSessionManager boost:]_block_invoke
___copy_helper_block_79
___destroy_helper_block_80
-[NDSessionManager dropBoost]
___29-[NDSessionManager dropBoost]_block_invoke
___copy_helper_block_84
___destroy_helper_block_85
-[NDSessionManager createSessionWithConfiguration:clientProxy:cachesDirectory:reply:]
-[NDSessionManager sendPendingCallbacksForIdentifier:reply:]
___60-[NDSessionManager sendPendingCallbacksForIdentifier:reply:]_block_invoke
___60-[NDSessionManager sendPendingCallbacksForIdentifier:reply:]_block_invoke_2
___copy_helper_block_104
___destroy_helper_block_105
___copy_helper_block_113
___destroy_helper_block_114
-[NDSessionManager releaseAssertionForSession:reply:]
-[NDSessionManager okayToSendPendingCallbacksForIdentifier:reply:]
___66-[NDSessionManager okayToSendPendingCallbacksForIdentifier:reply:]_block_invoke
___copy_helper_block_126
___destroy_helper_block_127
-[NDSessionManager clientDisconnected]
-[NDSessionManager cleanup]
-[NDSessionManager sessionCompleted:]
___37-[NDSessionManager sessionCompleted:]_block_invoke
___copy_helper_block_139
___destroy_helper_block_140
-[NDSessionManager getSessionWithIdentifier:]
-[NDSessionManager clientApplicationWasReinstalled]
___51-[NDSessionManager clientApplicationWasReinstalled]_block_invoke
___51-[NDSessionManager clientApplicationWasReinstalled]_block_invoke_2
___copy_helper_block_148
___destroy_helper_block_149
-[NDSessionManager obliterate]
___30-[NDSessionManager obliterate]_block_invoke
___30-[NDSessionManager obliterate]_block_invoke_2
___copy_helper_block_157
___destroy_helper_block_158
-[NDSessionManager xpcConn]
/SourceCache/nsnetworkd/CFNetwork-672.0.8/nsnetworkd/NDSessionManager.h
-[NDSessionManager setXpcConn:]
-[NDSessionManager delegate]
-[NDSessionManager setDelegate:]
-[NDSessionManager .cxx_destruct]
GCC_except_table0
GCC_except_table1
GCC_except_table2
GCC_except_table3
GCC_except_table4
GCC_except_table9
GCC_except_table13
GCC_except_table16
GCC_except_table17
GCC_except_table18
GCC_except_table24
GCC_except_table25
GCC_except_table26
GCC_except_table30
GCC_except_table31
GCC_except_table32
___block_descriptor_tmp
___block_descriptor_tmp81
___block_descriptor_tmp86
___block_descriptor_tmp106
___block_descriptor_tmp115
___block_descriptor_tmp128
___block_descriptor_tmp141
___block_descriptor_tmp145
___block_literal_global
___block_descriptor_tmp150
___block_descriptor_tmp155
___block_literal_global156
___block_descriptor_tmp159
_OBJC_CLASS_$_NDSessionManager
_OBJC_METACLASS_$_NDSessionManager
_OBJC_IVAR_$_NDSessionManager._delegate
_OBJC_IVAR_$_NDSessionManager._clientBundleID
_OBJC_IVAR_$_NDSessionManager._sessions
_OBJC_IVAR_$_NDSessionManager._reconnectingProxies
_OBJC_IVAR_$_NDSessionManager._bundleDirectory
_OBJC_IVAR_$_NDSessionManager._queue
_OBJC_IVAR_$_NDSessionManager._boostReply
_OBJC_IVAR_$_NDSessionManager._xpcConn
/SourceCache/nsnetworkd/CFNetwork-672.0.8/nsnetworkd/
NDCallbackQueue.mm
/private/var/tmp/nsnetworkd/nsnetworkd-672.0.8~1/CFNetwork.build/nsnetworkd.build/Objects-normal/armv7/NDCallbackQueue.o
-[PendingCallback initWithCallbackType:taskIdentifier:args:]
+[PendingCallback supportsSecureCoding]
-[PendingCallback encodeWithCoder:]
-[PendingCallback initWithCoder:]
-[PendingCallback type]
/SourceCache/nsnetworkd/CFNetwork-672.0.8/nsnetworkd/NDCallbackQueue.h
-[PendingCallback setType:]
-[PendingCallback taskIdentifier]
-[PendingCallback setTaskIdentifier:]
-[PendingCallback args]
-[PendingCallback setArgs:]
-[PendingCallback .cxx_destruct]
-[NDCallbackQueue initWithDelegate:]
-[NDCallbackQueue performCallback:]
___35-[NDCallbackQueue performCallback:]_block_invoke
___copy_helper_block_
___destroy_helper_block_
___35-[NDCallbackQueue performCallback:]_block_invoke74
___copy_helper_block_81
___destroy_helper_block_82
___35-[NDCallbackQueue performCallback:]_block_invoke87
___copy_helper_block_90
___destroy_helper_block_91
___35-[NDCallbackQueue performCallback:]_block_invoke97
___copy_helper_block_100
___destroy_helper_block_101
___35-[NDCallbackQueue performCallback:]_block_invoke103
___copy_helper_block_106
___destroy_helper_block_107
___35-[NDCallbackQueue performCallback:]_block_invoke112
___copy_helper_block_113
___destroy_helper_block_114
___35-[NDCallbackQueue performCallback:]_block_invoke118
___copy_helper_block_119
___destroy_helper_block_120
-[NDCallbackQueue addPendingCallbackToFront:]
-[NDCallbackQueue addPendingCallback:forceWakeup:]
-[NDCallbackQueue performAllCallbacks]
-[NDCallbackQueue count]
-[NDCallbackQueue delegate]
-[NDCallbackQueue setDelegate:]
-[NDCallbackQueue .cxx_destruct]
GCC_except_table0
GCC_except_table2
GCC_except_table3
GCC_except_table11
GCC_except_table12
GCC_except_table13
GCC_except_table16
GCC_except_table22
GCC_except_table25
GCC_except_table35
GCC_except_table36
___block_descriptor_tmp
___block_descriptor_tmp84
___block_descriptor_tmp92
___block_descriptor_tmp102
___block_descriptor_tmp109
___block_descriptor_tmp115
___block_descriptor_tmp121
_OBJC_CLASS_$_PendingCallback
_OBJC_METACLASS_$_PendingCallback
_OBJC_CLASS_$_NDCallbackQueue
_OBJC_METACLASS_$_NDCallbackQueue
_OBJC_IVAR_$_PendingCallback._type
_OBJC_IVAR_$_PendingCallback._taskIdentifier
_OBJC_IVAR_$_PendingCallback._args
_OBJC_IVAR_$_NDCallbackQueue._callbacks
_OBJC_IVAR_$_NDCallbackQueue._delegate
/SourceCache/nsnetworkd/CFNetwork-672.0.8/nsnetworkd/
NDTaskQueue.mm
/private/var/tmp/nsnetworkd/nsnetworkd-672.0.8~1/CFNetwork.build/nsnetworkd.build/Objects-normal/armv7/NDTaskQueue.o
-[NDPendingTask initWithTask:sessionID:bundleID:priority:]
-[NDPendingTask task]
/SourceCache/nsnetworkd/CFNetwork-672.0.8/nsnetworkd/NDTaskQueue.h
-[NDPendingTask sessionID]
-[NDPendingTask bundleID]
-[NDPendingTask priority]
-[NDPendingTask .cxx_destruct]
+[NDTaskQueue sharedTaskQueue]
___30+[NDTaskQueue sharedTaskQueue]_block_invoke
-[NDTaskQueue init]
___19-[NDTaskQueue init]_block_invoke
__ZL22__UnblockDuetDownloadsPv
-[NDTaskQueue addTask:inSession:forBundleID:withPriority:]
___58-[NDTaskQueue addTask:inSession:forBundleID:withPriority:]_block_invoke
___58-[NDTaskQueue addTask:inSession:forBundleID:withPriority:]_block_invoke_2
___58-[NDTaskQueue addTask:inSession:forBundleID:withPriority:]_block_invoke_3
___copy_helper_block_
___destroy_helper_block_
___copy_helper_block_116
___destroy_helper_block_117
-[NDTaskQueue suspendTask:inSession:forBundleID:]
___49-[NDTaskQueue suspendTask:inSession:forBundleID:]_block_invoke
___copy_helper_block_123
___destroy_helper_block_124
-[NDTaskQueue resumeTask:inSession:forBundleID:]
___48-[NDTaskQueue resumeTask:inSession:forBundleID:]_block_invoke
___copy_helper_block_134
___destroy_helper_block_135
-[NDTaskQueue taskCompleted:inSession:forBundleID:]
___51-[NDTaskQueue taskCompleted:inSession:forBundleID:]_block_invoke
___51-[NDTaskQueue taskCompleted:inSession:forBundleID:]_block_invoke_2
___copy_helper_block_145
___destroy_helper_block_146
___copy_helper_block_150
___destroy_helper_block_151
-[NDTaskQueue performDuetCheckForPendingTask:timeout:]
___54-[NDTaskQueue performDuetCheckForPendingTask:timeout:]_block_invoke
___copy_helper_block_172
___destroy_helper_block_173
-[NDTaskQueue downloadHandlerDidDisconnect:]
-[NDTaskQueue downloadHandler:handleSession:]
___45-[NDTaskQueue downloadHandler:handleSession:]_block_invoke
___45-[NDTaskQueue downloadHandler:handleSession:]_block_invoke_2
___45-[NDTaskQueue downloadHandler:handleSession:]_block_invoke_3
___copy_helper_block_207
___destroy_helper_block_208
___copy_helper_block_210
___destroy_helper_block_211
___copy_helper_block_213
___destroy_helper_block_214
-[NDTaskQueue downloadHandler:cancelSession:]
___45-[NDTaskQueue downloadHandler:cancelSession:]_block_invoke
___copy_helper_block_220
___destroy_helper_block_221
-[NDTaskQueue retryDuetBlockedDownloads]
-[NDTaskQueue disableDuetChecksForTask:inSession:forBundleID:]
___62-[NDTaskQueue disableDuetChecksForTask:inSession:forBundleID:]_block_invoke
___copy_helper_block_235
___destroy_helper_block_236
-[NDTaskQueue .cxx_destruct]
GCC_except_table0
GCC_except_table8
GCC_except_table9
GCC_except_table10
GCC_except_table12
GCC_except_table13
GCC_except_table20
GCC_except_table24
GCC_except_table28
GCC_except_table34
GCC_except_table35
GCC_except_table38
GCC_except_table40
GCC_except_table42
GCC_except_table50
GCC_except_table53
GCC_except_table55
___block_descriptor_tmp
___block_literal_global
___block_descriptor_tmp53
___block_literal_global54
___block_descriptor_tmp97
___block_literal_global98
___block_descriptor_tmp113
___block_descriptor_tmp118
___block_descriptor_tmp125
___block_descriptor_tmp136
___block_descriptor_tmp147
___block_descriptor_tmp152
___block_descriptor_tmp175
___block_descriptor_tmp209
___block_descriptor_tmp212
___block_descriptor_tmp215
___block_descriptor_tmp222
___block_descriptor_tmp237
_OBJC_CLASS_$_NDPendingTask
_OBJC_METACLASS_$_NDPendingTask
_OBJC_CLASS_$_NDTaskQueue
_OBJC_METACLASS_$_NDTaskQueue
_OBJC_IVAR_$_NDPendingTask._task
_OBJC_IVAR_$_NDPendingTask._sessionID
_OBJC_IVAR_$_NDPendingTask._bundleID
_OBJC_IVAR_$_NDPendingTask._priority
_OBJC_IVAR_$_NDTaskQueue._workQueue
_OBJC_IVAR_$_NDTaskQueue._downloadHandler
_OBJC_IVAR_$_NDTaskQueue._manager
_OBJC_IVAR_$_NDTaskQueue._bundleSessions
_OBJC_IVAR_$_NDTaskQueue._bundleDownloads
_OBJC_IVAR_$_NDTaskQueue._downloadsToPendingTasks
_OBJC_IVAR_$_NDTaskQueue._tasksBlockedOnDuet
__MergedGlobals
_main
-[NSString(nsnetworkd_Additions) _sha1Hash]
-[NSError(nsnetworkd_Additions) _isRecoverableErrorForBackgroundTaskWithStartTime:resourceTimeout:]
-[NSError(nsnetworkd_Additions) _errorShouldSuppressWake]
-[NSError(nsnetworkd_Additions) _cancelledReasonForError]
-[NDTaskMonitor setupTimeoutTimerWithTimeout:]
___46-[NDTaskMonitor setupTimeoutTimerWithTimeout:]_block_invoke
___copy_helper_block_
___destroy_helper_block_
-[NDTaskMonitor setThroughputTimerForCurrentInterval]
___53-[NDTaskMonitor setThroughputTimerForCurrentInterval]_block_invoke
___copy_helper_block_8
___destroy_helper_block_9
-[NDTaskMonitor setupThroughputTimer]
-[NDTaskMonitor initWithTask:timeout:]
-[NDTaskMonitor currentThroughputThreshold]
-[NDTaskMonitor currentIntervalEndDelta]
-[NDTaskMonitor calculateThroughput]
-[NDTaskMonitor taskTransferredData:]
-[NDTaskMonitor cancel]
-[NDTaskMonitor .cxx_destruct]
__Z5NDLog10NDLogLevelP8NSStringz
__Z18NDPowerlogLogEventP8NSStringS0_P16NSURLSessionTaskP10NDTaskInfo
__Z12NDADLogErrorP16NSURLSessionTask8TaskKindP7NSErrorh
__Z17NDADLogResumeDatadd
+[NDStatusMonitor sharedMonitor]
___32+[NDStatusMonitor sharedMonitor]_block_invoke
-[NDStatusMonitor init]
-[NDStatusMonitor dealloc]
-[NDStatusMonitor performBlockAfterNetworkChangedEvent:]
-[NDStatusMonitor handleDynamicStoreCallback:changedKeys:]
___58-[NDStatusMonitor handleDynamicStoreCallback:changedKeys:]_block_invoke
___copy_helper_block_
___destroy_helper_block_
-[NDStatusMonitor startMonitoringDynamicStore]
__ZL21_dynamicStoreCallbackPK16__SCDynamicStorePK9__CFArrayPv
-[NDStatusMonitor stopMonitoringDynamicStore]
-[NDStatusMonitor start]
-[NDStatusMonitor stop]
-[NDStatusMonitor .cxx_destruct]
___clang_call_terminate
-[DummyQueue initWithDispatchQueue:]
-[DummyQueue addOperationWithBlock:]
-[DummyQueue maxConcurrentOperationCount]
-[DummyQueue queue]
-[DummyQueue setQueue:]
-[DummyQueue .cxx_destruct]
-[NDBackgroundSession configurationWithClientConfiguration:forPriority:]
-[NDBackgroundSession initWithConfiguration:bundleID:downloadDirectory:clientProxy:delegate:]
-[NDBackgroundSession sessionForPriority:]
-[NDBackgroundSession setXPCConnection:]
___40-[NDBackgroundSession setXPCConnection:]_block_invoke
___copy_helper_block_
___destroy_helper_block_
___40-[NDBackgroundSession setXPCConnection:]_block_invoke142
___copy_helper_block_145
___destroy_helper_block_146
-[NDBackgroundSession applicationWasQuitFromAppSwitcher:]
___57-[NDBackgroundSession applicationWasQuitFromAppSwitcher:]_block_invoke
___copy_helper_block_162
___destroy_helper_block_163
-[NDBackgroundSession applicationBackgroundUpdatesTurnedOff:]
___61-[NDBackgroundSession applicationBackgroundUpdatesTurnedOff:]_block_invoke
___copy_helper_block_167
___destroy_helper_block_168
-[NDBackgroundSession applicationWasSuspended:]
___47-[NDBackgroundSession applicationWasSuspended:]_block_invoke
___copy_helper_block_172
___destroy_helper_block_173
-[NDBackgroundSession applicationNoLongerInForeground:]
___55-[NDBackgroundSession applicationNoLongerInForeground:]_block_invoke
___55-[NDBackgroundSession applicationNoLongerInForeground:]_block_invoke_2
___copy_helper_block_187
___destroy_helper_block_188
___copy_helper_block_196
___destroy_helper_block_197
-[NDBackgroundSession applicationEnteredForeground:]
___52-[NDBackgroundSession applicationEnteredForeground:]_block_invoke
___copy_helper_block_212
___destroy_helper_block_213
-[NDBackgroundSession clientApplicationWasReinstalled]
___54-[NDBackgroundSession clientApplicationWasReinstalled]_block_invoke
___copy_helper_block_237
___destroy_helper_block_238
-[NDBackgroundSession setupDownloadDirectory:]
-[NDBackgroundSession cleanupSession]
-[NDBackgroundSession obliterate]
___33-[NDBackgroundSession obliterate]_block_invoke
___copy_helper_block_271
___destroy_helper_block_272
-[NDBackgroundSession tasksArchivePath]
-[NDBackgroundSession archiveTaskInfo]
___38-[NDBackgroundSession archiveTaskInfo]_block_invoke
___copy_helper_block_278
___destroy_helper_block_279
-[NDBackgroundSession initializeTask:fromTaskInfo:]
-[NDBackgroundSession createNewTaskFromInfo:]
-[NDBackgroundSession restoreInProgressTask:]
-[NDBackgroundSession restoreCompletedTask:]
-[NDBackgroundSession restoreTask:isOutstanding:]
-[NDBackgroundSession restoreTasks]
-[NDBackgroundSession retryTask:originalError:]
___47-[NDBackgroundSession retryTask:originalError:]_block_invoke
___copy_helper_block_383
___destroy_helper_block_384
-[NDBackgroundSession removeDownloadFileForTaskInfo:]
-[NDBackgroundSession removeUploadFileForTask:]
-[NDBackgroundSession sessionHasOutstandingTasks]
-[NDBackgroundSession getClientProxy]
-[NDBackgroundSession errorOccurredDuringFinishedCallbackDelivery:]
-[NDBackgroundSession errorOccurredDuringAuthCallbackDelivery:completionHandler:]
-[NDBackgroundSession clientAcknowledgedTerminalCallbackForTask:]
-[NDBackgroundSession wakeUpClient]
-[NDBackgroundSession clientIsActive]
-[NDBackgroundSession notifyQueueOfTaskCompletion:identifier:taskInfo:suppressWake:]
-[NDBackgroundSession clientDidDisconnect]
-[NDBackgroundSession reconnectClient:withCompletion:]
___54-[NDBackgroundSession reconnectClient:withCompletion:]_block_invoke
___copy_helper_block_437
___destroy_helper_block_438
-[NDBackgroundSession allowReconnect]
-[NDBackgroundSession createClientTaskForTask:taskInfo:]
-[NDBackgroundSession getTasksForReconnection]
___46-[NDBackgroundSession getTasksForReconnection]_block_invoke
___copy_helper_block_460
___destroy_helper_block_461
-[NDBackgroundSession currentPriority]
-[NDBackgroundSession enqueueTask:withPriority:]
-[NDBackgroundSession downloadTaskWithResumeData:identifier:reply:]
-[NDBackgroundSession downloadTaskWithRequest:originalRequest:identifier:reply:]
-[NDBackgroundSession makeTempUploadFile:]
-[NDBackgroundSession uploadTaskWithRequest:originalRequest:fromFile:identifier:reply:]
-[NDBackgroundSession requeueTask:]
___35-[NDBackgroundSession requeueTask:]_block_invoke
___copy_helper_block_538
___destroy_helper_block_539
-[NDBackgroundSession cancelTaskWithIdentifier:byProducingResumeData:]
___70-[NDBackgroundSession cancelTaskWithIdentifier:byProducingResumeData:]_block_invoke
___copy_helper_block_543
___destroy_helper_block_544
-[NDBackgroundSession cancelTaskWithIdentifier:]
-[NDBackgroundSession suspendTaskWithIdentifier:]
-[NDBackgroundSession resumeTaskWithIdentifier:]
-[NDBackgroundSession setDescription:forTask:]
-[NDBackgroundSession resetStorageWithReply:]
-[NDBackgroundSession cancelMonitorForTask:]
-[NDBackgroundSession taskShouldResume:withTimeout:]
___52-[NDBackgroundSession taskShouldResume:withTimeout:]_block_invoke
___copy_helper_block_571
___destroy_helper_block_572
-[NDBackgroundSession taskShouldSuspend:]
___41-[NDBackgroundSession taskShouldSuspend:]_block_invoke
___copy_helper_block_579
___destroy_helper_block_580
-[NDBackgroundSession URLSession:didBecomeInvalidWithError:]
-[NDBackgroundSession URLSession:task:didReceiveChallenge:completionHandler:]
-[NDBackgroundSession URLSession:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:]
-[NDBackgroundSession URLSession:task:didCompleteWithError:]
-[NDBackgroundSession URLSession:dataTask:willCacheResponse:completionHandler:]
-[NDBackgroundSession URLSession:dataTask:didReceiveResponse:completionHandler:]
-[NDBackgroundSession URLSession:dataTask:didReceiveData:]
-[NDBackgroundSession URLSession:dataTask:didBecomeDownloadTask:]
-[NDBackgroundSession URLSession:downloadTask:didFinishDownloadingToURL:]
-[NDBackgroundSession URLSession:downloadTask:didResumeAtOffset:expectedTotalBytes:]
-[NDBackgroundSession URLSession:downloadTask:didWriteData:totalBytesWritten:totalBytesExpectedToWrite:]
-[NDBackgroundSession _URLSession:downloadTask:didReceiveResponse:]
-[NDBackgroundSession _URLSession:downloadTaskNeedsDownloadDirectory:]
-[NDBackgroundSession delegate]
-[NDBackgroundSession setDelegate:]
-[NDBackgroundSession identifier]
-[NDBackgroundSession .cxx_destruct]
-[NDCredentialStorage initWithDelegate:]
___40-[NDCredentialStorage initWithDelegate:]_block_invoke
___40-[NDCredentialStorage initWithDelegate:]_block_invoke_2
___40-[NDCredentialStorage initWithDelegate:]_block_invoke_3
___copy_helper_block_
___destroy_helper_block_
___copy_helper_block_8
___destroy_helper_block_9
___copy_helper_block_14
___destroy_helper_block_15
-[NDCredentialStorage credentialsForProtectionSpace:]
___53-[NDCredentialStorage credentialsForProtectionSpace:]_block_invoke
___copy_helper_block_17
___destroy_helper_block_18
___53-[NDCredentialStorage credentialsForProtectionSpace:]_block_invoke23
___53-[NDCredentialStorage credentialsForProtectionSpace:]_block_invoke_2
___copy_helper_block_28
___destroy_helper_block_29
___copy_helper_block_31
___destroy_helper_block_32
___Block_byref_object_copy_
___Block_byref_object_dispose_
___53-[NDCredentialStorage credentialsForProtectionSpace:]_block_invoke37
___copy_helper_block_40
___destroy_helper_block_41
-[NDCredentialStorage allCredentials]
___37-[NDCredentialStorage allCredentials]_block_invoke
___copy_helper_block_43
___destroy_helper_block_44
___37-[NDCredentialStorage allCredentials]_block_invoke46
___37-[NDCredentialStorage allCredentials]_block_invoke_2
___copy_helper_block_49
___destroy_helper_block_50
___copy_helper_block_52
___destroy_helper_block_53
___37-[NDCredentialStorage allCredentials]_block_invoke57
___copy_helper_block_59
___destroy_helper_block_60
-[NDCredentialStorage setCredential:forProtectionSpace:]
___56-[NDCredentialStorage setCredential:forProtectionSpace:]_block_invoke
___copy_helper_block_66
___destroy_helper_block_67
-[NDCredentialStorage removeCredential:forProtectionSpace:]
___59-[NDCredentialStorage removeCredential:forProtectionSpace:]_block_invoke
___copy_helper_block_71
___destroy_helper_block_72
-[NDCredentialStorage defaultCredentialForProtectionSpace:]
___59-[NDCredentialStorage defaultCredentialForProtectionSpace:]_block_invoke
___copy_helper_block_74
___destroy_helper_block_75
___59-[NDCredentialStorage defaultCredentialForProtectionSpace:]_block_invoke77
___59-[NDCredentialStorage defaultCredentialForProtectionSpace:]_block_invoke_2
___copy_helper_block_78
___destroy_helper_block_79
___copy_helper_block_81
___destroy_helper_block_82
___59-[NDCredentialStorage defaultCredentialForProtectionSpace:]_block_invoke87
___copy_helper_block_88
___destroy_helper_block_89
-[NDCredentialStorage setDefaultCredential:forProtectionSpace:]
___63-[NDCredentialStorage setDefaultCredential:forProtectionSpace:]_block_invoke
___copy_helper_block_93
___destroy_helper_block_94
-[NDCredentialStorage reset]
___28-[NDCredentialStorage reset]_block_invoke
___copy_helper_block_96
___destroy_helper_block_97
-[NDCredentialStorage delegate]
-[NDCredentialStorage setDelegate:]
-[NDCredentialStorage .cxx_destruct]
-[NDTaskInfo initWithTask:bundleID:sessionID:]
-[NDTaskInfo initWithUploadTask:bundleID:sessionID:]
-[NDTaskInfo initWithDownloadTask:bundleID:sessionID:]
-[NDTaskInfo encodeWithCoder:]
-[NDTaskInfo initWithCoder:]
+[NDTaskInfo supportsSecureCoding]
-[NDTaskInfo identifier]
-[NDTaskInfo setIdentifier:]
-[NDTaskInfo taskKind]
-[NDTaskInfo setTaskKind:]
-[NDTaskInfo taskPriority]
-[NDTaskInfo setTaskPriority:]
-[NDTaskInfo creationTime]
-[NDTaskInfo setCreationTime:]
-[NDTaskInfo state]
-[NDTaskInfo setState:]
-[NDTaskInfo suspendCount]
-[NDTaskInfo setSuspendCount:]
-[NDTaskInfo taskDescription]
-[NDTaskInfo setTaskDescription:]
-[NDTaskInfo originalRequest]
-[NDTaskInfo setOriginalRequest:]
-[NDTaskInfo currentRequest]
-[NDTaskInfo setCurrentRequest:]
-[NDTaskInfo response]
-[NDTaskInfo setResponse:]
-[NDTaskInfo error]
-[NDTaskInfo setError:]
-[NDTaskInfo fileURL]
-[NDTaskInfo setFileURL:]
-[NDTaskInfo downloadFileURL]
-[NDTaskInfo setDownloadFileURL:]
-[NDTaskInfo bundleID]
-[NDTaskInfo setBundleID:]
-[NDTaskInfo sessionID]
-[NDTaskInfo setSessionID:]
-[NDTaskInfo hasStarted]
-[NDTaskInfo setHasStarted:]
-[NDTaskInfo uniqueIdentifier]
-[NDTaskInfo setUniqueIdentifier:]
-[NDTaskInfo .cxx_destruct]
+[Daemon sharedDaemon]
___22+[Daemon sharedDaemon]_block_invoke
+[Daemon nsnetworkdPath]
+[Daemon bundleManagerPath:]
+[Daemon sessionPath:forBundleID:]
-[Daemon createDaemonDirectory]
-[Daemon init]
-[Daemon archivePath]
-[Daemon applicationIsInstalled:]
-[Daemon restoreState]
___22-[Daemon restoreState]_block_invoke
-[Daemon archiveState]
___22-[Daemon archiveState]_block_invoke
___copy_helper_block_
___destroy_helper_block_
-[Daemon listener:shouldAcceptNewConnection:]
-[Daemon getSessionWithIdentifier:forBundleID:]
___Block_byref_object_copy_
___Block_byref_object_dispose_
___47-[Daemon getSessionWithIdentifier:forBundleID:]_block_invoke
___copy_helper_block_250
___destroy_helper_block_251
-[Daemon managerBecameEmpty:bundleID:]
___38-[Daemon managerBecameEmpty:bundleID:]_block_invoke
___copy_helper_block_257
___destroy_helper_block_258
-[Daemon addTransaction]
-[Daemon releaseTransaction]
-[Daemon applicationsDidInstall:]
___33-[Daemon applicationsDidInstall:]_block_invoke
___copy_helper_block_271
___destroy_helper_block_272
-[Daemon applicationsDidUninstall:]
___35-[Daemon applicationsDidUninstall:]_block_invoke
___copy_helper_block_278
___destroy_helper_block_279
-[Daemon start]
___15-[Daemon start]_block_invoke
___copy_helper_block_284
___destroy_helper_block_285
-[Daemon queue]
-[Daemon .cxx_destruct]
+[NDSpringBoard sharedSpringBoard]
___34+[NDSpringBoard sharedSpringBoard]_block_invoke
-[NDSpringBoard init]
__ZL30handleBackgroundSettingsChangeP22__CFNotificationCenterPvPK10__CFStringPKvPK14__CFDictionary
-[NDSpringBoard dealloc]
-[NDSpringBoard setupMonitor]
___29-[NDSpringBoard setupMonitor]_block_invoke
-[NDSpringBoard handleAppSwitcherQuitAppNotification:]
___54-[NDSpringBoard handleAppSwitcherQuitAppNotification:]_block_invoke
___copy_helper_block_
___destroy_helper_block_
-[NDSpringBoard getBackgroundSettingsAppList]
-[NDSpringBoard handleBackgroundSettingsChange]
___47-[NDSpringBoard handleBackgroundSettingsChange]_block_invoke
___47-[NDSpringBoard handleBackgroundSettingsChange]_block_invoke_2
___copy_helper_block_87
___destroy_helper_block_88
___47-[NDSpringBoard handleBackgroundSettingsChange]_block_invoke95
___copy_helper_block_98
___destroy_helper_block_99
-[NDSpringBoard handleApplicationStateChange:]
___46-[NDSpringBoard handleApplicationStateChange:]_block_invoke
___copy_helper_block_121
___destroy_helper_block_122
-[NDSpringBoard addObserver:forApplication:]
___44-[NDSpringBoard addObserver:forApplication:]_block_invoke
___copy_helper_block_129
___destroy_helper_block_130
-[NDSpringBoard removeObserver:forApplication:]
___47-[NDSpringBoard removeObserver:forApplication:]_block_invoke
___copy_helper_block_134
___destroy_helper_block_135
-[NDSpringBoard startMonitoringBundleID:]
___41-[NDSpringBoard startMonitoringBundleID:]_block_invoke
___copy_helper_block_141
___destroy_helper_block_142
-[NDSpringBoard stopMonitoringBundleID:]
___40-[NDSpringBoard stopMonitoringBundleID:]_block_invoke
___copy_helper_block_146
___destroy_helper_block_147
-[NDSpringBoard applicationStateForBundleID:]
___45-[NDSpringBoard applicationStateForBundleID:]_block_invoke
___copy_helper_block_149
___destroy_helper_block_150
-[NDSpringBoard applicationIsForeground:]
-[NDSpringBoard applicationIsAwake:]
-[NDSpringBoard applicationIsSuspended:]
-[NDSpringBoard applicationIsBeingDebugged:]
-[NDSpringBoard applicationHasBackgroundTaskCompletion:]
___56-[NDSpringBoard applicationHasBackgroundTaskCompletion:]_block_invoke
___copy_helper_block_156
___destroy_helper_block_157
-[NDSpringBoard bundleIdentifierForProcess:]
-[NDSpringBoard _onqueue_releaseAssertionForBundleID:sessionID:]
-[NDSpringBoard releaseAssertionForBundleID:sessionID:]
___55-[NDSpringBoard releaseAssertionForBundleID:sessionID:]_block_invoke
___copy_helper_block_171
___destroy_helper_block_172
-[NDSpringBoard takeAssertionForBundleID:sessionID:]
___52-[NDSpringBoard takeAssertionForBundleID:sessionID:]_block_invoke
___copy_helper_block_177
___destroy_helper_block_178
-[NDSpringBoard internalWakeUpApp:forSession:]
-[NDSpringBoard application:hasPendingWakeRequestForSession:]
___61-[NDSpringBoard application:hasPendingWakeRequestForSession:]_block_invoke
___copy_helper_block_200
___destroy_helper_block_201
-[NDSpringBoard wakeUpApp:forSession:]
___38-[NDSpringBoard wakeUpApp:forSession:]_block_invoke
___38-[NDSpringBoard wakeUpApp:forSession:]_block_invoke_2
___copy_helper_block_221
___destroy_helper_block_222
___copy_helper_block_226
___destroy_helper_block_227
-[NDSpringBoard .cxx_destruct]
-[NDSessionManager initWithDelegate:bundleID:]
-[NDSessionManager archivePath]
-[NDSessionManager downloadDirectoryDataPath]
-[NDSessionManager restoreState]
-[NDSessionManager archiveState]
___32-[NDSessionManager archiveState]_block_invoke
___copy_helper_block_
___destroy_helper_block_
-[NDSessionManager boost:]
___26-[NDSessionManager boost:]_block_invoke
___copy_helper_block_79
___destroy_helper_block_80
-[NDSessionManager dropBoost]
___29-[NDSessionManager dropBoost]_block_invoke
___copy_helper_block_84
___destroy_helper_block_85
-[NDSessionManager createSessionWithConfiguration:clientProxy:cachesDirectory:reply:]
-[NDSessionManager sendPendingCallbacksForIdentifier:reply:]
___60-[NDSessionManager sendPendingCallbacksForIdentifier:reply:]_block_invoke
___60-[NDSessionManager sendPendingCallbacksForIdentifier:reply:]_block_invoke_2
___copy_helper_block_104
___destroy_helper_block_105
___copy_helper_block_113
___destroy_helper_block_114
-[NDSessionManager releaseAssertionForSession:reply:]
-[NDSessionManager okayToSendPendingCallbacksForIdentifier:reply:]
___66-[NDSessionManager okayToSendPendingCallbacksForIdentifier:reply:]_block_invoke
___copy_helper_block_126
___destroy_helper_block_127
-[NDSessionManager clientDisconnected]
-[NDSessionManager cleanup]
-[NDSessionManager sessionCompleted:]
___37-[NDSessionManager sessionCompleted:]_block_invoke
___copy_helper_block_139
___destroy_helper_block_140
-[NDSessionManager getSessionWithIdentifier:]
-[NDSessionManager clientApplicationWasReinstalled]
___51-[NDSessionManager clientApplicationWasReinstalled]_block_invoke
___51-[NDSessionManager clientApplicationWasReinstalled]_block_invoke_2
___copy_helper_block_148
___destroy_helper_block_149
-[NDSessionManager obliterate]
___30-[NDSessionManager obliterate]_block_invoke
___30-[NDSessionManager obliterate]_block_invoke_2
___copy_helper_block_157
___destroy_helper_block_158
-[NDSessionManager xpcConn]
-[NDSessionManager setXpcConn:]
-[NDSessionManager delegate]
-[NDSessionManager setDelegate:]
-[NDSessionManager .cxx_destruct]
-[PendingCallback initWithCallbackType:taskIdentifier:args:]
+[PendingCallback supportsSecureCoding]
-[PendingCallback encodeWithCoder:]
-[PendingCallback initWithCoder:]
-[PendingCallback type]
-[PendingCallback setType:]
-[PendingCallback taskIdentifier]
-[PendingCallback setTaskIdentifier:]
-[PendingCallback args]
-[PendingCallback setArgs:]
-[PendingCallback .cxx_destruct]
-[NDCallbackQueue initWithDelegate:]
-[NDCallbackQueue performCallback:]
___35-[NDCallbackQueue performCallback:]_block_invoke
___copy_helper_block_
___destroy_helper_block_
___35-[NDCallbackQueue performCallback:]_block_invoke74
___copy_helper_block_81
___destroy_helper_block_82
___35-[NDCallbackQueue performCallback:]_block_invoke87
___copy_helper_block_90
___destroy_helper_block_91
___35-[NDCallbackQueue performCallback:]_block_invoke97
___copy_helper_block_100
___destroy_helper_block_101
___35-[NDCallbackQueue performCallback:]_block_invoke103
___copy_helper_block_106
___destroy_helper_block_107
___35-[NDCallbackQueue performCallback:]_block_invoke112
___copy_helper_block_113
___destroy_helper_block_114
___35-[NDCallbackQueue performCallback:]_block_invoke118
___copy_helper_block_119
___destroy_helper_block_120
-[NDCallbackQueue addPendingCallbackToFront:]
-[NDCallbackQueue addPendingCallback:forceWakeup:]
-[NDCallbackQueue performAllCallbacks]
-[NDCallbackQueue count]
-[NDCallbackQueue delegate]
-[NDCallbackQueue setDelegate:]
-[NDCallbackQueue .cxx_destruct]
-[NDPendingTask initWithTask:sessionID:bundleID:priority:]
-[NDPendingTask task]
-[NDPendingTask sessionID]
-[NDPendingTask bundleID]
-[NDPendingTask priority]
-[NDPendingTask .cxx_destruct]
+[NDTaskQueue sharedTaskQueue]
___30+[NDTaskQueue sharedTaskQueue]_block_invoke
-[NDTaskQueue init]
___19-[NDTaskQueue init]_block_invoke
__ZL22__UnblockDuetDownloadsPv
-[NDTaskQueue addTask:inSession:forBundleID:withPriority:]
___58-[NDTaskQueue addTask:inSession:forBundleID:withPriority:]_block_invoke
___58-[NDTaskQueue addTask:inSession:forBundleID:withPriority:]_block_invoke_2
___58-[NDTaskQueue addTask:inSession:forBundleID:withPriority:]_block_invoke_3
___copy_helper_block_
___destroy_helper_block_
___copy_helper_block_116
___destroy_helper_block_117
-[NDTaskQueue suspendTask:inSession:forBundleID:]
___49-[NDTaskQueue suspendTask:inSession:forBundleID:]_block_invoke
___copy_helper_block_123
___destroy_helper_block_124
-[NDTaskQueue resumeTask:inSession:forBundleID:]
___48-[NDTaskQueue resumeTask:inSession:forBundleID:]_block_invoke
___copy_helper_block_134
___destroy_helper_block_135
-[NDTaskQueue taskCompleted:inSession:forBundleID:]
___51-[NDTaskQueue taskCompleted:inSession:forBundleID:]_block_invoke
___51-[NDTaskQueue taskCompleted:inSession:forBundleID:]_block_invoke_2
___copy_helper_block_145
___destroy_helper_block_146
___copy_helper_block_150
___destroy_helper_block_151
-[NDTaskQueue performDuetCheckForPendingTask:timeout:]
___54-[NDTaskQueue performDuetCheckForPendingTask:timeout:]_block_invoke
___copy_helper_block_172
___destroy_helper_block_173
-[NDTaskQueue downloadHandlerDidDisconnect:]
-[NDTaskQueue downloadHandler:handleSession:]
___45-[NDTaskQueue downloadHandler:handleSession:]_block_invoke
___45-[NDTaskQueue downloadHandler:handleSession:]_block_invoke_2
___45-[NDTaskQueue downloadHandler:handleSession:]_block_invoke_3
___copy_helper_block_207
___destroy_helper_block_208
___copy_helper_block_210
___destroy_helper_block_211
___copy_helper_block_213
___destroy_helper_block_214
-[NDTaskQueue downloadHandler:cancelSession:]
___45-[NDTaskQueue downloadHandler:cancelSession:]_block_invoke
___copy_helper_block_220
___destroy_helper_block_221
-[NDTaskQueue retryDuetBlockedDownloads]
-[NDTaskQueue disableDuetChecksForTask:inSession:forBundleID:]
___62-[NDTaskQueue disableDuetChecksForTask:inSession:forBundleID:]_block_invoke
___copy_helper_block_235
___destroy_helper_block_236
-[NDTaskQueue .cxx_destruct]
_objc_retain$shim
_objc_release$shim
_objc_msgSend$shim
_dispatch_resume$shim
_dispatch_source_cancel$shim
_objc_storeStrong$shim
_ADClientPushValueForDistributionKey$shim
_objc_retainAutoreleaseReturnValue$shim
_dispatch_async$shim
_objc_getProperty$shim
_objc_setProperty_atomic$shim
_objc_autoreleaseReturnValue$shim
_dispatch_semaphore_signal$shim
__Block_object_assign$shim
_objc_storeWeak$shim
__Block_object_dispose$shim
_objc_setProperty_atomic_copy$shim
 stub helpers
GCC_except_table0
GCC_except_table0
GCC_except_table1
GCC_except_table2
GCC_except_table3
GCC_except_table1
GCC_except_table4
GCC_except_table9
GCC_except_table12
GCC_except_table13
GCC_except_table0
GCC_except_table1
GCC_except_table2
GCC_except_table2
GCC_except_table3
GCC_except_table5
GCC_except_table7
GCC_except_table0
GCC_except_table6
GCC_except_table7
GCC_except_table9
GCC_except_table17
GCC_except_table21
GCC_except_table29
GCC_except_table36
GCC_except_table40
GCC_except_table43
GCC_except_table44
GCC_except_table46
GCC_except_table49
GCC_except_table50
GCC_except_table54
GCC_except_table55
GCC_except_table56
GCC_except_table57
GCC_except_table58
GCC_except_table59
GCC_except_table60
GCC_except_table64
GCC_except_table65
GCC_except_table69
GCC_except_table70
GCC_except_table71
GCC_except_table72
GCC_except_table73
GCC_except_table74
GCC_except_table80
GCC_except_table81
GCC_except_table82
GCC_except_table85
GCC_except_table86
GCC_except_table87
GCC_except_table88
GCC_except_table89
GCC_except_table90
GCC_except_table92
GCC_except_table95
GCC_except_table96
GCC_except_table99
GCC_except_table100
GCC_except_table101
GCC_except_table102
GCC_except_table103
GCC_except_table104
GCC_except_table106
GCC_except_table110
GCC_except_table113
GCC_except_table114
GCC_except_table115
GCC_except_table116
GCC_except_table118
GCC_except_table119
GCC_except_table120
GCC_except_table121
GCC_except_table122
GCC_except_table123
GCC_except_table124
GCC_except_table0
GCC_except_table1
GCC_except_table10
GCC_except_table15
GCC_except_table25
GCC_except_table38
GCC_except_table39
GCC_except_table42
GCC_except_table43
GCC_except_table46
GCC_except_table51
GCC_except_table56
GCC_except_table59
GCC_except_table60
GCC_except_table0
GCC_except_table1
GCC_except_table2
GCC_except_table3
GCC_except_table4
GCC_except_table2
GCC_except_table3
GCC_except_table4
GCC_except_table5
GCC_except_table6
GCC_except_table7
GCC_except_table9
GCC_except_table10
GCC_except_table11
GCC_except_table15
GCC_except_table19
GCC_except_table23
GCC_except_table29
GCC_except_table33
GCC_except_table36
GCC_except_table2
GCC_except_table4
GCC_except_table6
GCC_except_table7
GCC_except_table9
GCC_except_table12
GCC_except_table14
GCC_except_table15
GCC_except_table18
GCC_except_table22
GCC_except_table26
GCC_except_table30
GCC_except_table34
GCC_except_table38
GCC_except_table42
GCC_except_table49
GCC_except_table50
GCC_except_table54
GCC_except_table59
GCC_except_table63
GCC_except_table64
GCC_except_table69
GCC_except_table70
GCC_except_table0
GCC_except_table1
GCC_except_table2
GCC_except_table3
GCC_except_table4
GCC_except_table9
GCC_except_table13
GCC_except_table16
GCC_except_table17
GCC_except_table18
GCC_except_table24
GCC_except_table25
GCC_except_table26
GCC_except_table30
GCC_except_table31
GCC_except_table32
GCC_except_table0
GCC_except_table2
GCC_except_table3
GCC_except_table11
GCC_except_table12
GCC_except_table13
GCC_except_table16
GCC_except_table22
GCC_except_table25
GCC_except_table35
GCC_except_table36
GCC_except_table0
GCC_except_table8
GCC_except_table9
GCC_except_table10
GCC_except_table12
GCC_except_table13
GCC_except_table20
GCC_except_table24
GCC_except_table28
GCC_except_table34
GCC_except_table35
GCC_except_table38
GCC_except_table40
GCC_except_table42
GCC_except_table50
GCC_except_table53
GCC_except_table55
__ZL25kNDThroughputKBThresholds
__ZL31kNDThroughputIntervalEndMinutes
___block_descriptor_tmp
___block_descriptor_tmp10
___block_descriptor_tmp
___block_literal_global
___block_descriptor_tmp22
___block_descriptor_tmp
___block_descriptor_tmp147
___block_descriptor_tmp164
___block_descriptor_tmp169
___block_descriptor_tmp174
___block_descriptor_tmp190
___block_descriptor_tmp198
___block_descriptor_tmp214
___block_descriptor_tmp239
___block_descriptor_tmp273
___block_descriptor_tmp280
___block_descriptor_tmp385
___block_descriptor_tmp439
___block_descriptor_tmp463
___block_descriptor_tmp540
___block_descriptor_tmp546
___block_descriptor_tmp574
___block_descriptor_tmp581
___block_descriptor_tmp
___block_descriptor_tmp11
___block_descriptor_tmp16
___block_descriptor_tmp20
___block_descriptor_tmp30
___block_descriptor_tmp34
___block_descriptor_tmp42
___block_descriptor_tmp45
___block_descriptor_tmp51
___block_descriptor_tmp54
___block_descriptor_tmp61
___block_descriptor_tmp68
___block_descriptor_tmp73
___block_descriptor_tmp76
___block_descriptor_tmp80
___block_descriptor_tmp84
___block_descriptor_tmp90
___block_descriptor_tmp95
___block_descriptor_tmp98
___block_descriptor_tmp
___block_literal_global
___block_descriptor_tmp82
___block_literal_global83
___block_descriptor_tmp108
___block_descriptor_tmp252
___block_descriptor_tmp259
___block_descriptor_tmp273
___block_descriptor_tmp280
___block_descriptor_tmp287
___block_descriptor_tmp
___block_literal_global
___block_descriptor_tmp44
___block_literal_global45
___block_descriptor_tmp58
___block_descriptor_tmp90
___block_descriptor_tmp96
___block_literal_global97
___block_descriptor_tmp100
___block_descriptor_tmp123
___block_descriptor_tmp131
___block_descriptor_tmp136
___block_descriptor_tmp143
___block_descriptor_tmp148
___block_descriptor_tmp151
___block_descriptor_tmp158
___block_descriptor_tmp173
___block_descriptor_tmp180
___block_descriptor_tmp202
___block_descriptor_tmp223
___block_descriptor_tmp228
___block_descriptor_tmp
___block_descriptor_tmp81
___block_descriptor_tmp86
___block_descriptor_tmp106
___block_descriptor_tmp115
___block_descriptor_tmp128
___block_descriptor_tmp141
___block_descriptor_tmp145
___block_literal_global
___block_descriptor_tmp150
___block_descriptor_tmp155
___block_literal_global156
___block_descriptor_tmp159
___block_descriptor_tmp
___block_descriptor_tmp84
___block_descriptor_tmp92
___block_descriptor_tmp102
___block_descriptor_tmp109
___block_descriptor_tmp115
___block_descriptor_tmp121
___block_descriptor_tmp
___block_literal_global
___block_descriptor_tmp53
___block_literal_global54
___block_descriptor_tmp97
___block_literal_global98
___block_descriptor_tmp113
___block_descriptor_tmp118
___block_descriptor_tmp125
___block_descriptor_tmp136
___block_descriptor_tmp147
___block_descriptor_tmp152
___block_descriptor_tmp175
___block_descriptor_tmp209
___block_descriptor_tmp212
___block_descriptor_tmp215
___block_descriptor_tmp222
___block_descriptor_tmp237
_OBJC_CLASS_$_NDTaskMonitor
_OBJC_METACLASS_$_NDTaskMonitor
_OBJC_CLASS_$_NDStatusMonitor
_OBJC_METACLASS_$_NDStatusMonitor
_OBJC_CLASS_$_DummyQueue
_OBJC_METACLASS_$_DummyQueue
_OBJC_CLASS_$_NDBackgroundSession
_OBJC_METACLASS_$_NDBackgroundSession
_OBJC_CLASS_$_NDCredentialStorage
_OBJC_METACLASS_$_NDCredentialStorage
_OBJC_CLASS_$_NDTaskInfo
_OBJC_METACLASS_$_NDTaskInfo
_OBJC_CLASS_$_Daemon
_OBJC_METACLASS_$_Daemon
_OBJC_CLASS_$_NDSpringBoard
_OBJC_METACLASS_$_NDSpringBoard
_OBJC_CLASS_$_NDSessionManager
_OBJC_METACLASS_$_NDSessionManager
_OBJC_CLASS_$_PendingCallback
_OBJC_METACLASS_$_PendingCallback
_OBJC_CLASS_$_NDCallbackQueue
_OBJC_METACLASS_$_NDCallbackQueue
_OBJC_CLASS_$_NDPendingTask
_OBJC_METACLASS_$_NDPendingTask
_OBJC_CLASS_$_NDTaskQueue
_OBJC_METACLASS_$_NDTaskQueue
_OBJC_IVAR_$_NDTaskMonitor._queue
_OBJC_IVAR_$_NDTaskMonitor._timeoutTimer
_OBJC_IVAR_$_NDTaskMonitor._task
_OBJC_IVAR_$_NDTaskMonitor._throughputTimer
_OBJC_IVAR_$_NDTaskMonitor._throughputInterval
_OBJC_IVAR_$_NDTaskMonitor._progressTimestamps
_OBJC_IVAR_$_NDTaskMonitor._progressValues
_OBJC_IVAR_$_NDStatusMonitor._dynamicStoreSource
_OBJC_IVAR_$_NDStatusMonitor._blocksToExecuteAftetNetworkChange
_OBJC_IVAR_$_NDStatusMonitor._networkChangeEventCount
_OBJC_IVAR_$_NDStatusMonitor._queue
_OBJC_IVAR_$_DummyQueue._queue
_OBJC_IVAR_$_NDBackgroundSession._credentialStorage
_OBJC_IVAR_$_NDBackgroundSession._clientBundleID
_OBJC_IVAR_$_NDBackgroundSession._identifier
_OBJC_IVAR_$_NDBackgroundSession._sessionDirectory
_OBJC_IVAR_$_NDBackgroundSession._downloadDirectory
_OBJC_IVAR_$_NDBackgroundSession._workQueue
_OBJC_IVAR_$_NDBackgroundSession._archiveQueue
_OBJC_IVAR_$_NDBackgroundSession._clientProxy
_OBJC_IVAR_$_NDBackgroundSession._discretionary
_OBJC_IVAR_$_NDBackgroundSession._sendsLaunchEvents
_OBJC_IVAR_$_NDBackgroundSession._userInitiatedSession
_OBJC_IVAR_$_NDBackgroundSession._discretionaryPrioritySession
_OBJC_IVAR_$_NDBackgroundSession._callbackQueue
_OBJC_IVAR_$_NDBackgroundSession._tasksToIdentifiers
_OBJC_IVAR_$_NDBackgroundSession._identifiersToTasks
_OBJC_IVAR_$_NDBackgroundSession._identifiersToTaskInfo
_OBJC_IVAR_$_NDBackgroundSession._identifiersToMonitors
_OBJC_IVAR_$_NDBackgroundSession._outstandingTaskIDs
_OBJC_IVAR_$_NDBackgroundSession._obliterated
_OBJC_IVAR_$_NDBackgroundSession._cleanedUp
_OBJC_IVAR_$_NDBackgroundSession._delayPendingEventsUntilReady
_OBJC_IVAR_$_NDBackgroundSession._readyForPendingEventsSem
_OBJC_IVAR_$_NDBackgroundSession._clientPID
_OBJC_IVAR_$_NDBackgroundSession._xpcConn
_OBJC_IVAR_$_NDBackgroundSession._delegate
_OBJC_IVAR_$_NDCredentialStorage._delegate
_OBJC_IVAR_$_NDCredentialStorage._cachedCredentials
_OBJC_IVAR_$_NDCredentialStorage._cachedDefaultCredentialUsers
_OBJC_IVAR_$_NDCredentialStorage._queue
_OBJC_IVAR_$_NDTaskInfo._identifier
_OBJC_IVAR_$_NDTaskInfo._state
_OBJC_IVAR_$_NDTaskInfo._taskDescription
_OBJC_IVAR_$_NDTaskInfo._originalRequest
_OBJC_IVAR_$_NDTaskInfo._currentRequest
_OBJC_IVAR_$_NDTaskInfo._response
_OBJC_IVAR_$_NDTaskInfo._error
_OBJC_IVAR_$_NDTaskInfo._bundleID
_OBJC_IVAR_$_NDTaskInfo._sessionID
_OBJC_IVAR_$_NDTaskInfo._hasStarted
_OBJC_IVAR_$_NDTaskInfo._uniqueIdentifier
_OBJC_IVAR_$_NDTaskInfo._taskKind
_OBJC_IVAR_$_NDTaskInfo._taskPriority
_OBJC_IVAR_$_NDTaskInfo._creationTime
_OBJC_IVAR_$_NDTaskInfo._suspendCount
_OBJC_IVAR_$_NDTaskInfo._fileURL
_OBJC_IVAR_$_NDTaskInfo._downloadFileURL
_OBJC_IVAR_$_Daemon._clients
_OBJC_IVAR_$_Daemon._queue
_OBJC_IVAR_$_NDSpringBoard._monitor
_OBJC_IVAR_$_NDSpringBoard._service
_OBJC_IVAR_$_NDSpringBoard._assertions
_OBJC_IVAR_$_NDSpringBoard._wakeDelays
_OBJC_IVAR_$_NDSpringBoard._nextWakeTimes
_OBJC_IVAR_$_NDSpringBoard._pendingWakes
_OBJC_IVAR_$_NDSpringBoard._observers
_OBJC_IVAR_$_NDSpringBoard._appStates
_OBJC_IVAR_$_NDSpringBoard._backgroundUpdatesAllowed
_OBJC_IVAR_$_NDSpringBoard._observedBackgroundSettings
_OBJC_IVAR_$_NDSpringBoard._monitoredBundleIDs
_OBJC_IVAR_$_NDSpringBoard._queue
_OBJC_IVAR_$_NDSessionManager._delegate
_OBJC_IVAR_$_NDSessionManager._clientBundleID
_OBJC_IVAR_$_NDSessionManager._sessions
_OBJC_IVAR_$_NDSessionManager._reconnectingProxies
_OBJC_IVAR_$_NDSessionManager._bundleDirectory
_OBJC_IVAR_$_NDSessionManager._queue
_OBJC_IVAR_$_NDSessionManager._boostReply
_OBJC_IVAR_$_NDSessionManager._xpcConn
_OBJC_IVAR_$_PendingCallback._type
_OBJC_IVAR_$_PendingCallback._taskIdentifier
_OBJC_IVAR_$_PendingCallback._args
_OBJC_IVAR_$_NDCallbackQueue._callbacks
_OBJC_IVAR_$_NDCallbackQueue._delegate
_OBJC_IVAR_$_NDPendingTask._task
_OBJC_IVAR_$_NDPendingTask._sessionID
_OBJC_IVAR_$_NDPendingTask._bundleID
_OBJC_IVAR_$_NDPendingTask._priority
_OBJC_IVAR_$_NDTaskQueue._workQueue
_OBJC_IVAR_$_NDTaskQueue._downloadHandler
_OBJC_IVAR_$_NDTaskQueue._manager
_OBJC_IVAR_$_NDTaskQueue._bundleSessions
_OBJC_IVAR_$_NDTaskQueue._bundleDownloads
_OBJC_IVAR_$_NDTaskQueue._downloadsToPendingTasks
_OBJC_IVAR_$_NDTaskQueue._tasksBlockedOnDuet
__MergedGlobals
__MergedGlobals
__MergedGlobals
__MergedGlobals
__mh_execute_header
_ADClientAddValueForScalarKey
_ADClientPushValueForDistributionKey
_BKSApplicationStateDisplayIDKey
_BKSApplicationStateKey
_BKSApplicationStateRunningReasonAssertionReasonKey
_BKSApplicationStateRunningReasonsKey
_CC_SHA1
_CFAbsoluteTimeGetCurrent
_CFArrayAppendValue
_CFArrayCreateMutable
_CFLog
_CFNotificationCenterAddObserver
_CFNotificationCenterGetDarwinNotifyCenter
_CFNotificationCenterRemoveEveryObserver
_CFPreferencesGetAppBooleanValue
_CFRelease
_CFRunLoopAddSource
_CFRunLoopGetMain
_CFRunLoopSourceInvalidate
_CFStringCreateWithFormat
_DuetNetworkClientOkToInitiateDiscretionaryTransfer
_DuetNetworkClientOkToInitiateNonDiscretionaryTransfer
_DuetNetworkClientRegisterInitiationCallback
_MKBDeviceUnlockedSinceBoot
_NSFileProtectionCompleteUntilFirstUserAuthentication
_NSFileProtectionKey
_NSSearchPathForDirectoriesInDomains
_NSURLErrorDomain
_NSURLSessionDownloadTaskResumeData
_OBJC_CLASS_$_BKSApplicationStateMonitor
_OBJC_CLASS_$_BKSProcessAssertion
_OBJC_CLASS_$_BKSSystemService
_OBJC_CLASS_$_LSApplicationProxy
_OBJC_CLASS_$_LSApplicationWorkspace
_OBJC_CLASS_$_MCProfileConnection
_OBJC_CLASS_$_NSArray
_OBJC_CLASS_$_NSDate
_OBJC_CLASS_$_NSDictionary
_OBJC_CLASS_$_NSDistributedNotificationCenter
_OBJC_CLASS_$_NSError
_OBJC_CLASS_$_NSFileManager
_OBJC_CLASS_$_NSKeyedArchiver
_OBJC_CLASS_$_NSKeyedUnarchiver
_OBJC_CLASS_$_NSMutableArray
_OBJC_CLASS_$_NSMutableDictionary
_OBJC_CLASS_$_NSMutableSet
_OBJC_CLASS_$_NSMutableString
_OBJC_CLASS_$_NSNumber
_OBJC_CLASS_$_NSObject
_OBJC_CLASS_$_NSPropertyListSerialization
_OBJC_CLASS_$_NSRunLoop
_OBJC_CLASS_$_NSSet
_OBJC_CLASS_$_NSString
_OBJC_CLASS_$_NSURL
_OBJC_CLASS_$_NSURLCredential
_OBJC_CLASS_$_NSURLCredentialStorage
_OBJC_CLASS_$_NSURLProtectionSpace
_OBJC_CLASS_$_NSURLRequest
_OBJC_CLASS_$_NSURLResponse
_OBJC_CLASS_$_NSURLSession
_OBJC_CLASS_$_NSURLSessionConfiguration
_OBJC_CLASS_$_NSURLSessionTask
_OBJC_CLASS_$_NSUUID
_OBJC_CLASS_$_NSUserDefaults
_OBJC_CLASS_$_NSXPCConnection
_OBJC_CLASS_$_NSXPCInterface
_OBJC_CLASS_$_NSXPCListener
_OBJC_CLASS_$_SSDownload
_OBJC_CLASS_$_SSDownloadAsset
_OBJC_CLASS_$_SSDownloadHandler
_OBJC_CLASS_$_SSDownloadManager
_OBJC_CLASS_$_SSDownloadManagerOptions
_OBJC_CLASS_$_SSDownloadPolicy
_OBJC_CLASS_$_SSDownloadPolicyRule
_OBJC_METACLASS_$_NSObject
_OBJC_METACLASS_$_NSURLCredentialStorage
_PLLogRegisteredEvent
_PLShouldLogRegisteredEvent
_SBSAppSwitcherQuitAppNotification
_SBSLaunchApplicationWithIdentifierAndLaunchOptions
_SCDynamicStoreCreate
_SCDynamicStoreCreateRunLoopSource
_SCDynamicStoreKeyCreateNetworkGlobalEntity
_SCDynamicStoreKeyCreateNetworkInterfaceEntity
_SCDynamicStoreSetNotificationKeys
_SCError
_SCErrorString
_SSDownloadAssetTypeMedia
_SSDownloadKindNSURLSession
_SSDownloadPhaseDataRestore
_SSDownloadPhaseDownloading
_SSDownloadPhaseInstalling
_SSDownloadPhasePaused
_SSDownloadPhasePreflight
_SSDownloadPhaseProcessing
_SSDownloadPropertyClientBundleIdentifier
_SSDownloadPropertyKind
_SSDownloadPropertyPriority
_SSDownloadPropertyShouldSuppressErrorDialogs
__Block_object_assign
__Block_object_dispose
__NSConcreteGlobalBlock
__NSConcreteStackBlock
__Unwind_SjLj_Register
__Unwind_SjLj_Resume
__Unwind_SjLj_Unregister
__ZSt9terminatev
___CFConstantStringClassReference
___cxa_begin_catch
___fixdfdi
___floatdidf
___gxx_personality_sj0
___stack_chk_fail
___stack_chk_guard
__dispatch_source_type_timer
__kCFStreamPropertyLargeDownload
__kCFURLConnectionPropertyDuet
__objc_empty_cache
__objc_empty_vtable
_dispatch_after
_dispatch_async
_dispatch_get_global_queue
_dispatch_once
_dispatch_queue_create
_dispatch_resume
_dispatch_semaphore_create
_dispatch_semaphore_signal
_dispatch_semaphore_wait
_dispatch_source_cancel
_dispatch_source_create
_dispatch_source_set_event_handler
_dispatch_source_set_timer
_dispatch_sync
_dispatch_time
_kCFBooleanTrue
_kCFErrorDomainCFNetwork
_kCFRunLoopDefaultMode
_kCFStreamPropertySourceApplicationBundleIdentifier
_kCFTypeArrayCallBacks
_kSCCompAnyRegex
_kSCDynamicStoreDomainState
_kSCEntNetIPv4
_kSCEntNetIPv6
_mktemp
_notify_register_dispatch
_objc_autoreleaseReturnValue
_objc_copyStruct
_objc_destroyWeak
_objc_enumerationMutation
_objc_getClass
_objc_getProperty
_objc_loadWeakRetained
_objc_msgSend
_objc_msgSendSuper2
_objc_release
_objc_retain
_objc_retainAutorelease
_objc_retainAutoreleaseReturnValue
_objc_retainAutoreleasedReturnValue
_objc_retainBlock
_objc_setProperty_atomic
_objc_setProperty_atomic_copy
_objc_storeStrong
_objc_storeWeak
_snprintf
_strlen
_xpc_track_activity
dyld_stub_binder
