/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 1:39:07 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/MobileTimer.app/MobileTimer
* classdump-dyld is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/

#import <MobileTimer/MobileTimer-Structs.h>
#import <UIKit/UICollectionViewLayout.h>

@class NSCalendar, NSDate, NSDateComponents, NSMutableArray, NSMutableDictionary, NSIndexPath, NSString, NSMutableSet, AlarmScheduleLayoutData, NSTimer, NSDictionary;

@interface AlarmScheduleLayout : UICollectionViewLayout {

	BOOL _needsRefreshDateInfo;
	int _firstDayOfWeek;
	NSCalendar* _calendar;
	NSDate* _now;
	NSDateComponents* _nowComps;
	NSMutableArray* _alarmIdForSection;
	NSMutableDictionary* _layoutDataMap;
	NSMutableArray* _itemZOrder[7];
	NSMutableDictionary* _overlappingItemLists[7];
	NSIndexPath* _pendingFrontIndexPath;
	NSString* _pendingUpdatedAlarmId;
	int _pendingUpdatedAlarmAction;
	BOOL _needsRefreshLayout;
	NSMutableSet* _changedAlarmIds;
	NSMutableSet* _pendingSnoozeChangedAlarms;
	int _dragState;
	AlarmScheduleLayoutData* _draggingLayoutData;
	float _dragXStartLocation;
	float _dragYOffset;
	CGPoint _pendingDragLocation;
	/*^block*/ id _dragCompletionBlock;
	NSTimer* _nextNonRepeatingAlarmTimer;
	NSMutableDictionary* _cachedAttributes;
	NSDictionary* _previousCachedAttributes;
	NSMutableDictionary* _cachedAttributesAlarmMap[7];
	NSMutableDictionary* _previousCachedAttributesAlarmMap[7];
	NSMutableArray* _previousAlarmIdForSection;
	NSMutableSet* _reloadedAlarms;
	NSMutableDictionary* _dayOfOverlappingReloadedAlarms;

}

@property (nonatomic,readonly) int firstDayOfWeek;                       //@synthesize firstDayOfWeek=_firstDayOfWeek - In the implementation block
@property (nonatomic,readonly) int currentDayOfWeek; 
@property (nonatomic,readonly) NSDate * now;                             //@synthesize now=_now - In the implementation block
@property (nonatomic,readonly) NSDateComponents * nowComps;              //@synthesize nowComps=_nowComps - In the implementation block
@property (nonatomic,readonly) float leftMargin; 
@property (nonatomic,readonly) float columnWidth; 
+(float)yForTimeInMinutes:(int)arg1 ;
+(int)timeInMinutesForY:(float)arg1 ;
-(void)bringAlarmToFront:(id)arg1 ;
-(BOOL)isAlarmOverlapping:(id)arg1 ;
-(id)cycleAlarmToBack:(id)arg1 ;
-(void)beginDraggingAlarmId:(id)arg1 fromLocationInSuperview:(CGPoint)arg2 ;
-(void)dragAlarmToLocationInSuperview:(CGPoint)arg1 completion:(/*^block*/ id)arg2 ;
-(void)endDraggingAlarmWithInvalidation:(BOOL)arg1 ;
-(void)setPendingUpdatedAlarmId:(id)arg1 action:(int)arg2 ;
-(void)addPendingSnoozeChangedForAlarmId:(id)arg1 ;
-(void)setNeedsRefreshLayoutWithChangedAlarmIds:(id)arg1 ;
-(int)currentDayOfWeek;
-(void)setNeedsRefreshDateInfo;
-(id)nowComps;
-(BOOL)refreshDateInfo;
-(void)setNeedsRefreshDateInfoWithInvalidation:(BOOL)arg1 ;
-(void)resetEverything;
-(void)handleNextNonRepeatingAlarm;
-(id)fullyOverlappingAlarmsForAlarm:(id)arg1 forDay:(int)arg2 ;
-(void)resetAllAlarmLayout;
-(void)resetAllAlarmOperations;
-(void)calculateLayoutForAllAlarms;
-(void)handleReloadOfAlarm:(id)arg1 ;
-(void)handleInsertOfAlarm:(id)arg1 ;
-(void)handleDeleteOfAlarm:(id)arg1 ;
-(int)columnIndexForX:(float)arg1 ;
-(void)handleDeleteOfAlarm:(id)arg1 forDays:(id)arg2 ;
-(void)handleInsertOfAlarm:(id)arg1 atZIndex:(int)arg2 forDays:(id)arg3 ;
-(void)scheduleTimerForNextNonRepeatingAlarm;
-(void)determineOverlappingItemListsForAlarms:(id)arg1 onDay:(int)arg2 ;
-(id)sortLayoutDataByTime:(id)arg1 forDay:(int)arg2 ;
-(void)handleNoLongerOverlappingAlarm:(id)arg1 forDay:(int)arg2 ;
-(SCD_Struct_Al5)daysVisibleInRect:(CGRect)arg1 ;
-(SCD_Struct_Al6)timesVisibleInRect:(CGRect)arg1 ;
-(id)now;
-(void)dealloc;
-(id)init;
-(CGSize)collectionViewContentSize;
-(id)layoutAttributesForItemAtIndexPath:(id)arg1 ;
-(float)columnWidth;
-(void)prepareLayout;
-(id)layoutAttributesForElementsInRect:(CGRect)arg1 ;
-(BOOL)shouldInvalidateLayoutForBoundsChange:(CGRect)arg1 ;
-(id)finalLayoutAttributesForDisappearingItemAtIndexPath:(id)arg1 ;
-(id)initialLayoutAttributesForAppearingItemAtIndexPath:(id)arg1 ;
-(void)prepareForCollectionViewUpdates:(id)arg1 ;
-(void)finalizeCollectionViewUpdates;
-(int)firstDayOfWeek;
-(float)leftMargin;
-(float)rightMargin;
@end

