/*
* This header is generated by classdump-dyld 0.1
* on Thursday, November 28, 2013 at 4:00:36 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/MobileTimer.app/MobileTimer
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/

#import <MobileTimer/MobileTimer-Structs.h>
#import <UIKit/UIView.h>

@class UILabel;

@interface LapPadTableViewHeaderView : UIView {

	UILabel* _leftColumnHeader;
	UILabel* _centerColumnHeader;
	UILabel* _rightColumnHeader;

}
+(float)defaultHeight;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)layoutSubviews;
@end

