/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 1:39:07 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/MobileTimer.app/MobileTimer
* classdump-dyld is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/

#import <MobileTimer/TimerControlsView.h>

@protocol TimerPadControlsViewDelegate;
@class UIImageView, CircleProgressView, UIButton, MTTimerButtonsController, ;

@interface TimerPadControlsView : TimerControlsView {

	UIImageView* _circleBackground;
	CircleProgressView* _circleProgressView;
	UIButton* _toneButton;
	MTTimerButtonsController* _buttonsController;
	<TimerPadControlsViewDelegate>* _timerControlsDelegate;

}

@property (assign,nonatomic) <TimerPadControlsViewDelegate> * timerControlsDelegate;              //@synthesize timerControlsDelegate=_timerControlsDelegate - In the implementation block
-(void)setTimerToneName:(id)arg1 ;
-(void)setTimerControlsDelegate:(id)arg1 ;
-(void)showSoundPicker:(id)arg1 ;
-(void)_configureAndAddButton:(id)arg1 ;
-(void)setState:(int)arg1 force:(BOOL)arg2 ;
-(id)timerControlsDelegate;
-(void)dealloc;
-(void)layoutSubviews;
-(int)state;
-(void)setState:(int)arg1 ;
-(id)initWithTarget:(id)arg1 ;
-(void)willRotateToInterfaceOrientation:(int)arg1 duration:(double)arg2 ;
-(void)setTime:(double)arg1 ;
@end

