/*
* This header is generated by strong_classdump 0.1
* on Wednesday, November 27, 2013 at 12:01:42 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/MobileTimer.app/MobileTimer
* strong_classdump is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/

#import <MobileTimer/MobileTimer-Structs.h>
#import <UIKit/UIPageControl.h>

@class UIImage;

@interface WorldClockPageControl : UIPageControl {

	UIImage* _indicator;
	UIImage* _currentIndicator;

}
-(id)initWithFrame:(CGRect)arg1 useNeutralColor:(BOOL)arg2 ;
-(void)dealloc;
-(id)_pageIndicatorImageForPage:(int)arg1 ;
-(id)_pageIndicatorCurrentImageForPage:(int)arg1 ;
@end

