/*
* This header is generated by classdump-dyld 0.1
* on Thursday, November 28, 2013 at 3:59:52 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/

#import <Maps/SearchCompletionTableViewCell.h>

@class NSArray;

@interface AddressCompletionTableViewCell : SearchCompletionTableViewCell {

	NSArray* _addressLines;

}

@property (nonatomic,retain) NSArray * addressLines;              //@synthesize addressLines=_addressLines - In the implementation block
-(void)dealloc;
-(id)initWithReuseIdentifier:(id)arg1 ;
-(void)setAddressLines:(id)arg1 ;
-(id)addressLines;
@end

