/*
* This header is generated by strong_classdump 0.1
* on Wednesday, November 27, 2013 at 12:00:55 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Maps.app/Maps
* strong_classdump is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/

#import <Maps/Maps-Structs.h>
#import <UIKit/UIButton.h>

@interface CustomCalloutButton : UIButton
+(id)buttonWithNormalImageName:(id)arg1 pressedImageName:(id)arg2 ;
+(id)button;
-(id)hitTest:(CGPoint)arg1 withEvent:(id)arg2 ;
-(BOOL)pointInside:(CGPoint)arg1 withEvent:(id)arg2 ;
@end

