/*
* This header is generated by strong_classdump 0.1
* on Wednesday, November 27, 2013 at 12:01:01 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Maps.app/Maps
* strong_classdump is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/

#import <Maps/Maps-Structs.h>
#import <Maps/InfoCardBackgroundView.h>
#import <ChatKit/MKMapViewDelegate.h>

@class MKMapView, UIImageView, NSTimer;

@interface InfoCardBackgroundView_Snapshot : InfoCardBackgroundView <MKMapViewDelegate> {

	MKMapView* _mapView;
	UIImageView* _pin;
	NSTimer* _timer;
	double _orbitStartTime;
	BOOL showsPin;
	BOOL useSatellite;
	float zoomLevel;

}

@property (assign) BOOL showsPin; 
@property (assign) BOOL useSatellite; 
@property (assign) float zoomLevel; 
-(void)prepareForPresentation;
-(BOOL)showsPin;
-(BOOL)useSatellite;
-(void)updatePin;
-(void)resizeMapIfNeeded;
-(void)setShowsPin:(BOOL)arg1 ;
-(void)setUseSatellite:(BOOL)arg1 ;
-(void)pauseOrbit;
-(void)requestSnapshot;
-(void)mapFinishedLoading:(BOOL)arg1 ;
-(void)orbit:(id)arg1 ;
-(void)beginOrbit;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)setFrame:(CGRect)arg1 ;
-(void)present;
-(void)reset;
-(id)pin;
-(int)backgroundType;
-(float)zoomLevel;
-(void)mapView:(id)arg1 regionDidChangeAnimated:(BOOL)arg2 ;
-(void)mapViewDidFinishLoadingMap:(id)arg1 ;
-(void)mapViewDidFinishRenderingMap:(id)arg1 fullyRendered:(BOOL)arg2 ;
-(void)setZoomLevel:(float)arg1 ;
@end

