/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 10:35:04 PM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/


@protocol ManeuverGuidanceObserver <NSObject>
@optional
-(void)maneuverGuidanceDetailsWillChange:(id)arg1;

@required
-(void)maneuverGuidanceDistanceDidChange:(id)arg1;
-(void)maneuverGuidanceDetailsDidChange:(id)arg1;
@end

