/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 10:35:16 PM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Maps.app/mapspushd
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/

typedef struct _NSZone* NSZoneRef;

typedef struct {
	unsigned businessID : 1;
	unsigned latitude : 1;
	unsigned longitude : 1;
	unsigned regionLatitude : 1;
	unsigned regionLatitudeDelta : 1;
	unsigned regionLongitude : 1;
	unsigned regionLongitudeDelta : 1;
	unsigned directionsMode : 1;
	unsigned providerID : 1;
} SCD_Struct_Sy1;

