/*
* This header is generated by classdump-dyld 0.1
* on Thursday, November 28, 2013 at 3:59:54 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/

#import <MapKit/_MKUserTrackingButton.h>

@interface MapsUserTrackingButton : _MKUserTrackingButton {

	BOOL _shouldInvertSelectionColor;
	BOOL shouldInvertSelectionColor;

}

@property (assign) BOOL shouldInvertSelectionColor; 
-(void)setShouldInvertSelectionColor:(BOOL)arg1 ;
-(void)updateSelectedTintColor;
-(BOOL)shouldInvertSelectionColor;
-(void)tintColorDidChange;
-(void)setSelected:(BOOL)arg1 ;
-(id)_selectedIndicatorViewWithImage:(id)arg1 ;
-(float)_selectedIndicatorAlpha;
@end

