/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 10:35:16 PM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Maps.app/geocorrectiond
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/


@class RTRoutineManager, NSArray;

@interface MCRoutineHelper : NSObject {

	RTRoutineManager* _routineManager;
	NSArray* _allLOIs;

}
-(void)findSignificantLocationAvailability:(/*^block*/ id)arg1 ;
-(void)findSignificantLocationAtLocation:(id)arg1 finishedHandler:(/*^block*/ id)arg2 ;
-(void)findNearbySignificantLocationsAtLocation:(id)arg1 inRadius:(double)arg2 finishedHandler:(/*^block*/ id)arg3 ;
-(void)dealloc;
-(id)init;
@end

