/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 1:38:25 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/


@protocol OS_xpc_object, MNBTAJobDelegate;
@class NSObject, NSString, ;

@interface MNBTAJob : NSObject {

	NSObject<OS_xpc_object>* _job;
	NSString* _name;
	<MNBTAJobDelegate>* _delegate;

}

@property (nonatomic,readonly) NSObject<OS_xpc_object> * job;              //@synthesize job=_job - In the implementation block
@property (nonatomic,readonly) NSString * name;                            //@synthesize name=_name - In the implementation block
@property (assign,nonatomic) <MNBTAJobDelegate> * delegate;                //@synthesize delegate=_delegate - In the implementation block
-(id)initWithJob:(id)arg1 name:(id)arg2 ;
-(void)dealloc;
-(void)setDelegate:(id)arg1 ;
-(id)description;
-(id)delegate;
-(id)name;
-(id)job;
@end

