/*
* This header is generated by strong_classdump 0.1
* on Wednesday, November 27, 2013 at 12:01:07 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Maps.app/Maps
* strong_classdump is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/

#import <Maps/MNMapMatcher.h>

@interface MNDriveMapMatcher : MNMapMatcher {

	double _lastKnownSpeed;

}
-(id)matchLocation:(id)arg1 alongRoute:(id)arg2 onDate:(id)arg3 activeTransportType:(int)arg4 ;
-(id)projectInTunnelFromLocation:(id)arg1 timeInterval:(double)arg2 ;
-(void)reset;
-(int)transportType;
@end

