/*
* This header is generated by classdump-dyld 0.1
* on Thursday, November 28, 2013 at 3:59:58 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/

#import <Maps/MNMapMatcher.h>

@interface MNDriveMapMatcher : MNMapMatcher {

	double _lastKnownSpeed;

}
-(id)matchLocation:(id)arg1 alongRoute:(id)arg2 onDate:(id)arg3 activeTransportType:(int)arg4 ;
-(id)projectInTunnelFromLocation:(id)arg1 timeInterval:(double)arg2 ;
-(void)reset;
-(int)transportType;
@end

