/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 1:38:18 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/


@protocol MNGuidanceSignsDisplayDelegate <NSObject>
@required
-(void)guidanceSignsDisplayRepeatGuidance:(id)arg1;
-(void)guidanceSignsDisplayToggleNavigationBar:(id)arg1;
-(void)guidanceSignsDisplayUpdateBlur:(id)arg1 frame:(CGRect)arg2;
-(void)guidanceSignsDisplayDidInvalidateMinimumEdgeInsets:(id)arg1;
-(void)guidanceSignsDisplayChoseEndNavigation:(id)arg1;
-(void)guidanceSignsDisplayChoseOverview:(id)arg1;
-(void)guidanceSignsDisplayWillAnimateSign:(id)arg1;
-(void)guidanceSignsDisplayDidAnimateSign:(id)arg1;
@end

