/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 10:35:10 PM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/

#import <Maps/MNMotionContextProviderDelegate.h>

@protocol MNMotionContextProvider;
@class ;

@interface MNMotionContext : NSObject <MNMotionContextProviderDelegate> {

	<MNMotionContextProvider>* _provider;
	int _motionType;
	int _exitType;
	int _confidence;

}

@property (nonatomic,readonly) int motionType;              //@synthesize motionType=_motionType - In the implementation block
@property (nonatomic,readonly) int exitType;                //@synthesize exitType=_exitType - In the implementation block
@property (nonatomic,readonly) int confidence;              //@synthesize confidence=_confidence - In the implementation block
@property (nonatomic,readonly) BOOL isMoving; 
@property (nonatomic,readonly) BOOL isWalking; 
@property (nonatomic,readonly) BOOL isRunning; 
@property (nonatomic,readonly) BOOL isDriving; 
-(int)motionType;
-(void)startMotionUpdatesWithProvider:(id)arg1 ;
-(void)motionContextProvider:(id)arg1 didUpdateMotion:(int)arg2 exitType:(int)arg3 confidence:(int)arg4 ;
-(int)confidence;
-(BOOL)isMoving;
-(BOOL)isWalking;
-(BOOL)isDriving;
-(void)stopMotionUpdates;
-(void)dealloc;
-(id)description;
-(BOOL)isRunning;
-(int)exitType;
@end

