/*
* This header is generated by strong_classdump 0.1
* on Wednesday, November 27, 2013 at 12:01:06 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Maps.app/Maps
* strong_classdump is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/


@protocol MNTraceSliderViewDelegate <NSObject>
@required
-(void)traceSliderViewEditingDidBegin:(id)arg1;
-(void)traceSliderView:(id)arg1 editingEndedAtTime:(double)arg2;
-(void)traceSliderViewCancelledEditing:(id)arg1;
@end

