/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 1:38:23 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/

#import <Maps/MNGuidanceManager.h>

@interface MNWalkGuidanceManager : MNGuidanceManager
-(double)_adjustedDistanceToRoute:(id)arg1 ;
-(id)_combinedGuidanceForStep:(id)arg1 withType:(int)arg2 ;
-(void)_updatePrepareForNextStep;
-(BOOL)_updateConsiderExecuteAnnouncement:(id)arg1 location:(id)arg2 ;
-(double)_adjustedVehicleSpeed:(id)arg1 ;
-(int)transportType;
@end

