/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 1:38:26 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/

#import <UIKit/UIWindow.h>
#import <Maps/FlipViewControllerDelegate.h>

@interface ModalFlipWindow : UIWindow <FlipViewControllerDelegate> {

	/*^block*/ id _dismissal;

}

@property (nonatomic,copy) id dismissal;              //@synthesize dismissal=_dismissal - In the implementation block
-(void)presentViewController:(id)arg1 flippingView:(id)arg2 dismissal:(/*^block*/ id)arg3 ;
-(void)flipViewControllerDidDismiss:(id)arg1 ;
-(void)setDismissal:(/*^block*/ id)arg1 ;
-(/*^block*/ id)dismissal;
-(void)dealloc;
-(id)init;
-(void)dismiss;
@end

