/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 10:35:02 PM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/


@protocol MUActivityViewControllerDelegate <NSObject>
@required
-(void)mapsActivityViewController:(id)arg1 addBookmarkWithSearchResult:(id)arg2 title:(id)arg3;
-(void)mapsActivityViewController:(id)arg1 performedActivityOfType:(id)arg2 withSearchResult:(id)arg3 completed:(BOOL)arg4;
@end

