/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 1:38:27 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/

#import <ManagedConfiguration/NSURLConnectionDataDelegate.h>

@class NSCache, NSMapTable, NSMutableDictionary;

@interface MUAppImageManager : NSObject <NSURLConnectionDataDelegate> {

	NSCache* _iconCache;
	NSMapTable* _containers;
	NSMutableDictionary* _urlConnections;

}
+(id)sharedImageManager;
-(void)cancelLoadAppImageAtURL:(id)arg1 ;
-(void)loadAppImageAtURL:(id)arg1 completionHandler:(/*^block*/ id)arg2 ;
-(void)clearImageCache;
-(void)dealloc;
-(id)init;
-(void)connection:(id)arg1 didFailWithError:(id)arg2 ;
-(void)connection:(id)arg1 didReceiveData:(id)arg2 ;
-(void)connectionDidFinishLoading:(id)arg1 ;
@end

