/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 1:38:25 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/


@class NSString, ReportAProblemTableViewController;

@interface ProblemItem : NSObject {

	BOOL _isChecked;
	NSString* _title;
	int _problemType;
	BOOL _needsExtraInfo;
	ReportAProblemTableViewController* _moreItems;
	NSString* _subtitle;

}

@property (assign,nonatomic) BOOL isChecked;                                             //@synthesize isChecked=_isChecked - In the implementation block
@property (nonatomic,copy) NSString * title;                                             //@synthesize title=_title - In the implementation block
@property (nonatomic,copy) NSString * subtitle;                                          //@synthesize subtitle=_subtitle - In the implementation block
@property (assign,nonatomic) int problemType;                                            //@synthesize problemType=_problemType - In the implementation block
@property (assign,nonatomic) BOOL needsExtraInfo;                                        //@synthesize needsExtraInfo=_needsExtraInfo - In the implementation block
@property (nonatomic,retain) ReportAProblemTableViewController * moreItems;              //@synthesize moreItems=_moreItems - In the implementation block
+(id)problemItemWithTitle:(id)arg1 problemType:(int)arg2 ;
+(id)problemItemWithTitle:(id)arg1 problemType:(int)arg2 needsExtraInfo:(BOOL)arg3 ;
+(id)problemItemWithTitle:(id)arg1 subtitle:(id)arg2 problemType:(int)arg3 ;
+(id)problemItemWithTitle:(id)arg1 subtitle:(id)arg2 problemType:(int)arg3 needsExtraInfo:(BOOL)arg4 ;
+(id)problemItemWithTitle:(id)arg1 moreItems:(id)arg2 ;
-(void)setIsChecked:(BOOL)arg1 ;
-(void)setNeedsExtraInfo:(BOOL)arg1 ;
-(void)setMoreItems:(id)arg1 ;
-(id)initWithTitle:(id)arg1 subtitle:(id)arg2 problemType:(int)arg3 needsExtraInfo:(BOOL)arg4 moreItems:(id)arg5 ;
-(BOOL)hasValidProblemType;
-(BOOL)needsExtraInfo;
-(id)moreItems;
-(void)dealloc;
-(void)setTitle:(id)arg1 ;
-(id)title;
-(void)setSubtitle:(id)arg1 ;
-(id)subtitle;
-(BOOL)isChecked;
-(int)problemType;
-(void)setProblemType:(int)arg1 ;
@end

