/*
* This header is generated by strong_classdump 0.1
* on Wednesday, November 27, 2013 at 12:01:06 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Maps.app/Maps
* strong_classdump is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/

#import <Maps/ReportAProblemAddressTableViewCell.h>

@class NSMutableArray, NSDictionary;

@interface ReportAProblemAddressTableViewMultiCell : ReportAProblemAddressTableViewCell {

	NSMutableArray* _valueFields;
	NSMutableArray* _horizontalBars;
	NSMutableArray* _verticalBars;
	NSDictionary* _locale;
	unsigned _numberOfLines;

}
-(BOOL)becomeFirstResponderFromDirection:(int)arg1 ;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2 localeCode:(id)arg3 ;
-(void)setValue:(id)arg1 forAddressType:(int)arg2 ;
-(void)setOriginalText:(id)arg1 forAddressType:(int)arg2 ;
-(void)fieldChanged:(id)arg1 ;
-(void)reportAProblemTextFieldCorrectnessStatusChanged;
-(void)reportAProblemTextFieldNextPressed;
-(void)reportAProblemTextFieldPreviousPressed;
-(int)_addressTypeForEditComponent:(id)arg1 ;
-(id)_placeholderTextForEditComponent:(id)arg1 ;
-(BOOL)_isHalfWidthForEditComponent:(id)arg1 lines:(id)arg2 ;
-(id)newVerticalBar;
-(unsigned)_indexOfFirstResponder;
-(id)_addressBookBundle;
-(void)dealloc;
-(void)layoutSubviews;
-(float)cellHeight;
@end

