/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 10:35:12 PM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/

#import <Maps/Maps-Structs.h>
#import <UIKit/UITextField.h>

@protocol RAPTextFieldInputAccessoryViewDelegate;
@class , NSString;

@interface ReportAProblemTextField : UITextField {

	<RAPTextFieldInputAccessoryViewDelegate>* _inputAccessoryViewDelegate;
	int _addressType;
	NSString* _originalText;
	BOOL _halfWidth;
	int _disabledDirection;

}

@property (assign,nonatomic) int addressType;                                                                    //@synthesize addressType=_addressType - In the implementation block
@property (nonatomic,retain) NSString * originalText;                                                            //@synthesize originalText=_originalText - In the implementation block
@property (assign,nonatomic) BOOL halfWidth;                                                                     //@synthesize halfWidth=_halfWidth - In the implementation block
@property (assign,nonatomic) <RAPTextFieldInputAccessoryViewDelegate> * inputAccessoryViewDelegate;              //@synthesize inputAccessoryViewDelegate=_inputAccessoryViewDelegate - In the implementation block
-(int)addressType;
-(void)setAddressType:(int)arg1 ;
-(void)disableDirectionButtonWithDirection:(int)arg1 ;
-(void)setOriginalText:(id)arg1 ;
-(void)setInputAccessoryViewDelegate:(id)arg1 ;
-(void)fieldChanged:(id)arg1 ;
-(void)updateInputAccessoryView;
-(void)editingBegan:(id)arg1 ;
-(void)editingEnded:(id)arg1 ;
-(void)_updateRAPTextColor;
-(void)nextPrevButtonPressed:(id)arg1 ;
-(void)markAsWrongPressed:(id)arg1 ;
-(void)doneButtonPressed:(id)arg1 ;
-(void)_updateNextPreviousButton;
-(void)_updateMarkAsWrongButton;
-(id)inputAccessoryViewDelegate;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(id)description;
-(void)setText:(id)arg1 ;
-(id)originalText;
-(void)setHalfWidth:(BOOL)arg1 ;
-(BOOL)halfWidth;
@end

