/*
* This header is generated by classdump-dyld 0.1
* on Thursday, November 28, 2013 at 3:59:48 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/

#import <Maps/Maps-Structs.h>
#import <ChatKit/MKAnnotation.h>

@class MNRoute, NSString;

@interface RouteAnnotation : NSObject <MKAnnotation> {

	MNRoute* _route;
	SCD_Struct_Si10 _coordinate;

}

@property (nonatomic,readonly) MNRoute * route;                       //@synthesize route=_route - In the implementation block
@property (assign,nonatomic) SCD_Struct_Si10 coordinate;              //@synthesize coordinate=_coordinate - In the implementation block
@property (nonatomic,readonly) NSString * title; 
@property (nonatomic,readonly) NSString * subtitle; 
-(id)description;
-(SCD_Struct_Si10)coordinate;
-(void)setCoordinate:(SCD_Struct_Si10)arg1 ;
-(id)route;
-(id)initWithRoute:(id)arg1 ;
@end

