/*
* This header is generated by classdump-dyld 0.1
* on Thursday, November 28, 2013 at 3:59:46 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/


@protocol SearchBarDelegate <NSObject>
@property (nonatomic,readonly) DirectionsSearchViewController * directionsSearchViewController; 
@property (nonatomic,readonly) BOOL isRotating; 
@required
-(id)collectionsViewController;
-(void)clearSearchResults;
-(id)worldView;
-(id)directionsSearchViewController;
-(void)searchBarDidPresentPopover:(id)arg1 shouldReselectAnnotation:(BOOL)arg2;
-(void)searchBarDirectionsButtonWasTapped:(id)arg1;
-(void)searchBar:(id)arg1 choseHistoryItem:(id)arg2;
-(void)searchBar:(id)arg1 choseBookmark:(id)arg2;
-(void)searchBarBookmarksButtonWasTapped:(id)arg1;
-(void)searchBarCancelButtonWasTapped:(id)arg1;
-(BOOL)isRotating;
@end

