/*
* This header is generated by strong_classdump 0.1
* on Wednesday, November 27, 2013 at 12:00:58 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Maps.app/Maps
* strong_classdump is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/

#import <UIKit/UILabel.h>
#import <Maps/StarkToolbarTitleView.h>

@interface StarkToolbarTitleLabel : UILabel <StarkToolbarTitleView> {

	int _lightLevel;

}
-(void)setDisplayedLightLevel:(int)arg1 ;
-(void)_updateStarkToolbarTitleAttributedText;
-(id)_starkToolbarTitleAttributes;
-(void)setText:(id)arg1 ;
@end

