/*
* This header is generated by strong_classdump 0.1
* on Wednesday, November 27, 2013 at 12:00:55 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Maps.app/Maps
* strong_classdump is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/

#import <UIKit/UIViewController.h>

@class UIView, UILabel, NSMutableArray, NSArray, UIWindow, NSString;

@interface StarkAlertViewController : UIViewController {

	UIView* _contentView;
	UIView* _shieldView;
	UILabel* _titleLabel;
	UILabel* _messageLabel;
	NSMutableArray* _choiceButtonLabels;
	NSMutableArray* _choiceButtonCancel;
	NSArray* _buttons;
	UIWindow* _displayingWindow;
	BOOL _done;
	NSString* _alertTitle;
	NSString* _alertMessage;
	int _behavior;
	/*^block*/ id _resultBlock;
	int _interactionModel;
	/*^block*/ id _firstResponderRequestBlock;

}

@property (nonatomic,copy) id resultBlock;                       //@synthesize resultBlock=_resultBlock - In the implementation block
@property (readonly) id firstResponderRequestBlock;              //@synthesize firstResponderRequestBlock=_firstResponderRequestBlock - In the implementation block
@property (nonatomic,copy) NSString * alertTitle;                //@synthesize alertTitle=_alertTitle - In the implementation block
@property (nonatomic,copy) NSString * alertMessage;              //@synthesize alertMessage=_alertMessage - In the implementation block
@property (assign,nonatomic) int behavior;                       //@synthesize behavior=_behavior - In the implementation block
@property (assign,nonatomic) int interactionModel;               //@synthesize interactionModel=_interactionModel - In the implementation block
+(id)_alertWindowForScreen:(id)arg1 creatingIfNeeded:(BOOL)arg2 ;
+(void)_screenDidDisconnect:(id)arg1 ;
-(void)setInteractionModel:(int)arg1 ;
-(int)interactionModel;
-(void)_recreateButtonsIfNeededRequiringViewLoaded:(BOOL)arg1 ;
-(id)_buttonLabelsForBehavior:(int)arg1 ;
-(void)_selectButton:(id)arg1 ;
-(id)_dismissButtonBackgroundImage;
-(void)_requestFirstResponderStatusForResponder:(id)arg1 ;
-(void)_dismissWithResult:(int)arg1 buttonIndex:(int)arg2 ;
-(void)_invokeCompletionWithResult:(int)arg1 buttonIndex:(int)arg2 ;
-(void)_dismissFromAlertWindow;
-(void)_highlightNextButton;
-(void)_highlightPreviousButton;
-(void)_supersede;
-(id)initWithResultBlock:(/*^block*/ id)arg1 ;
-(void)setAlertTitle:(id)arg1 ;
-(id)alertTitle;
-(void)setAlertMessage:(id)arg1 ;
-(id)alertMessage;
-(unsigned)addButtonWithTitle:(id)arg1 cancels:(BOOL)arg2 ;
-(void)_acknowledge;
-(void)presentInAlertWindowOnScreen:(id)arg1 ;
-(/*^block*/ id)firstResponderRequestBlock;
-(void)dealloc;
-(id)init;
-(void)_physicalButtonsBegan:(id)arg1 withEvent:(id)arg2 ;
-(void)_wheelChangedWithEvent:(id)arg1 ;
-(BOOL)canBecomeFirstResponder;
-(void)viewWillLayoutSubviews;
-(void)_moveWithEvent:(id)arg1 ;
-(void)loadView;
-(void)viewDidAppear:(BOOL)arg1 ;
-(void)dismiss;
-(void)setResultBlock:(/*^block*/ id)arg1 ;
-(/*^block*/ id)resultBlock;
-(int)behavior;
-(void)setBehavior:(int)arg1 ;
@end

