/*
* This header is generated by strong_classdump 0.1
* on Wednesday, November 27, 2013 at 12:01:07 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Maps.app/Maps
* strong_classdump is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/

#import <Maps/SearchCompletionsTableViewController.h>
#import <Maps/SearchCompletionsTableViewControllerDelegate.h>

@class UIBarButtonItem;

@interface StarkRecentsViewController : SearchCompletionsTableViewController <SearchCompletionsTableViewControllerDelegate> {

	/*^block*/ id _completion;
	UIBarButtonItem* _doneBarButtonItem;

}

@property (nonatomic,readonly) UIBarButtonItem * doneBarButtonItem; 
-(void)searchCompletionsTableViewController:(id)arg1 hasCompletionsForQuery:(id)arg2 ;
-(void)searchCompletionsTableViewController:(id)arg1 didSelectQueryCompletion:(id)arg2 forQuery:(id)arg3 ;
-(void)searchCompletionsTableViewController:(id)arg1 didSelectHistoryItem:(id)arg2 forQuery:(id)arg3 ;
-(void)searchCompletionsTableViewController:(id)arg1 didSelectSearchCompletion:(id)arg2 forQuery:(id)arg3 ;
-(id)doneBarButtonItem;
-(void)dealloc;
-(id)initWithCompletionBlock:(/*^block*/ id)arg1 ;
-(void)viewDidAppear:(BOOL)arg1 ;
-(void)done;
@end

