/*
* This header is generated by strong_classdump 0.1
* on Wednesday, November 27, 2013 at 12:00:54 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Maps.app/Maps
* strong_classdump is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/


@protocol StarkChromeModeController <MapsChromeModeController,MapsChromeModeControllerWithInterruptionDisplay>
@optional
-(void)layoutForInteractionModelChange;
-(void)willEnterPanModeWithAnimation:(id)arg1;
-(void)willExitPanModeWithAnimation:(id)arg1;
-(BOOL)physicalButtonsBegan:(id)arg1;
-(BOOL)physicalButtonsEnded:(id)arg1;
-(BOOL)physicalButtonsCancelled:(id)arg1;
-(BOOL)moveWithEvent:(id)arg1;
-(BOOL)wheelChangedWithEvent:(id)arg1;
-(BOOL)presentMenu;
-(void)showAutohidingContentWithAnimation:(id)arg1;
-(void)hideAutohidingContentWithAnimation:(id)arg1;
-(double)autohideIdlenessInterval;
-(void)willEndAutohideInterruptionsForTokens:(id)arg1;
-(BOOL)starkStatusBarModifiesInsets;
-(BOOL)starkTopBarModifiesInsets;
-(id)topBarForInteractionModel:(int)arg1;
@end

