/*
* This header is generated by strong_classdump 0.1
* on Wednesday, November 27, 2013 at 12:00:53 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Maps.app/Maps
* strong_classdump is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/


@protocol UIActivityItemSocialSource <NSObject>
@optional
-(id)activityViewController:(id)arg1 thumbnailForActivityType:(id)arg2;
-(int)activityViewController:(id)arg1 attachmentULRTypeForActivityType:(id)arg2;
@end

