/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 10:35:01 PM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/

#import <Maps/Maps-Structs.h>
#import <Maps/SearchResult.h>
#import <MapKit/MKUserLocationAnnotation.h>

@class NSString;

@interface UserLocationSearchResult : SearchResult <MKUserLocationAnnotation> {

	double _reverseGeocodeUpdateTime;
	SCD_Struct_Si10 _reverseGeocodeCoordinate;
	double _accuracy;
	double _reverseGeocodeAccuracy;
	BOOL _selected;

}

@property (assign,nonatomic) double accuracy; 
@property (assign,getter=isSelected,nonatomic) BOOL selected;              //@synthesize selected=_selected - In the implementation block
@property (nonatomic,readonly) SCD_Struct_Si10 coordinate; 
@property (nonatomic,readonly) NSString * title; 
@property (nonatomic,readonly) NSString * subtitle; 
-(void)setReverseGeocoded:(BOOL)arg1 ;
-(BOOL)needsReverseGeocodeCheck;
-(BOOL)requiresPanoramaIDCheck;
-(void)setAccuracy:(double)arg1 ;
-(id)init;
-(BOOL)isSelected;
-(void)setSelected:(BOOL)arg1 ;
-(id).cxx_construct;
-(void)setCoordinate:(SCD_Struct_Si10)arg1 ;
-(double)accuracy;
@end

