/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 1:38:25 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/


@class GEOPlace, NSString;

@interface WeatherDetailProvider : NSObject {

	GEOPlace* _place;
	NSString* _temperatureAtPlace;
	/*^block*/ id _updateHandler;

}

@property (retain) GEOPlace * place;              //@synthesize place=_place - In the implementation block
@property (copy) id updateHandler;                //@synthesize updateHandler=_updateHandler - In the implementation block
+(BOOL)infoAvailable;
-(void)beginUpdateWithHandler:(/*^block*/ id)arg1 ;
-(void)dealloc;
-(void)endUpdates;
-(void)setPlace:(id)arg1 ;
-(void)setUpdateHandler:(/*^block*/ id)arg1 ;
-(/*^block*/ id)updateHandler;
-(id)place;
@end

