/*
* This header is generated by classdump-dyld 0.1
* on Thursday, November 28, 2013 at 3:59:27 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Contacts.app/Contacts
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/


@interface ContactsTestingManager : NSObject {

	id _currentTest;

}

@property (nonatomic,retain) id currentTest;              //@synthesize currentTest=_currentTest - In the implementation block
+(id)defaultTestingManager;
-(BOOL)runTest:(id)arg1 options:(id)arg2 peoplePicker:(id)arg3 ;
-(id)currentTest;
-(void)setCurrentTest:(id)arg1 ;
-(void).cxx_destruct;
@end

