/*
* This header is generated by strong_classdump 0.1
* on Wednesday, November 27, 2013 at 12:00:37 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Contacts.app/Contacts
* strong_classdump is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/

#import <UIKit/UINavigationControllerDelegate.h>
#import <Contacts/ABMembersControllerSearchCompletionDelegate.h>

@class ABPeoplePickerNavigationController, NSMutableDictionary, NSArray;

@interface SearchByNameTest : NSObject <UINavigationControllerDelegate, ABMembersControllerSearchCompletionDelegate> {

	BOOL _animate;
	ABPeoplePickerNavigationController* _peoplePicker;
	NSMutableDictionary* _extraResults;
	NSArray* _allDatabaseDirectories;
	unsigned _currentDirectoryIndex;
	int _testState;
	NSArray* _allSearchQueries;
	unsigned _currentQueryIndex;
	double _lastSearchBeginTime;

}

@property (nonatomic,retain) ABPeoplePickerNavigationController * peoplePicker;              //@synthesize peoplePicker=_peoplePicker - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * extraResults;                             //@synthesize extraResults=_extraResults - In the implementation block
@property (nonatomic,retain) NSArray * allDatabaseDirectories;                               //@synthesize allDatabaseDirectories=_allDatabaseDirectories - In the implementation block
@property (assign,nonatomic) unsigned currentDirectoryIndex;                                 //@synthesize currentDirectoryIndex=_currentDirectoryIndex - In the implementation block
@property (assign,nonatomic) int testState;                                                  //@synthesize testState=_testState - In the implementation block
@property (assign,nonatomic) BOOL animate;                                                   //@synthesize animate=_animate - In the implementation block
@property (nonatomic,retain) NSArray * allSearchQueries;                                     //@synthesize allSearchQueries=_allSearchQueries - In the implementation block
@property (assign,nonatomic) unsigned currentQueryIndex;                                     //@synthesize currentQueryIndex=_currentQueryIndex - In the implementation block
@property (assign,nonatomic) double lastSearchBeginTime;                                     //@synthesize lastSearchBeginTime=_lastSearchBeginTime - In the implementation block
-(BOOL)startTestWithOptions:(id)arg1 peoplePicker:(id)arg2 ;
-(void)setExtraResults:(id)arg1 ;
-(void)setAllDatabaseDirectories:(id)arg1 ;
-(void)setAllSearchQueries:(id)arg1 ;
-(void)setCurrentQueryIndex:(unsigned)arg1 ;
-(void)loadNextDatabase;
-(unsigned)currentQueryIndex;
-(id)allSearchQueries;
-(double)lastSearchBeginTime;
-(id)extraResults;
-(void)startSearchQuery;
-(void)didShowViewController:(id)arg1 ;
-(unsigned)currentDirectoryIndex;
-(void)setTestState:(int)arg1 ;
-(void)setCurrentDirectoryIndex:(unsigned)arg1 ;
-(int)testState;
-(void)setLastSearchBeginTime:(double)arg1 ;
-(void)membersControllerDidCompleteSearch:(id)arg1 ;
-(id)allDatabaseDirectories;
-(void)navigationController:(id)arg1 didShowViewController:(id)arg2 animated:(BOOL)arg3 ;
-(id)peoplePicker;
-(void)setPeoplePicker:(id)arg1 ;
-(BOOL)animate;
-(void).cxx_destruct;
-(void)setAnimate:(BOOL)arg1 ;
@end

