/*
* This header is generated by classdump-dyld 0.1
* on Thursday, November 28, 2013 at 4:00:37 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/MobileTimer.app/MobileTimer
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/

#import <MobileTimer/MobileTimer-Structs.h>
#import <UIKit/UIView.h>

@class UILabel;

@interface AlarmTitleAndRepeatView : UIView {

	float _previousWidth;
	UILabel* _titleLabel;
	UILabel* _repeatLabel;

}

@property (nonatomic,readonly) UILabel * titleLabel;               //@synthesize titleLabel=_titleLabel - In the implementation block
@property (nonatomic,readonly) UILabel * repeatLabel;              //@synthesize repeatLabel=_repeatLabel - In the implementation block
-(id)repeatLabel;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)layoutSubviews;
-(id)titleLabel;
@end

