/*
* This header is generated by classdump-dyld 0.1
* on Thursday, November 28, 2013 at 3:59:39 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/GameCenterUIService.app/GameCenterUIService
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/

#import <GameCenterUIService/GKServiceViewController.h>
#import <GameCenterUI/RemoteChallengeIssueViewControllerDelegate.h>

@class GKChallenge, NSString, NSArray, GKGame;

@interface ChallengeIssueServiceViewController : GKServiceViewController <RemoteChallengeIssueViewControllerDelegate> {

	BOOL _forcePicker;
	GKChallenge* _challenge;
	NSString* _defaultMessage;
	NSArray* _playerIDs;
	/*^block*/ id _completionHandler;

}

@property (nonatomic,retain) GKChallenge * challenge;              //@synthesize challenge=_challenge - In the implementation block
@property (nonatomic,copy) NSString * defaultMessage;              //@synthesize defaultMessage=_defaultMessage - In the implementation block
@property (nonatomic,retain) NSArray * playerIDs;                  //@synthesize playerIDs=_playerIDs - In the implementation block
@property (assign,nonatomic) BOOL forcePicker;                     //@synthesize forcePicker=_forcePicker - In the implementation block
@property (nonatomic,copy) id completionHandler;                   //@synthesize completionHandler=_completionHandler - In the implementation block
@property (nonatomic,retain) GKGame * game; 
+(id)_remoteViewControllerInterface;
+(id)_exportedInterface;
-(void)constructPrivateViewController;
-(BOOL)_useBackdropViewForWindowBackground;
-(void)setDefaultMessage:(id)arg1 ;
-(id)defaultMessage;
-(void)setForcePicker:(BOOL)arg1 ;
-(void)setPlayerIDs:(id)arg1 ;
-(id)playerIDs;
-(BOOL)forcePicker;
-(void)setChallenge:(id)arg1 playerIDs:(id)arg2 defaultMessage:(id)arg3 forcePicker:(BOOL)arg4 ;
-(id)init;
-(/*^block*/ id)completionHandler;
-(void)setCompletionHandler:(/*^block*/ id)arg1 ;
-(id)challenge;
-(void)setChallenge:(id)arg1 ;
@end

