/*
* This header is generated by classdump-dyld 0.1
* on Thursday, November 28, 2013 at 3:59:43 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/

#import <Maps/MapsSyncedClient.h>

@protocol OS_dispatch_queue;
@class NSMutableArray, NSObject, MapsSyncManager, NSString, NSArray;

@interface Bookmarks : NSObject <MapsSyncedClient> {

	NSMutableArray* _bookmarks;
	BOOL _savingEnabled;
	BOOL _hasPendingChanges;
	NSObject<OS_dispatch_queue>* _saveQ;
	MapsSyncManager* _syncManager;

}

@property (nonatomic,retain) MapsSyncManager * syncManager;                  //@synthesize syncManager=_syncManager - In the implementation block
@property (nonatomic,readonly) NSString * syncIdentifier; 
@property (nonatomic,readonly) NSArray * syncedItems; 
@property (nonatomic,readonly) BOOL syncSupportsKVO; 
@property (nonatomic,readonly) BOOL syncInvertedOrdering; 
@property (nonatomic,readonly) BOOL syncShouldUseItemPositions; 
@property (nonatomic,readonly) BOOL syncShouldUseCustomStore; 
+(id)sharedBookmarks;
-(id)orderedBookmarks;
-(id)syncIdentifier;
-(void)_madeChanges;
-(id)newSyncedItemForSyncData:(id)arg1 ;
-(BOOL)shouldAddSyncedItem:(id)arg1 atIndex:(unsigned)arg2 ;
-(void)insertSyncedItems:(id)arg1 atIndexes:(id)arg2 ;
-(void)removeSyncedItemsAtIndexes:(id)arg1 ;
-(void)updateSyncedItemAtIndexes:(id)arg1 ;
-(void)syncManagerDidUpdateSyncedItems:(id)arg1 ;
-(id)syncedItems;
-(BOOL)syncSupportsKVO;
-(void)_cleanBookmark:(id)arg1 ;
-(id)newSearchResultForPlaceBookmark:(id)arg1 ;
-(void)addBookmark:(id)arg1 ;
-(void)replaceBookmark:(id)arg1 withBookmark:(id)arg2 ;
-(void)removeBookmarkAtIndex:(unsigned)arg1 ;
-(void)moveBookmarkAtIndex:(unsigned)arg1 toIndex:(unsigned)arg2 ;
-(id)syncManager;
-(void)setSyncManager:(id)arg1 ;
-(void)dealloc;
-(id)init;
-(void)beginChanges;
-(void)endChanges;
-(void)_saveBookmarks;
@end

