/*
* This header is generated by classdump-dyld 0.1
* on Thursday, November 28, 2013 at 3:59:58 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/

#import <Maps/Maps-Structs.h>
#import <Maps/MapsChromeTopBarContent.h>

@protocol MNNavigationOverviewBarDelegate;
@class TopBarTitleView, UIBarButtonItem, MNNavigationOverviewBarButtonView, MainChromeViewController, NSString;

@interface MNNavigationOverviewBar : NSObject <MapsChromeTopBarContent> {

	<MNNavigationOverviewBarDelegate>* _delegate;
	TopBarTitleView* _titleView;
	UIBarButtonItem* _title;
	UIBarButtonItem* _end;
	UIBarButtonItem* _overview;
	BOOL _overviewHidden;
	MNNavigationOverviewBarButtonView* _endButtonView;
	MNNavigationOverviewBarButtonView* _overviewButtonView;
	BOOL _isDimmed;
	MainChromeViewController* _chromeViewController;

}

@property (assign,nonatomic) <MNNavigationOverviewBarDelegate> * delegate;                 //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) NSString * titleLabelText; 
@property (assign,nonatomic) BOOL compact; 
@property (assign,nonatomic) BOOL isDimmed;                                                //@synthesize isDimmed=_isDimmed - In the implementation block
@property (assign,nonatomic) MainChromeViewController * chromeViewController;              //@synthesize chromeViewController=_chromeViewController - In the implementation block
-(id)toolbarItemsForIdiom:(int)arg1 ;
-(void)topBarSizeWillChange:(CGSize)arg1 ;
-(void)topBarSizeDidChange:(CGSize)arg1 ;
-(BOOL)requiresSuppressingRepositioningAnimations;
-(id)chromeViewController;
-(void)setChromeViewController:(id)arg1 ;
-(void)setIsDimmed:(BOOL)arg1 ;
-(void)setShowsDimmedDisplay:(BOOL)arg1 animation:(id)arg2 ;
-(void)setOverviewButtonHidden:(BOOL)arg1 animated:(BOOL)arg2 ;
-(id)initForActivity:(int)arg1 ;
-(void)setTitleLabelText:(id)arg1 ;
-(id)titleLabelText;
-(void)setDetailLabelText:(id)arg1 ;
-(void)_endTapped;
-(id)_buttonWithTitle:(id)arg1 action:(SEL)arg2 ;
-(void)_overviewTapped;
-(void)delayRefreshForAnimation;
-(void)dealloc;
-(void)setDelegate:(id)arg1 ;
-(id)delegate;
-(BOOL)isDimmed;
-(BOOL)compact;
-(void)setCompact:(BOOL)arg1 ;
@end

