/*
* This header is generated by classdump-dyld 0.1
* on Thursday, November 28, 2013 at 3:59:49 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/


@protocol PlaceViewControllerDelegate <NSObject>
@optional
-(void)placeViewController:(id)arg1 didSelectDirectionsToAddressWithIdentifier:(int)arg2;
-(void)placeViewController:(id)arg1 didSelectDirectionsFromAddressWithIdentifier:(int)arg2;
-(void)placeViewController:(id)arg1 didSelectTransitDirectionsToAddressWithIdentifier:(int)arg2;
-(void)placeViewController:(id)arg1 didSelectAddToBookmarksWithAddressIdentifier:(int)arg2 title:(id)arg3;
-(void)placeViewController:(id)arg1 didSelectActivityOfType:(id)arg2 completed:(BOOL)arg3;
-(void)placeViewControllerDidSelectRemovePin:(id)arg1;
-(void)placeViewControllerDidSelectReportAProblem:(id)arg1;
-(void)placeViewControllerDidSelectShareLocation:(id)arg1;
-(void)placeViewController:(id)arg1 didSelectHomePage:(id)arg2;
-(void)placeViewController:(id)arg1 didSelectPhoneNumber:(id)arg2;
-(void)placeViewControllerDidSelectDisplayedAddress:(id)arg1;
-(void)placeViewControllerDidDismiss:(id)arg1;
-(void)placeViewControllerDidSelectInfo:(id)arg1;
-(void)placeViewControllerDidSelectPhotos:(id)arg1;
-(void)placeViewControllerDidSelectReviews:(id)arg1;
-(void)placeViewControllerDidLaunchYelp:(id)arg1;
-(void)placeViewController:(id)arg1 didSelectAddressWithIdentifier:(int)arg2;
-(BOOL)placeViewControllerShouldShowAddMergeContactSheet:(id)arg1;
@end

