/*
* This header is generated by classdump-dyld 0.1
* on Thursday, November 28, 2013 at 3:59:52 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/


@class MKWorldView, NSArray, SearchResult, NSMutableArray, SearchPinsManagerShowSearchResultsAnimation;

@interface SearchPinsManager : NSObject {

	MKWorldView* _worldView;
	NSArray* _searchPins;
	SearchResult* _startPin;
	SearchResult* _hiddenStartPin;
	SearchResult* _endPin;
	SearchResult* _droppedPin;
	SearchResult* _parkingPin;
	NSMutableArray* _hiddenSearchPins;
	BOOL _animatingStartPin;
	BOOL _animatingEndPin;
	/*^block*/ id _routePinsAnimationCompletedHandler;
	SearchPinsManagerShowSearchResultsAnimation* _showSearchResultsAnimation;

}

@property (nonatomic,retain) MKWorldView * worldView;                          //@synthesize worldView=_worldView - In the implementation block
@property (nonatomic,retain) NSArray * searchPins;                             //@synthesize searchPins=_searchPins - In the implementation block
@property (nonatomic,retain) SearchResult * startPin;                          //@synthesize startPin=_startPin - In the implementation block
@property (nonatomic,retain) SearchResult * endPin;                            //@synthesize endPin=_endPin - In the implementation block
@property (nonatomic,retain) SearchResult * droppedPin;                        //@synthesize droppedPin=_droppedPin - In the implementation block
@property (nonatomic,retain) SearchResult * parkingPin;                        //@synthesize parkingPin=_parkingPin - In the implementation block
@property (nonatomic,retain) SearchResult * hiddenStartPin;                    //@synthesize hiddenStartPin=_hiddenStartPin - In the implementation block
@property (nonatomic,retain) NSMutableArray * hiddenSearchPins;                //@synthesize hiddenSearchPins=_hiddenSearchPins - In the implementation block
@property (nonatomic,copy) id routePinsAnimationCompletedHandler;              //@synthesize routePinsAnimationCompletedHandler=_routePinsAnimationCompletedHandler - In the implementation block
-(void)replaceSearchResult:(id)arg1 withSearchResult:(id)arg2 ;
-(id)worldView;
-(void)setWorldView:(id)arg1 ;
-(void)hideStartPin;
-(void)showStartPin;
-(void)setSearchPins:(id)arg1 selectedPin:(id)arg2 animated:(BOOL)arg3 ;
-(void)setDroppedPin:(id)arg1 animated:(BOOL)arg2 ;
-(void)setParkingPin:(id)arg1 animated:(BOOL)arg2 ;
-(id)startPin;
-(id)endPin;
-(void)clearDirectionsPins;
-(void)setStartPin:(id)arg1 endPin:(id)arg2 animated:(BOOL)arg3 completion:(/*^block*/ id)arg4 ;
-(void)clearDroppedPin;
-(void)clearSearchPins;
-(void)hideSearchPinsExcept:(id)arg1 ;
-(void)setSearchPinsFromSearchManagerResults:(id)arg1 scrollToResults:(BOOL)arg2 ;
-(void)worldViewDidBecomeFullyDrawn;
-(void)restoreHiddenSearchPins;
-(void)worldViewFinishedAnimatingPins:(id)arg1 ;
-(void)clearParkingPin;
-(void)_clearShowSearchResultsAnimation;
-(void)setHiddenSearchPins:(id)arg1 ;
-(void)setHiddenStartPin:(id)arg1 ;
-(void)setRoutePinsAnimationCompletedHandler:(/*^block*/ id)arg1 ;
-(id)_setOfPinsForPinType:(unsigned)arg1 ;
-(void)_completeShowSearchResultsAnimation;
-(void)_clearStartPin;
-(void)_clearEndPin;
-(void)setStartPin:(id)arg1 ;
-(void)setEndPin:(id)arg1 ;
-(void)setDroppedPin:(id)arg1 ;
-(void)setParkingPin:(id)arg1 ;
-(id)hiddenStartPin;
-(void)hideSearchPinsExcept:(id)arg1 forStaticDisplay:(BOOL)arg2 ;
-(void)setSearchPinsFromSearchManagerResults:(id)arg1 scrollToResults:(BOOL)arg2 animated:(BOOL)arg3 ;
-(id)pinsForPinType:(unsigned)arg1 ;
-(id)searchPins;
-(void)setSearchPins:(id)arg1 ;
-(id)droppedPin;
-(id)parkingPin;
-(id)hiddenSearchPins;
-(/*^block*/ id)routePinsAnimationCompletedHandler;
-(id)worldView:(id)arg1 viewForAnnotation:(id)arg2 ;
-(void)dealloc;
@end

