/*
* This header is generated by classdump-dyld 0.1
* on Thursday, November 28, 2013 at 3:59:46 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/


@protocol SearchManagerObserver <NSObject>
@optional
-(void)searchManagerDidClearSearchResults:(id)arg1;
-(void)searchManager:(id)arg1 willPerformSearchForQuery:(id)arg2;
-(void)searchManager:(id)arg1 didReceiveResults:(id)arg2 scrollToResults:(BOOL)arg3;
-(void)searchManagerSearchFailed:(id)arg1 withError:(id)arg2;
-(void)searchManagerSearchCanceled:(id)arg1;
-(void)searchManager:(id)arg1 didReceiveRefinementResults:(id)arg2;
-(void)searchManager:(id)arg1 didReceiveSpellingSuggestion:(id)arg2 scrollToResults:(BOOL)arg3;
@end

