/*
* This header is generated by classdump-dyld 0.1
* on Thursday, November 28, 2013 at 3:59:46 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/


@protocol SettingsControllerDelegate <NSObject>
@required
-(void)settingsControllerWillDismissSettings:(id)arg1;
-(void)settingsControllerDidDismissSettings:(id)arg1;
-(void)settingsController:(id)arg1 didSetViewMode:(int)arg2;
-(void)settingsControllerDidRequestPinDrop:(id)arg1;
-(void)settingsControllerDidRequestPrint:(id)arg1;
-(void)settingsControllerDidRequestReportAProblem:(id)arg1;
-(void)settingsController:(id)arg1 didSetShowingTraffic:(BOOL)arg2;
-(void)settingsControllerDidRequestAttributionLegalese:(id)arg1;
-(void)settingsControllerDidRequestEnvironments:(id)arg1;
-(int)viewMode;
@end

