/*
* This header is generated by classdump-dyld 0.1
* on Thursday, November 28, 2013 at 3:59:43 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Maps.app/Maps
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIView.h>

@interface StarkTableViewCellContentView : UIView {

	/*^block*/ id _layoutHandler;

}

@property (nonatomic,copy) id layoutHandler;              //@synthesize layoutHandler=_layoutHandler - In the implementation block
-(/*^block*/ id)layoutHandler;
-(void)setLayoutHandler:(/*^block*/ id)arg1 ;
-(void)dealloc;
-(void)layoutSubviews;
@end

