#import <libxpc.dylib/OS_xpc_object.h>
#import <libxpc.dylib/OS_xpc_connection.h>
#import <libxpc.dylib/OS_xpc_service.h>
#import <libxpc.dylib/OS_xpc_null.h>
#import <libxpc.dylib/OS_xpc_bool.h>
#import <libxpc.dylib/OS_xpc_int64.h>
#import <libxpc.dylib/OS_xpc_uint64.h>
#import <libxpc.dylib/OS_xpc_double.h>
#import <libxpc.dylib/OS_xpc_pointer.h>
#import <libxpc.dylib/OS_xpc_date.h>
#import <libxpc.dylib/OS_xpc_data.h>
#import <libxpc.dylib/OS_xpc_string.h>
#import <libxpc.dylib/OS_xpc_uuid.h>
#import <libxpc.dylib/OS_xpc_fd.h>
#import <libxpc.dylib/OS_xpc_shmem.h>
#import <libxpc.dylib/OS_xpc_mach_send.h>
#import <libxpc.dylib/OS_xpc_array.h>
#import <libxpc.dylib/OS_xpc_dictionary.h>
#import <libxpc.dylib/OS_xpc_error.h>
#import <libxpc.dylib/OS_xpc_domain.h>
#import <libxpc.dylib/OS_xpc_endpoint.h>
#import <libxpc.dylib/OS_xpc_serializer.h>
#import <libxpc.dylib/OS_xpc_pipe.h>
#import <libxpc.dylib/OS_xpc_mach_recv.h>
#import <libxpc.dylib/OS_xpc_bundle.h>
#import <libxpc.dylib/OS_xpc_service_instance.h>
#import <libxpc.dylib/OS_xpc_activity.h>
