/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 1:39:08 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Music.app/Music
* classdump-dyld is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/


@protocol MSCarDisplayServiceProvider <NSObject>
@required
-(void)changeRepeatType:(unsigned)arg1;
-(void)changeShuffleType:(unsigned)arg1;
-(void)reloadPlayer:(id)arg1 radioStation:(id)arg2 options:(id)arg3 completion:(/*^block*/ id)arg4;
-(void)reloadPlayer:(id)arg1 mediaQuery:(id)arg2 options:(id)arg3;
-(void)reloadPlayer:(id)arg1 geniusMixPlaylist:(id)arg2 options:(id)arg3;
@end

