/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 1:39:39 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/WebSheet.app/WebSheet
* classdump-dyld is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/

#import <WebSheet/WebSheet-Structs.h>
#import <UIKit/UIView.h>
#import <UIKit/UIActionSheetDelegate.h>
#import <UIKit/UIWebViewDelegate.h>
#import <UIKit/UIWebViewPrivateDelegate.h>

@class UIWebView, WebSheetPolicyDelegate, UIView, UINavigationBar, UINavigationItem, UIBarButtonItem, UIImageView, UILabel, NSMutableArray, SheetController, WebUIAuthenticationManager, WebUIDownloadManager, UIActionSheet, NSTimer, NSURL, NSDictionary;

@interface WebSheetView : UIView <UIActionSheetDelegate, UIWebViewDelegate, UIWebViewPrivateDelegate> {

	UIWebView* _webView;
	WebSheetPolicyDelegate* _policyDelegate;
	UIView* _headerBackgroundView;
	UINavigationBar* _headerView;
	UINavigationItem* _navigationItem;
	UIBarButtonItem* _backButtonItem;
	UIBarButtonItem* _forwardButtonItem;
	UIBarButtonItem* _cancelDoneBarButtonItem;
	UIBarButtonItem* _backForwardButton;
	UIImageView* _lockIconView;
	UILabel* _addressLabel;
	UILabel* _ssidLabel;
	float _statusBarHeight;
	CFURLStorageSessionRef _storageSession;
	NSMutableArray* _alerts;
	SheetController* _sheetController;
	ProbeContext* _probeContext;
	int _orientation;
	WebUIAuthenticationManager* _authenticationManager;
	WebUIDownloadManager* _downloadManager;
	BOOL _inDoneState;
	int _springboardPID;
	UIActionSheet* _stayConnectedActionSheet;
	NSTimer* _captiveProbeDispatchTimer;
	BOOL _shouldShowStayConnectedOptions;
	BOOL _mediaPlaybackEnabled;
	BOOL _hasEVCert;
	NSURL* _currentURL;
	NSDictionary* _proxyConfiguration;

}

@property (nonatomic,retain) UIWebView * webView;                              //@synthesize webView=_webView - In the implementation block
@property (nonatomic,retain) NSURL * currentURL;                               //@synthesize currentURL=_currentURL - In the implementation block
@property (assign,nonatomic) int orientation;                                  //@synthesize orientation=_orientation - In the implementation block
@property (assign,nonatomic) BOOL shouldShowStayConnectedOptions;              //@synthesize shouldShowStayConnectedOptions=_shouldShowStayConnectedOptions - In the implementation block
@property (assign,nonatomic) BOOL mediaPlaybackEnabled;                        //@synthesize mediaPlaybackEnabled=_mediaPlaybackEnabled - In the implementation block
@property (nonatomic,copy) NSDictionary * proxyConfiguration;                  //@synthesize proxyConfiguration=_proxyConfiguration - In the implementation block
@property (assign,nonatomic) BOOL hasEVCert;                                   //@synthesize hasEVCert=_hasEVCert - In the implementation block
-(void)setMediaPlaybackEnabled:(BOOL)arg1 ;
-(BOOL)mediaPlaybackEnabled;
-(void)doneTapped;
-(void)addAlert:(id)arg1 ;
-(id)containerViewForAuthenticationPanel;
-(void)_continueAfterCertificateAlertWithContext:(id)arg1 ;
-(id)currentURL;
-(void)_showGenericDownloadAlert;
-(void)_showProfileInstallAlert;
-(void)_loadRequest:(id)arg1 inFrame:(id)arg2 ;
-(id)_titleForError:(id)arg1 ;
-(id)_sheetController;
-(void)setInterfaceName:(CFStringRef)arg1 ;
-(void)setCaptiveNetworkCookie:(unsigned long)arg1 ;
-(void)setCurrentURL:(id)arg1 ;
-(void)setSSID:(CFStringRef)arg1 ;
-(void)setProxyConfiguration:(id)arg1 ;
-(void)setShouldShowStayConnectedOptions:(BOOL)arg1 ;
-(void)updateToDoneButton;
-(void)_backButtonPressed;
-(void)_forwardButtonPressed;
-(id)_promptLabelFont;
-(id)_lockIconImage;
-(BOOL)_shouldShowPromptLabels;
-(void)_updateAddress;
-(float)_promptLabelFontLineHeight;
-(float)_addressBaselineOffsetY;
-(BOOL)_isSecureAddress;
-(id)_evCertColor;
-(id)_lockIconImageWithTintColor:(id)arg1 ;
-(id)_evCertLockIconImage;
-(void)_dismissWebSheetWithCaptiveWebSheetResult:(int)arg1 ;
-(void)_startCaptiveProbeDispatchTimer;
-(id)_specializedMessageForError:(id)arg1 ;
-(void)setHasEVCert:(BOOL)arg1 ;
-(void)_showProfileDownloadAlert;
-(void)_stopCaptiveProbeDispatchTimer;
-(void)_updateBackForwardButtons;
-(void)_captiveProbeDispatchTimerDidFire:(id)arg1 ;
-(BOOL)shouldShowStayConnectedOptions;
-(id)proxyConfiguration;
-(BOOL)hasEVCert;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)layoutSubviews;
-(int)orientation;
-(void)actionSheet:(id)arg1 didDismissWithButtonIndex:(int)arg2 ;
-(id)webView;
-(void)setWebView:(id)arg1 ;
-(void)setOrientation:(int)arg1 ;
-(void)webView:(id)arg1 didFailLoadWithError:(id)arg2 ;
-(BOOL)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(int)arg3 ;
-(void)uiWebView:(id)arg1 decidePolicyForMIMEType:(id)arg2 request:(id)arg3 frame:(id)arg4 decisionListener:(id)arg5 ;
-(void)webViewDidStartLoad:(id)arg1 ;
-(void)uiWebView:(id)arg1 didCommitLoadForFrame:(id)arg2 ;
-(void)uiWebView:(id)arg1 didReceiveTitle:(id)arg2 forFrame:(id)arg3 ;
-(id)uiWebView:(id)arg1 connectionPropertiesForResource:(id)arg2 dataSource:(id)arg3 ;
-(id)uiWebView:(id)arg1 resource:(id)arg2 willSendRequest:(id)arg3 redirectResponse:(id)arg4 fromDataSource:(id)arg5 ;
-(void)webViewDidFinishLoad:(id)arg1 ;
-(id)uiWebView:(id)arg1 identifierForInitialRequest:(id)arg2 fromDataSource:(id)arg3 ;
-(void)uiWebView:(id)arg1 resource:(id)arg2 didFinishLoadingFromDataSource:(id)arg3 ;
-(void)uiWebView:(id)arg1 resource:(id)arg2 didFailLoadingWithError:(id)arg3 fromDataSource:(id)arg4 ;
-(void)uiWebView:(id)arg1 resource:(id)arg2 didReceiveAuthenticationChallenge:(id)arg3 fromDataSource:(id)arg4 ;
-(void)uiWebView:(id)arg1 resource:(id)arg2 didCancelAuthenticationChallenge:(id)arg3 fromDataSource:(id)arg4 ;
-(void)cancelTapped;
-(BOOL)_handleCertificateError:(id)arg1 ;
-(void)_updateTitle;
-(void)sheetControllerDidShowSheet:(id)arg1 ;
-(void)sheetController:(id)arg1 performAction:(int)arg2 forAlert:(id)arg3 ;
-(void)sheetControllerDidHideSheet:(id)arg1 ;
-(void)cancelFromAuthenticationManager:(id)arg1 forChallenge:(id)arg2 ;
-(void)logInFromAuthenticationManager:(id)arg1 withCredential:(id)arg2 forChallenge:(id)arg3 ;
-(void)downloadManager:(id)arg1 downloadDidFail:(id)arg2 ;
-(void)downloadManager:(id)arg1 hasData:(id)arg2 forFinishedDownload:(id)arg3 ;
@end

