/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 1:39:35 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Weather.app/Weather
* classdump-dyld is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/


@protocol TabBarDelegate
@required
-(void)tabBarAddTab:(id)arg1;
-(void)tabBar:(id)arg1 closeItem:(id)arg2;
-(void)tabBarShowMoreTabs:(id)arg1;
-(BOOL)tabBar:(id)arg1 canCloseItem:(id)arg2;
-(void)tabBar:(id)arg1 activateItem:(id)arg2;
-(BOOL)tabBar:(id)arg1 canMoveItem:(id)arg2;
-(void)tabBar:(id)arg1 moveItem:(id)arg2 overItem:(id)arg3;
@end

