/*
* This header is generated by strong_classdump 0.1
* on Wednesday, November 27, 2013 at 12:02:11 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Weather.app/Weather
* strong_classdump is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/

#import <Weather/Weather-Structs.h>
#import <UIKit/UICollectionViewFlowLayout.h>

@class NSIndexPath;

@interface WAPagedFlowLayout : UICollectionViewFlowLayout {

	NSIndexPath* _targetIndexPath;

}

@property (nonatomic,retain) NSIndexPath * targetIndexPath;              //@synthesize targetIndexPath=_targetIndexPath - In the implementation block
-(void)setTargetIndexPath:(id)arg1 ;
-(id)targetIndexPath;
-(void)dealloc;
-(CGPoint)targetContentOffsetForProposedContentOffset:(CGPoint)arg1 withScrollingVelocity:(CGPoint)arg2 ;
@end

