/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 1:39:35 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Weather.app/Weather
* classdump-dyld is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/

#import <Weather/Weather-Structs.h>
#import <Weather/WACardLayout.h>

@class NSIndexPath;

@interface WAReorderableCardLayout : WACardLayout {

	BOOL _isReordering;
	NSIndexPath* _deleteIndexPath;
	NSIndexPath* _pivotIndexPath;
	int _initialDragIndex;
	int _currentDragIndex;

}

@property (nonatomic,retain) NSIndexPath * deleteIndexPath;              //@synthesize deleteIndexPath=_deleteIndexPath - In the implementation block
@property (nonatomic,retain) NSIndexPath * pivotIndexPath;               //@synthesize pivotIndexPath=_pivotIndexPath - In the implementation block
@property (nonatomic,readonly) int initialDragIndex;                     //@synthesize initialDragIndex=_initialDragIndex - In the implementation block
@property (assign,nonatomic) int currentDragIndex;                       //@synthesize currentDragIndex=_currentDragIndex - In the implementation block
-(id)pivotIndexPath;
-(void)setPivotIndexPath:(id)arg1 ;
-(int)targetIndexForProposedStartIndex:(int)arg1 inRect:(CGRect)arg2 ;
-(int)currentDragIndex;
-(int)indexForItemAtPoint:(CGPoint)arg1 ;
-(void)setCurrentDragIndex:(int)arg1 ;
-(void)beginReorderingWithInitialDragIndex:(int)arg1 ;
-(int)initialDragIndex;
-(void)setDeleteIndexPath:(id)arg1 ;
-(id)deleteIndexPath;
-(BOOL)isReordering;
-(void)dealloc;
-(CGPoint)targetContentOffsetForProposedContentOffset:(CGPoint)arg1 ;
-(id)finalLayoutAttributesForDisappearingItemAtIndexPath:(id)arg1 ;
-(void)endReordering;
@end

