/*
* This header is generated by strong_classdump 0.1
* on Wednesday, November 27, 2013 at 12:02:11 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Weather.app/Weather
* strong_classdump is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/

#import <Weather/Weather-Structs.h>
#import <UIKit/UIScrollView.h>
#import <UIKit/UIScrollViewDelegate.h>

@protocol WeatherScrollerDelegate;
@class , UIImageView, UIView, UIImage;

@interface WeatherScroller : UIScrollView <UIScrollViewDelegate> {

	<WeatherScrollerDelegate>* _weatherScrollerDelegate;
	UIImageView* _backgroundHeader;
	UIImageView* _backgroundImage;
	UIView* _todayHeader;
	UIView* _todayHourlyForecasts;
	UIView* _tomorrowHeader;
	UIView* _tomorrowHourlyForecasts;
	UIView* _unusedDaysFooter;
	UIImageView* _infoFooter;
	UIImageView* _todayBackground;
	UIImageView* _tomorrowBackground;
	UIImageView* _unusedBackground;
	UIImageView* _tomorrowCastShadow;
	UIImageView* _extraDaysCastShadow;
	UIImageView* _footerCastShadow;
	BOOL _isDay;
	BOOL _isOpeningOrClosing;
	BOOL _isSlammingShut;
	BOOL _isDroppedShut;
	UIImage* _stretchableDrawer;
	UIImageView* _topDrawerShadow;
	UIImageView* _bottomDrawerShadow;
	UIImageView* _todayTopBevel;
	UIImageView* _tomorrowTopBevel;

}

@property (assign,nonatomic) BOOL isOpeningOrClosing;                                          //@synthesize isOpeningOrClosing=_isOpeningOrClosing - In the implementation block
@property (assign,nonatomic) <WeatherScrollerDelegate> * weatherScrollerDelegate;              //@synthesize weatherScrollerDelegate=_weatherScrollerDelegate - In the implementation block
@property (nonatomic,retain) UIImage * stretchableDrawer;                                      //@synthesize stretchableDrawer=_stretchableDrawer - In the implementation block
@property (nonatomic,retain) UIImageView * topDrawerShadow;                                    //@synthesize topDrawerShadow=_topDrawerShadow - In the implementation block
@property (nonatomic,retain) UIImageView * bottomDrawerShadow;                                 //@synthesize bottomDrawerShadow=_bottomDrawerShadow - In the implementation block
@property (nonatomic,retain) UIImageView * todayTopBevel;                                      //@synthesize todayTopBevel=_todayTopBevel - In the implementation block
@property (nonatomic,retain) UIImageView * tomorrowTopBevel;                                   //@synthesize tomorrowTopBevel=_tomorrowTopBevel - In the implementation block
-(void)_createHeadersAndFooters:(id)arg1 ;
-(void)_createShadows;
-(void)_updateHeaderBackgrounds;
-(void)_updateBevelAlphas;
-(void)_layoutShadows;
-(id)initWithFrame:(CGRect)arg1 dictionary:(id)arg2 ;
-(void)showInfoShadow:(BOOL)arg1 ;
-(void)slide:(id)arg1 ;
-(void)showBevels:(BOOL)arg1 ;
-(CGPoint)timeToPartiallyOpenDrawer:(BOOL)arg1 ;
-(void)openDrawerCompletely:(BOOL)arg1 ;
-(CGPoint)timeToPartiallyCloseDrawer:(BOOL)arg1 ;
-(void)closeDrawer:(id)arg1 ;
-(float)closeDistance;
-(void)setDrawerPosition:(float)arg1 ;
-(void)prepareForClosureAnimation;
-(BOOL)isOpeningOrClosing;
-(void)setIsOpeningOrClosing:(BOOL)arg1 ;
-(id)weatherScrollerDelegate;
-(void)setWeatherScrollerDelegate:(id)arg1 ;
-(id)stretchableDrawer;
-(void)setStretchableDrawer:(id)arg1 ;
-(id)topDrawerShadow;
-(void)setTopDrawerShadow:(id)arg1 ;
-(id)bottomDrawerShadow;
-(void)setBottomDrawerShadow:(id)arg1 ;
-(id)todayTopBevel;
-(void)setTodayTopBevel:(id)arg1 ;
-(id)tomorrowTopBevel;
-(void)setTomorrowTopBevel:(id)arg1 ;
-(void)dealloc;
-(void)layoutSubviews;
-(void)scrollViewDidScroll:(id)arg1 ;
-(void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2 ;
-(void)scrollViewDidEndDecelerating:(id)arg1 ;
-(void)setContentOffset:(CGPoint)arg1 ;
-(float)maxDistance;
@end

