/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 10:51:55 PM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /usr/libexec/BackupAgent2
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/

#import <backupd/MBPlugin.h>

@interface MBAppleCarePlugin : NSObject <MBPlugin>
-(id)endedBackupWithEngine:(id)arg1 error:(id)arg2 ;
-(id)endedRestoreWithEngine:(id)arg1 error:(id)arg2 ;
-(void)logEventWithSubtype:(id)arg1 code:(int)arg2 ;
@end

