/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 10:51:55 PM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /usr/libexec/BackupAgent2
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/


@class SSKeyValueStore;

@interface MBiTunesStoreKVS : NSObject {

	SSKeyValueStore* _KVS;

}

@property (nonatomic,readonly) SSKeyValueStore * KVS;              //@synthesize KVS=_KVS - In the implementation block
+(id)iTunesStoreKVS;
+(id)mergeKnownAccountsByDSID:(id)arg1 into:(id)arg2 ;
-(id)valueForDomain:(id)arg1 key:(id)arg2 ;
-(id)knownAccounts;
-(id)knownAccountsByDSID;
-(void)setKnownAccounts:(id)arg1 ;
-(id)KVS;
-(void)dealloc;
-(id)init;
-(void)setValue:(id)arg1 forDomain:(id)arg2 key:(id)arg3 ;
-(void)setValuesWithDictionary:(id)arg1 forDomain:(id)arg2 ;
-(void)removeAllValues;
@end

