/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 1:38:34 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/MobileCal.app/MobileCal
* classdump-dyld is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/


#import <MobileCal/MobileCal-Structs.h>
@class NSOperationQueue, NSMutableSet;

@interface _BackgroundViewRenderManager : NSObject {

	NSOperationQueue* _queue;
	NSMutableSet* _viewsInQueue;
	opaque_pthread_mutex_t _lock;

}
+(id)sharedManager;
-(void)addViewToQueue:(id)arg1 ;
-(void)removeViewFromQueue:(id)arg1 ;
-(void)cancelAllRendering;
-(void)dealloc;
-(id)init;
-(void).cxx_destruct;
@end

