/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 10:35:20 PM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/MobileCal.app/MobileCal
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>
#import <AdSheet/EKStyleProvider.h>
#import <MobileCal/PopoverContentView.h>

@class CalendarModel, UINavigationController;

@interface CalendarsViewController : UIViewController <EKStyleProvider, PopoverContentView> {

	/*^block*/ id _doneBlock;
	CalendarModel* _model;
	UINavigationController* _embeddedNavigationController;

}

@property (nonatomic,copy) id doneBlock;                                                         //@synthesize doneBlock=_doneBlock - In the implementation block
@property (nonatomic,retain) CalendarModel * model;                                              //@synthesize model=_model - In the implementation block
@property (nonatomic,retain) UINavigationController * embeddedNavigationController;              //@synthesize embeddedNavigationController=_embeddedNavigationController - In the implementation block
-(void)setEmbeddedNavigationController:(id)arg1 ;
-(id)embeddedNavigationController;
-(/*^block*/ id)doneBlock;
-(void)setDoneBlock:(/*^block*/ id)arg1 ;
-(void)_saveFilterAndNotify;
-(id)initWithModel:(id)arg1 ;
-(void)calendarChooserSelectionDidChange:(id)arg1 ;
-(void)calendarChooserDidFinish:(id)arg1 ;
-(void)refreshCalendarsButtonPressed;
-(id)backgroundColor;
-(unsigned)supportedInterfaceOrientations;
-(void)loadView;
-(void)viewDidDisappear:(BOOL)arg1 ;
-(id)model;
-(BOOL)canDismiss;
-(void)setModel:(id)arg1 ;
-(void).cxx_destruct;
@end

