/*
* This header is generated by strong_classdump 0.1
* on Wednesday, November 27, 2013 at 12:01:12 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/MobileCal.app/MobileCal
* strong_classdump is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/

#import <MobileCal/MobileCal-Structs.h>
#import <UIKit/UIViewController.h>
#import <MobileCal/CalendarMessagesTableViewControllerDelegate.h>

@protocol CalendarMessagesViewControllerDelegate;
@class CalendarModel, EKEvent, , CalendarMessagesTableViewController, CalendarMessagesHistoryTableViewController, UIView, UISegmentedControl, NSString;

@interface CalendarMessagesViewController : UIViewController <CalendarMessagesTableViewControllerDelegate> {

	CalendarModel* _model;
	EKEvent* _eventToSelect;
	<CalendarMessagesViewControllerDelegate>* _delegate;
	int _visibleView;
	CalendarMessagesTableViewController* _notificationsViewController;
	CalendarMessagesHistoryTableViewController* _recentNotificationsViewController;
	UIView* _messagesContentView;
	UISegmentedControl* _segmentedControl;
	NSString* _eventUUIDToInspect;
	CGSize _largestSize;

}

@property (nonatomic,retain) CalendarMessagesTableViewController * notificationsViewController;                           //@synthesize notificationsViewController=_notificationsViewController - In the implementation block
@property (nonatomic,retain) CalendarMessagesHistoryTableViewController * recentNotificationsViewController;              //@synthesize recentNotificationsViewController=_recentNotificationsViewController - In the implementation block
@property (nonatomic,retain) UIView * messagesContentView;                                                                //@synthesize messagesContentView=_messagesContentView - In the implementation block
@property (nonatomic,retain) UISegmentedControl * segmentedControl;                                                       //@synthesize segmentedControl=_segmentedControl - In the implementation block
@property (nonatomic,retain) NSString * eventUUIDToInspect;                                                               //@synthesize eventUUIDToInspect=_eventUUIDToInspect - In the implementation block
@property (assign,nonatomic) CGSize largestSize;                                                                          //@synthesize largestSize=_largestSize - In the implementation block
-(id)initWithModel:(id)arg1 eventToSelect:(id)arg2 delegate:(id)arg3 ;
-(void)calendarNotificationsTableViewControllerShouldClose:(id)arg1 animated:(BOOL)arg2 ;
-(void)calendarNotificationsTableViewController:(id)arg1 inspectEvent:(id)arg2 ;
-(void)setNotificationsViewController:(id)arg1 ;
-(id)notificationsViewController;
-(void)setRecentNotificationsViewController:(id)arg1 ;
-(id)recentNotificationsViewController;
-(void)segementedControlValueChanged:(id)arg1 ;
-(void)_setVisibleView:(int)arg1 shouldSetSegmentedControl:(BOOL)arg2 ;
-(void)setVisibleView:(int)arg1 ;
-(void)setEventUUIDToInspect:(id)arg1 ;
-(id)showNewSection;
-(id)showRepliedSection;
-(id)messagesContentView;
-(void)setMessagesContentView:(id)arg1 ;
-(id)eventUUIDToInspect;
-(CGSize)largestSize;
-(void)setLargestSize:(CGSize)arg1 ;
-(void)setSegmentedControl:(id)arg1 ;
-(void)viewWillAppear:(BOOL)arg1 ;
-(CGSize)preferredContentSize;
-(void)viewDidLoad;
-(void)loadView;
-(void)viewDidDisappear:(BOOL)arg1 ;
-(id)segmentedControl;
-(void).cxx_destruct;
@end

