/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 10:35:18 PM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/MobileCal.app/MobileCal
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/


@protocol EKEventGestureControllerUntimedDelegate
@required
-(id)touchTrackingViewForEventGestureController:(id)arg1;
-(BOOL)eventGestureControllerShouldAllowLongPress:(id)arg1;
-(void)eventGestureController:(id)arg1 setUpAtPoint:(CGPoint)arg2;
-(void)eventGestureController:(id)arg1 updateToPoint:(CGPoint)arg2;
-(void)eventGestureControllerCancelled:(id)arg1;
-(void)eventGestureController:(id)arg1 commitToPoint:(CGPoint)arg2;
-(void)eventGestureControllerScrollTimerFired:(id)arg1;
@end

