/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 1:38:33 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/MobileCal.app/MobileCal
* classdump-dyld is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/

#import <MobileCal/MobileCal-Structs.h>
#import <MobileCal/InfiniteScrollViewController.h>
#import <MobileCal/MainViewController.h>

@class CalendarModel, EKCalendarDate, MonthTitleView, UIFont;

@interface MonthViewController : InfiniteScrollViewController <MainViewController> {

	CalendarModel* _model;
	EKCalendarDate* _backButtonDate;
	BOOL _backButtonShowingInterval;
	BOOL _currentlyDisplayed;
	float _decelerationTargetY;
	EKCalendarDate* _decelerationTargetDate;
	MonthTitleView* _monthTitleView;
	BOOL _monthTitleViewIsVisible;
	BOOL _shouldShowMonthTitleHUDWhenScrolling;
	UIFont* _headerFont;

}

@property (readonly) UIFont * headerFont;                                            //@synthesize headerFont=_headerFont - In the implementation block
@property (assign,nonatomic) BOOL shouldShowMonthTitleHUDWhenScrolling;              //@synthesize shouldShowMonthTitleHUDWhenScrolling=_shouldShowMonthTitleHUDWhenScrolling - In the implementation block
+(float)subviewHeightForDate:(id)arg1 orientation:(int)arg2 ;
-(CGRect)frameForTodayHighlight;
-(void)localeChanged;
-(id)initWithCalendarDate:(id)arg1 model:(id)arg2 ;
-(void)_significantTimeChangeOccurred:(id)arg1 ;
-(void)_selectedDateChanged:(id)arg1 ;
-(id)pastMajorBoundaryCalendarDateForCalendarDate:(id)arg1 ;
-(void)showDate:(id)arg1 animated:(BOOL)arg2 ;
-(void)showEvent:(id)arg1 animated:(BOOL)arg2 showDetails:(BOOL)arg3 ;
-(void)willBeginDragging;
-(void)_updateMonthTitle;
-(float)decelerationDistanceThresholdForPreferringMonthBoundary;
-(CGPoint)nearestMajorBoundaryForPoint:(CGPoint)arg1 ;
-(float)decelerationDistanceThresholdForDisplayingMonthBanner;
-(void)didEndScrolling;
-(void)_updateSelectedDateWithCentralView;
-(void)_updateBackButtonOnBackViewControllerToDate:(id)arg1 ;
-(void)updateBackButtonToDate:(id)arg1 ;
-(float)decelerationDistanceThresholdToStopShowingMonthBanner;
-(BOOL)allowsOverriddenRightNavigationBarItems;
-(BOOL)allowsOverriddenToolbarItems;
-(void)showEvent:(id)arg1 animated:(BOOL)arg2 ;
-(void)selectDate:(id)arg1 animated:(BOOL)arg2 ;
-(id)bestDateForNewEvent;
-(BOOL)shouldAnimateScrollToDate:(id)arg1 fromClosestDate:(id)arg2 ;
-(id)futureMajorBoundaryCalendarDateForCalendarDate:(id)arg1 ;
-(void)willEndDraggingWithVelocity:(CGPoint)arg1 targetContentOffset:(inout CGPoint*)arg2 ;
-(id)monthTitleView;
-(CGRect)frameForWeekContainingDate:(id)arg1 ;
-(id)cellWidthsForWeekContainingDate:(id)arg1 ;
-(id)headerFont;
-(BOOL)shouldShowMonthTitleHUDWhenScrolling;
-(void)setShouldShowMonthTitleHUDWhenScrolling:(BOOL)arg1 ;
-(void)significantTimeChangeOccurred;
-(void)dealloc;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)loadView;
-(void)viewDidAppear:(BOOL)arg1 ;
-(void)viewWillDisappear:(BOOL)arg1 ;
-(void)didScroll;
-(void)_localeChanged:(id)arg1 ;
-(void).cxx_destruct;
@end

