/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 1:38:34 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/MobileCal.app/MobileCal
* classdump-dyld is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/

#import <MobileCal/MobileCal-Structs.h>
#import <UIKit/UIView.h>

@class UILabel, EKCalendarDate;

@interface MonthTitleView : UIView {

	UILabel* _titleLabel;
	EKCalendarDate* _calendarDate;

}

@property (nonatomic,retain) EKCalendarDate * calendarDate;              //@synthesize calendarDate=_calendarDate - In the implementation block
-(void)animateVisible:(BOOL)arg1 duration:(double)arg2 completion:(/*^block*/ id)arg3 ;
-(void)setCalendarDate:(id)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(id)backgroundImage;
-(void)setFont:(id)arg1 ;
-(id)calendarDate;
-(void).cxx_destruct;
@end

