/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 1:38:35 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/MobileCal.app/MobileCal
* classdump-dyld is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/

#import <MobileCal/RootViewController.h>

@class RootNavigationController;

@interface PadRootViewController : RootViewController {

	RootNavigationController* _rootNavigationController;

}
-(void)showInvitationForEvent:(id)arg1 ;
-(unsigned)supportedInterfaceOrientations;
-(id)rootNavigationController;
-(void).cxx_destruct;
@end

