/*
* This header is generated by strong_classdump 0.1
* on Wednesday, November 27, 2013 at 12:00:26 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /usr/lib/system/libdispatch.dylib
* strong_classdump is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/

#import <libdispatch.dylib/libdispatch.dylib-Structs.h>
#import <libdispatch.dylib/OS_dispatch_data.h>

@interface OS_dispatch_data_empty : OS_dispatch_data
+(id)allocWithZone:(NSZoneRef)arg1 ;
+(void)load;
-(oneway void)release;
-(id)retain;
-(id)autorelease;
-(unsigned)retainCount;
-(void)_setContext:(void*)arg1 ;
-(void)_setTargetQueue:(id)arg1 ;
-(void*)_getContext;
-(void)_setFinalizer:(/*function pointer*/ void*)arg1 ;
@end

