/*
* This header is generated by classdump-dyld 0.1
* on Thursday, November 28, 2013 at 4:00:57 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Setup.app/Setup
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/

#import <Setup/Setup-Structs.h>
#import <UIKit/UIViewController.h>
#import <Setup/BuddyController.h>

@protocol BuddyControllerDelegate;
@interface BuddyMesaEnrollmentController : UIViewController <BuddyController> {

	<BuddyControllerDelegate>* _delegate;

}

@property (assign,nonatomic) <BuddyControllerDelegate> * delegate;              //@synthesize delegate=_delegate - In the implementation block
-(CGRect)frameForEnrollmentController;
-(void)controllerWasPopped;
-(BOOL)shouldAllowStartOver;
-(BOOL)controllerAllowsNavigatingBack;
-(void)beginEnrollment;
-(void)endEnrollment;
-(void)dealloc;
-(void)setDelegate:(id)arg1 ;
-(id)delegate;
-(void)viewDidLayoutSubviews;
-(void)viewWillAppear:(BOOL)arg1 ;
@end

