/*
* This header is generated by classdump-dyld 0.1
* on Wednesday, November 27, 2013 at 10:36:07 PM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Setup.app/Setup
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/

#import <Setup/SetupChoiceController.h>

@interface BuddyMesaPurchasesChoiceController : SetupChoiceController
+(void)resetMesaForPurchases;
+(void)setMesaForPurchasesEnabled:(BOOL)arg1 ;
+(BOOL)controllerNeedsToRun;
-(void)choice:(id)arg1 resultWasValid:(BOOL)arg2 ;
-(BOOL)wantsNextButton;
-(id)footerDetailText;
-(void)startOver;
-(void)controllerWasPopped;
-(id)init;
-(id)titleText;
@end

