/*
* This header is generated by strong_classdump 0.1
* on Wednesday, November 27, 2013 at 12:02:02 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Setup.app/Setup
* strong_classdump is Copyright © 2013 by Elias Limneos, licensed under GPLv3.
*/

#import <Setup/BuddyTableViewController.h>
#import <UIKit/UITextFieldDelegate.h>

@class BuddyTableViewCell, NSString, UIAlertView;

@interface BuddyEmailSetupPage : BuddyTableViewController <UITextFieldDelegate> {

	BuddyTableViewCell* _username;
	BuddyTableViewCell* _password;
	NSString* _email;
	UIAlertView* _skipSetupAlert;
	id _delegate;

}

@property (nonatomic,copy) NSString * email;              //@synthesize email=_email - In the implementation block
-(void)tryAgain;
-(void)dealloc;
-(void)setDelegate:(id)arg1 ;
-(id)init;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(int)numberOfSectionsInTableView:(id)arg1 ;
-(id)tableView:(id)arg1 titleForFooterInSection:(int)arg2 ;
-(void)alertView:(id)arg1 didDismissWithButtonIndex:(int)arg2 ;
-(void)setEnabled:(BOOL)arg1 ;
-(BOOL)textFieldShouldReturn:(id)arg1 ;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)done;
-(void)setEmail:(id)arg1 ;
-(id)email;
@end

