/*
* This header is generated by classdump-dyld 0.1
* on Thursday, November 28, 2013 at 4:00:58 AM Eastern European Standard Time
* Operating System: Version 7.0.3 (Build 11B511)
* Image Source: /Applications/Setup.app/Setup
* classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
*/

#import <Setup/BuddyAppleIDSignInPage.h>

@interface BuddyExistingAccountSignInPage : BuddyAppleIDSignInPage {

	BOOL _showTwoAccountsLink;

}

@property (assign,nonatomic) BOOL showTwoAccountsLink;              //@synthesize showTwoAccountsLink=_showTwoAccountsLink - In the implementation block
-(void)setShowTwoAccountsLink:(BOOL)arg1 ;
-(id)appleIDController;
-(id)newHeader;
-(id)newFooter;
-(BOOL)showTwoAccountsLink;
-(void)twoAccountsPressed:(id)arg1 ;
-(id)signInTitle;
@end

